ALTER TABLE campaigns
    ADD COLUMN IF NOT EXISTS placement_search BOOLEAN NULL,
    ADD COLUMN IF NOT EXISTS placement_recommendations BOOLEAN NULL,
    ADD COLUMN IF NOT EXISTS wb_created_at TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS wb_started_at TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS wb_updated_at TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS wb_deleted_at TIMESTAMPTZ NULL;

ALTER TABLE campaign_products
    ADD COLUMN IF NOT EXISTS subject_name TEXT NULL,
    ADD COLUMN IF NOT EXISTS bid_search BIGINT NULL,
    ADD COLUMN IF NOT EXISTS bid_recommendations BIGINT NULL;
