// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit_logs.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (workspace_id, user_id, action, entity_type, entity_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, user_id, action, entity_type, entity_id, metadata, created_at
`

type CreateAuditLogParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	Action      string      `json:"action"`
	EntityType  string      `json:"entity_type"`
	EntityID    pgtype.UUID `json:"entity_id"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.WorkspaceID,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogsByWorkspace = `-- name: ListAuditLogsByWorkspace :many
SELECT id, workspace_id, user_id, action, entity_type, entity_id, metadata, created_at FROM audit_logs
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) ListAuditLogsByWorkspace(ctx context.Context, arg ListAuditLogsByWorkspaceParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsFiltered = `-- name: ListAuditLogsFiltered :many
SELECT id, workspace_id, user_id, action, entity_type, entity_id, metadata, created_at FROM audit_logs
WHERE workspace_id = $1
  AND ($4::text IS NULL OR action = $4::text)
  AND ($5::text IS NULL OR entity_type = $5::text)
  AND ($6::uuid IS NULL OR user_id = $6::uuid)
  AND ($7::timestamptz IS NULL OR created_at >= $7::timestamptz)
  AND ($8::timestamptz IS NULL OR created_at <= $8::timestamptz)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsFilteredParams struct {
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	Limit            int32              `json:"limit"`
	Offset           int32              `json:"offset"`
	ActionFilter     pgtype.Text        `json:"action_filter"`
	EntityTypeFilter pgtype.Text        `json:"entity_type_filter"`
	UserIDFilter     pgtype.UUID        `json:"user_id_filter"`
	DateFrom         pgtype.Timestamptz `json:"date_from"`
	DateTo           pgtype.Timestamptz `json:"date_to"`
}

func (q *Queries) ListAuditLogsFiltered(ctx context.Context, arg ListAuditLogsFilteredParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsFiltered,
		arg.WorkspaceID,
		arg.Limit,
		arg.Offset,
		arg.ActionFilter,
		arg.EntityTypeFilter,
		arg.UserIDFilter,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
