// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: batch_stats.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestBidSnapshotsBatch = `-- name: GetLatestBidSnapshotsBatch :many
SELECT DISTINCT ON (bs.phrase_id) bs.id, bs.phrase_id, bs.workspace_id, bs.competitive_bid, bs.leadership_bid, bs.cpm_min, bs.captured_at, bs.created_at
FROM bid_snapshots bs
JOIN phrases p ON p.id = bs.phrase_id
WHERE p.workspace_id = $1
ORDER BY bs.phrase_id, bs.created_at DESC
`

// Returns the latest bid snapshot per phrase for a given workspace.
func (q *Queries) GetLatestBidSnapshotsBatch(ctx context.Context, workspaceID pgtype.UUID) ([]BidSnapshot, error) {
	rows, err := q.db.Query(ctx, getLatestBidSnapshotsBatch, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BidSnapshot{}
	for rows.Next() {
		var i BidSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.PhraseID,
			&i.WorkspaceID,
			&i.CompetitiveBid,
			&i.LeadershipBid,
			&i.CpmMin,
			&i.CapturedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestCampaignStatsBatch = `-- name: GetLatestCampaignStatsBatch :many
SELECT DISTINCT ON (cs.campaign_id) cs.id, cs.campaign_id, cs.date, cs.impressions, cs.clicks, cs.spend, cs.orders, cs.revenue, cs.created_at, cs.updated_at, cs.atbs, cs.canceled, cs.shks
FROM campaign_stats cs
JOIN campaigns c ON c.id = cs.campaign_id
WHERE c.workspace_id = $1
ORDER BY cs.campaign_id, cs.date DESC
`

// Returns the latest stat row per campaign for a given workspace.
func (q *Queries) GetLatestCampaignStatsBatch(ctx context.Context, workspaceID pgtype.UUID) ([]CampaignStat, error) {
	rows, err := q.db.Query(ctx, getLatestCampaignStatsBatch, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignStat{}
	for rows.Next() {
		var i CampaignStat
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Date,
			&i.Impressions,
			&i.Clicks,
			&i.Spend,
			&i.Orders,
			&i.Revenue,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Atbs,
			&i.Canceled,
			&i.Shks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestPhraseStatsBatch = `-- name: GetLatestPhraseStatsBatch :many
SELECT DISTINCT ON (ps.phrase_id) ps.id, ps.phrase_id, ps.date, ps.impressions, ps.clicks, ps.spend, ps.created_at, ps.updated_at, ps.atbs, ps.orders, ps.cpc, ps.cpm, ps.avg_pos
FROM phrase_stats ps
JOIN phrases p ON p.id = ps.phrase_id
WHERE p.workspace_id = $1
ORDER BY ps.phrase_id, ps.date DESC
`

// Returns the latest stat row per phrase for a given workspace.
func (q *Queries) GetLatestPhraseStatsBatch(ctx context.Context, workspaceID pgtype.UUID) ([]PhraseStat, error) {
	rows, err := q.db.Query(ctx, getLatestPhraseStatsBatch, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PhraseStat{}
	for rows.Next() {
		var i PhraseStat
		if err := rows.Scan(
			&i.ID,
			&i.PhraseID,
			&i.Date,
			&i.Impressions,
			&i.Clicks,
			&i.Spend,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Atbs,
			&i.Orders,
			&i.Cpc,
			&i.Cpm,
			&i.AvgPos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
