// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: bid_snapshots.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBidSnapshot = `-- name: CreateBidSnapshot :one
INSERT INTO bid_snapshots (phrase_id, workspace_id, competitive_bid, leadership_bid, cpm_min, captured_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, phrase_id, workspace_id, competitive_bid, leadership_bid, cpm_min, captured_at, created_at
`

type CreateBidSnapshotParams struct {
	PhraseID       pgtype.UUID        `json:"phrase_id"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	CompetitiveBid int64              `json:"competitive_bid"`
	LeadershipBid  int64              `json:"leadership_bid"`
	CpmMin         int64              `json:"cpm_min"`
	CapturedAt     pgtype.Timestamptz `json:"captured_at"`
}

func (q *Queries) CreateBidSnapshot(ctx context.Context, arg CreateBidSnapshotParams) (BidSnapshot, error) {
	row := q.db.QueryRow(ctx, createBidSnapshot,
		arg.PhraseID,
		arg.WorkspaceID,
		arg.CompetitiveBid,
		arg.LeadershipBid,
		arg.CpmMin,
		arg.CapturedAt,
	)
	var i BidSnapshot
	err := row.Scan(
		&i.ID,
		&i.PhraseID,
		&i.WorkspaceID,
		&i.CompetitiveBid,
		&i.LeadershipBid,
		&i.CpmMin,
		&i.CapturedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestBidSnapshot = `-- name: GetLatestBidSnapshot :one
SELECT id, phrase_id, workspace_id, competitive_bid, leadership_bid, cpm_min, captured_at, created_at FROM bid_snapshots
WHERE phrase_id = $1
ORDER BY captured_at DESC
LIMIT 1
`

func (q *Queries) GetLatestBidSnapshot(ctx context.Context, phraseID pgtype.UUID) (BidSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestBidSnapshot, phraseID)
	var i BidSnapshot
	err := row.Scan(
		&i.ID,
		&i.PhraseID,
		&i.WorkspaceID,
		&i.CompetitiveBid,
		&i.LeadershipBid,
		&i.CpmMin,
		&i.CapturedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listBidSnapshotsByPhrase = `-- name: ListBidSnapshotsByPhrase :many
SELECT id, phrase_id, workspace_id, competitive_bid, leadership_bid, cpm_min, captured_at, created_at FROM bid_snapshots
WHERE phrase_id = $1
  AND ($4::timestamptz IS NULL OR captured_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR captured_at <= $5::timestamptz)
ORDER BY captured_at DESC
LIMIT $2 OFFSET $3
`

type ListBidSnapshotsByPhraseParams struct {
	PhraseID pgtype.UUID        `json:"phrase_id"`
	Limit    int32              `json:"limit"`
	Offset   int32              `json:"offset"`
	DateFrom pgtype.Timestamptz `json:"date_from"`
	DateTo   pgtype.Timestamptz `json:"date_to"`
}

func (q *Queries) ListBidSnapshotsByPhrase(ctx context.Context, arg ListBidSnapshotsByPhraseParams) ([]BidSnapshot, error) {
	rows, err := q.db.Query(ctx, listBidSnapshotsByPhrase,
		arg.PhraseID,
		arg.Limit,
		arg.Offset,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BidSnapshot{}
	for rows.Next() {
		var i BidSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.PhraseID,
			&i.WorkspaceID,
			&i.CompetitiveBid,
			&i.LeadershipBid,
			&i.CpmMin,
			&i.CapturedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBidSnapshotsByWorkspace = `-- name: ListBidSnapshotsByWorkspace :many
SELECT id, phrase_id, workspace_id, competitive_bid, leadership_bid, cpm_min, captured_at, created_at FROM bid_snapshots
WHERE workspace_id = $1
  AND ($4::uuid IS NULL OR phrase_id = $4::uuid)
  AND ($5::timestamptz IS NULL OR captured_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR captured_at <= $6::timestamptz)
ORDER BY captured_at DESC
LIMIT $2 OFFSET $3
`

type ListBidSnapshotsByWorkspaceParams struct {
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	Limit          int32              `json:"limit"`
	Offset         int32              `json:"offset"`
	PhraseIDFilter pgtype.UUID        `json:"phrase_id_filter"`
	DateFrom       pgtype.Timestamptz `json:"date_from"`
	DateTo         pgtype.Timestamptz `json:"date_to"`
}

func (q *Queries) ListBidSnapshotsByWorkspace(ctx context.Context, arg ListBidSnapshotsByWorkspaceParams) ([]BidSnapshot, error) {
	rows, err := q.db.Query(ctx, listBidSnapshotsByWorkspace,
		arg.WorkspaceID,
		arg.Limit,
		arg.Offset,
		arg.PhraseIDFilter,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BidSnapshot{}
	for rows.Next() {
		var i BidSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.PhraseID,
			&i.WorkspaceID,
			&i.CompetitiveBid,
			&i.LeadershipBid,
			&i.CpmMin,
			&i.CapturedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
