// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: campaigns.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const campaignSelectColumns = `id, workspace_id, seller_cabinet_id, wb_campaign_id, name, status, campaign_type, bid_type, payment_type, daily_budget,
  placement_search, placement_recommendations, wb_created_at, wb_started_at, wb_updated_at, wb_deleted_at,
  can_change_nms, created_at, updated_at`

type rowScanner interface {
	Scan(dest ...interface{}) error
}

func scanCampaign(row rowScanner) (Campaign, error) {
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SellerCabinetID,
		&i.WbCampaignID,
		&i.Name,
		&i.Status,
		&i.CampaignType,
		&i.BidType,
		&i.PaymentType,
		&i.DailyBudget,
		&i.PlacementSearch,
		&i.PlacementRecommendations,
		&i.WbCreatedAt,
		&i.WbStartedAt,
		&i.WbUpdatedAt,
		&i.WbDeletedAt,
		&i.CanChangeNms,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (workspace_id, seller_cabinet_id, wb_campaign_id, name, status, campaign_type, bid_type, payment_type, daily_budget)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING ` + campaignSelectColumns + `
`

type CreateCampaignParams struct {
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	WbCampaignID    int64       `json:"wb_campaign_id"`
	Name            string      `json:"name"`
	Status          string      `json:"status"`
	CampaignType    int32       `json:"campaign_type"`
	BidType         string      `json:"bid_type"`
	PaymentType     string      `json:"payment_type"`
	DailyBudget     pgtype.Int8 `json:"daily_budget"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	return scanCampaign(q.db.QueryRow(ctx, createCampaign,
		arg.WorkspaceID,
		arg.SellerCabinetID,
		arg.WbCampaignID,
		arg.Name,
		arg.Status,
		arg.CampaignType,
		arg.BidType,
		arg.PaymentType,
		arg.DailyBudget,
	))
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT ` + campaignSelectColumns + ` FROM campaigns WHERE id = $1
`

func (q *Queries) GetCampaignByID(ctx context.Context, id pgtype.UUID) (Campaign, error) {
	return scanCampaign(q.db.QueryRow(ctx, getCampaignByID, id))
}

const getCampaignByWBCampaignID = `-- name: GetCampaignByWBCampaignID :one
SELECT ` + campaignSelectColumns + ` FROM campaigns
WHERE workspace_id = $1 AND wb_campaign_id = $2
LIMIT 1
`

type GetCampaignByWBCampaignIDParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	WbCampaignID int64       `json:"wb_campaign_id"`
}

func (q *Queries) GetCampaignByWBCampaignID(ctx context.Context, arg GetCampaignByWBCampaignIDParams) (Campaign, error) {
	return scanCampaign(q.db.QueryRow(ctx, getCampaignByWBCampaignID, arg.WorkspaceID, arg.WbCampaignID))
}

const listCampaignsBySellerCabinet = `-- name: ListCampaignsBySellerCabinet :many
SELECT ` + campaignSelectColumns + ` FROM campaigns
WHERE seller_cabinet_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCampaignsBySellerCabinetParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Limit           int32       `json:"limit"`
	Offset          int32       `json:"offset"`
}

func (q *Queries) ListCampaignsBySellerCabinet(ctx context.Context, arg ListCampaignsBySellerCabinetParams) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsBySellerCabinet, arg.SellerCabinetID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		item, err := scanCampaign(rows)
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignsByWorkspace = `-- name: ListCampaignsByWorkspace :many
SELECT ` + campaignSelectColumns + ` FROM campaigns
WHERE workspace_id = $1
  AND ($4::uuid IS NULL OR seller_cabinet_id = $4::uuid)
  AND ($5::text IS NULL OR status = $5::text)
  AND ($6::text IS NULL OR name ILIKE '%' || $6::text || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCampaignsByWorkspaceParams struct {
	WorkspaceID           pgtype.UUID `json:"workspace_id"`
	Limit                 int32       `json:"limit"`
	Offset                int32       `json:"offset"`
	SellerCabinetIDFilter pgtype.UUID `json:"seller_cabinet_id_filter"`
	StatusFilter          pgtype.Text `json:"status_filter"`
	NameFilter            pgtype.Text `json:"name_filter"`
}

func (q *Queries) ListCampaignsByWorkspace(ctx context.Context, arg ListCampaignsByWorkspaceParams) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsByWorkspace,
		arg.WorkspaceID,
		arg.Limit,
		arg.Offset,
		arg.SellerCabinetIDFilter,
		arg.StatusFilter,
		arg.NameFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		item, err := scanCampaign(rows)
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns
SET name = $2, status = $3, bid_type = $4, payment_type = $5, daily_budget = $6, updated_at = now()
WHERE id = $1
RETURNING ` + campaignSelectColumns + `
`

type UpdateCampaignParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Status      string      `json:"status"`
	BidType     string      `json:"bid_type"`
	PaymentType string      `json:"payment_type"`
	DailyBudget pgtype.Int8 `json:"daily_budget"`
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error) {
	return scanCampaign(q.db.QueryRow(ctx, updateCampaign,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.BidType,
		arg.PaymentType,
		arg.DailyBudget,
	))
}

const upsertCampaign = `-- name: UpsertCampaign :one
INSERT INTO campaigns (
  workspace_id, seller_cabinet_id, wb_campaign_id, name, status, campaign_type, bid_type, payment_type, daily_budget,
  placement_search, placement_recommendations, wb_created_at, wb_started_at, wb_updated_at, wb_deleted_at, can_change_nms
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
ON CONFLICT (wb_campaign_id, seller_cabinet_id) DO UPDATE SET
    name = EXCLUDED.name,
    status = EXCLUDED.status,
    campaign_type = EXCLUDED.campaign_type,
    bid_type = EXCLUDED.bid_type,
    payment_type = EXCLUDED.payment_type,
    daily_budget = EXCLUDED.daily_budget,
    placement_search = EXCLUDED.placement_search,
    placement_recommendations = EXCLUDED.placement_recommendations,
    wb_created_at = COALESCE(EXCLUDED.wb_created_at, campaigns.wb_created_at),
    wb_started_at = COALESCE(EXCLUDED.wb_started_at, campaigns.wb_started_at),
    wb_updated_at = COALESCE(EXCLUDED.wb_updated_at, campaigns.wb_updated_at),
    wb_deleted_at = COALESCE(EXCLUDED.wb_deleted_at, campaigns.wb_deleted_at),
    can_change_nms = EXCLUDED.can_change_nms,
    updated_at = now()
RETURNING ` + campaignSelectColumns + `
`

type UpsertCampaignParams struct {
	WorkspaceID              pgtype.UUID        `json:"workspace_id"`
	SellerCabinetID          pgtype.UUID        `json:"seller_cabinet_id"`
	WbCampaignID             int64              `json:"wb_campaign_id"`
	Name                     string             `json:"name"`
	Status                   string             `json:"status"`
	CampaignType             int32              `json:"campaign_type"`
	BidType                  string             `json:"bid_type"`
	PaymentType              string             `json:"payment_type"`
	DailyBudget              pgtype.Int8        `json:"daily_budget"`
	PlacementSearch          pgtype.Bool        `json:"placement_search"`
	PlacementRecommendations pgtype.Bool        `json:"placement_recommendations"`
	WbCreatedAt              pgtype.Timestamptz `json:"wb_created_at"`
	WbStartedAt              pgtype.Timestamptz `json:"wb_started_at"`
	WbUpdatedAt              pgtype.Timestamptz `json:"wb_updated_at"`
	WbDeletedAt              pgtype.Timestamptz `json:"wb_deleted_at"`
	CanChangeNms             pgtype.Bool        `json:"can_change_nms"`
}

func (q *Queries) UpsertCampaign(ctx context.Context, arg UpsertCampaignParams) (Campaign, error) {
	return scanCampaign(q.db.QueryRow(ctx, upsertCampaign,
		arg.WorkspaceID,
		arg.SellerCabinetID,
		arg.WbCampaignID,
		arg.Name,
		arg.Status,
		arg.CampaignType,
		arg.BidType,
		arg.PaymentType,
		arg.DailyBudget,
		arg.PlacementSearch,
		arg.PlacementRecommendations,
		arg.WbCreatedAt,
		arg.WbStartedAt,
		arg.WbUpdatedAt,
		arg.WbDeletedAt,
		arg.CanChangeNms,
	))
}
