// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: campaign_stats.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCampaignStat = `-- name: CreateCampaignStat :one
INSERT INTO campaign_stats (campaign_id, date, impressions, clicks, spend, orders, revenue)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, campaign_id, date, impressions, clicks, spend, orders, revenue, created_at, updated_at
`

type CreateCampaignStatParams struct {
	CampaignID  pgtype.UUID `json:"campaign_id"`
	Date        pgtype.Date `json:"date"`
	Impressions int64       `json:"impressions"`
	Clicks      int64       `json:"clicks"`
	Spend       int64       `json:"spend"`
	Orders      pgtype.Int8 `json:"orders"`
	Revenue     pgtype.Int8 `json:"revenue"`
}

func (q *Queries) CreateCampaignStat(ctx context.Context, arg CreateCampaignStatParams) (CampaignStat, error) {
	row := q.db.QueryRow(ctx, createCampaignStat,
		arg.CampaignID,
		arg.Date,
		arg.Impressions,
		arg.Clicks,
		arg.Spend,
		arg.Orders,
		arg.Revenue,
	)
	var i CampaignStat
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Date,
		&i.Impressions,
		&i.Clicks,
		&i.Spend,
		&i.Orders,
		&i.Revenue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCampaignStatsByDateRange = `-- name: GetCampaignStatsByDateRange :many
SELECT id, campaign_id, date, impressions, clicks, spend, orders, revenue, created_at, updated_at FROM campaign_stats
WHERE campaign_id = $1 AND date BETWEEN $2 AND $3
ORDER BY date
LIMIT $4 OFFSET $5
`

type GetCampaignStatsByDateRangeParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	Date       pgtype.Date `json:"date"`
	Date_2     pgtype.Date `json:"date_2"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) GetCampaignStatsByDateRange(ctx context.Context, arg GetCampaignStatsByDateRangeParams) ([]CampaignStat, error) {
	rows, err := q.db.Query(ctx, getCampaignStatsByDateRange,
		arg.CampaignID,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignStat{}
	for rows.Next() {
		var i CampaignStat
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Date,
			&i.Impressions,
			&i.Clicks,
			&i.Spend,
			&i.Orders,
			&i.Revenue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestCampaignStat = `-- name: GetLatestCampaignStat :one
SELECT id, campaign_id, date, impressions, clicks, spend, orders, revenue, created_at, updated_at FROM campaign_stats
WHERE campaign_id = $1
ORDER BY date DESC
LIMIT 1
`

func (q *Queries) GetLatestCampaignStat(ctx context.Context, campaignID pgtype.UUID) (CampaignStat, error) {
	row := q.db.QueryRow(ctx, getLatestCampaignStat, campaignID)
	var i CampaignStat
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Date,
		&i.Impressions,
		&i.Clicks,
		&i.Spend,
		&i.Orders,
		&i.Revenue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCampaignStatsByWorkspace = `-- name: ListCampaignStatsByWorkspace :many
SELECT cs.id, cs.campaign_id, cs.date, cs.impressions, cs.clicks, cs.spend, cs.orders, cs.revenue, cs.created_at, cs.updated_at FROM campaign_stats cs
JOIN campaigns c ON c.id = cs.campaign_id
WHERE c.workspace_id = $1
ORDER BY cs.date DESC
LIMIT $2 OFFSET $3
`

type ListCampaignStatsByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) ListCampaignStatsByWorkspace(ctx context.Context, arg ListCampaignStatsByWorkspaceParams) ([]CampaignStat, error) {
	rows, err := q.db.Query(ctx, listCampaignStatsByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignStat{}
	for rows.Next() {
		var i CampaignStat
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Date,
			&i.Impressions,
			&i.Clicks,
			&i.Spend,
			&i.Orders,
			&i.Revenue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCampaignStat = `-- name: UpsertCampaignStat :one
INSERT INTO campaign_stats (campaign_id, date, impressions, clicks, spend, orders, revenue)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (campaign_id, date) DO UPDATE SET
    impressions = EXCLUDED.impressions,
    clicks = EXCLUDED.clicks,
    spend = EXCLUDED.spend,
    orders = EXCLUDED.orders,
    revenue = EXCLUDED.revenue,
    updated_at = now()
RETURNING id, campaign_id, date, impressions, clicks, spend, orders, revenue, created_at, updated_at
`

type UpsertCampaignStatParams struct {
	CampaignID  pgtype.UUID `json:"campaign_id"`
	Date        pgtype.Date `json:"date"`
	Impressions int64       `json:"impressions"`
	Clicks      int64       `json:"clicks"`
	Spend       int64       `json:"spend"`
	Orders      pgtype.Int8 `json:"orders"`
	Revenue     pgtype.Int8 `json:"revenue"`
}

func (q *Queries) UpsertCampaignStat(ctx context.Context, arg UpsertCampaignStatParams) (CampaignStat, error) {
	row := q.db.QueryRow(ctx, upsertCampaignStat,
		arg.CampaignID,
		arg.Date,
		arg.Impressions,
		arg.Clicks,
		arg.Spend,
		arg.Orders,
		arg.Revenue,
	)
	var i CampaignStat
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Date,
		&i.Impressions,
		&i.Clicks,
		&i.Spend,
		&i.Orders,
		&i.Revenue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
