// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: campaigns.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (workspace_id, seller_cabinet_id, wb_campaign_id, name, status, campaign_type, bid_type, payment_type, daily_budget)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, workspace_id, seller_cabinet_id, wb_campaign_id, name, status, campaign_type, bid_type, payment_type, daily_budget, created_at, updated_at
`

type CreateCampaignParams struct {
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	WbCampaignID    int64       `json:"wb_campaign_id"`
	Name            string      `json:"name"`
	Status          string      `json:"status"`
	CampaignType    int32       `json:"campaign_type"`
	BidType         string      `json:"bid_type"`
	PaymentType     string      `json:"payment_type"`
	DailyBudget     pgtype.Int8 `json:"daily_budget"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.WorkspaceID,
		arg.SellerCabinetID,
		arg.WbCampaignID,
		arg.Name,
		arg.Status,
		arg.CampaignType,
		arg.BidType,
		arg.PaymentType,
		arg.DailyBudget,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SellerCabinetID,
		&i.WbCampaignID,
		&i.Name,
		&i.Status,
		&i.CampaignType,
		&i.BidType,
		&i.PaymentType,
		&i.DailyBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT id, workspace_id, seller_cabinet_id, wb_campaign_id, name, status, campaign_type, bid_type, payment_type, daily_budget, created_at, updated_at FROM campaigns WHERE id = $1
`

func (q *Queries) GetCampaignByID(ctx context.Context, id pgtype.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByID, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SellerCabinetID,
		&i.WbCampaignID,
		&i.Name,
		&i.Status,
		&i.CampaignType,
		&i.BidType,
		&i.PaymentType,
		&i.DailyBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCampaignByWBCampaignID = `-- name: GetCampaignByWBCampaignID :one
SELECT id, workspace_id, seller_cabinet_id, wb_campaign_id, name, status, campaign_type, bid_type, payment_type, daily_budget, created_at, updated_at FROM campaigns
WHERE workspace_id = $1 AND wb_campaign_id = $2
LIMIT 1
`

type GetCampaignByWBCampaignIDParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	WbCampaignID int64       `json:"wb_campaign_id"`
}

func (q *Queries) GetCampaignByWBCampaignID(ctx context.Context, arg GetCampaignByWBCampaignIDParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByWBCampaignID, arg.WorkspaceID, arg.WbCampaignID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SellerCabinetID,
		&i.WbCampaignID,
		&i.Name,
		&i.Status,
		&i.CampaignType,
		&i.BidType,
		&i.PaymentType,
		&i.DailyBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCampaignsBySellerCabinet = `-- name: ListCampaignsBySellerCabinet :many
SELECT id, workspace_id, seller_cabinet_id, wb_campaign_id, name, status, campaign_type, bid_type, payment_type, daily_budget, created_at, updated_at FROM campaigns
WHERE seller_cabinet_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCampaignsBySellerCabinetParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Limit           int32       `json:"limit"`
	Offset          int32       `json:"offset"`
}

func (q *Queries) ListCampaignsBySellerCabinet(ctx context.Context, arg ListCampaignsBySellerCabinetParams) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsBySellerCabinet, arg.SellerCabinetID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SellerCabinetID,
			&i.WbCampaignID,
			&i.Name,
			&i.Status,
			&i.CampaignType,
			&i.BidType,
			&i.PaymentType,
			&i.DailyBudget,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignsByWorkspace = `-- name: ListCampaignsByWorkspace :many
SELECT id, workspace_id, seller_cabinet_id, wb_campaign_id, name, status, campaign_type, bid_type, payment_type, daily_budget, created_at, updated_at FROM campaigns
WHERE workspace_id = $1
  AND ($4::uuid IS NULL OR seller_cabinet_id = $4::uuid)
  AND ($5::text IS NULL OR status = $5::text)
  AND ($6::text IS NULL OR name ILIKE '%' || $6::text || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCampaignsByWorkspaceParams struct {
	WorkspaceID           pgtype.UUID `json:"workspace_id"`
	Limit                 int32       `json:"limit"`
	Offset                int32       `json:"offset"`
	SellerCabinetIDFilter pgtype.UUID `json:"seller_cabinet_id_filter"`
	StatusFilter          pgtype.Text `json:"status_filter"`
	NameFilter            pgtype.Text `json:"name_filter"`
}

func (q *Queries) ListCampaignsByWorkspace(ctx context.Context, arg ListCampaignsByWorkspaceParams) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsByWorkspace,
		arg.WorkspaceID,
		arg.Limit,
		arg.Offset,
		arg.SellerCabinetIDFilter,
		arg.StatusFilter,
		arg.NameFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SellerCabinetID,
			&i.WbCampaignID,
			&i.Name,
			&i.Status,
			&i.CampaignType,
			&i.BidType,
			&i.PaymentType,
			&i.DailyBudget,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns
SET name = $2, status = $3, bid_type = $4, payment_type = $5, daily_budget = $6, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, seller_cabinet_id, wb_campaign_id, name, status, campaign_type, bid_type, payment_type, daily_budget, created_at, updated_at
`

type UpdateCampaignParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Status      string      `json:"status"`
	BidType     string      `json:"bid_type"`
	PaymentType string      `json:"payment_type"`
	DailyBudget pgtype.Int8 `json:"daily_budget"`
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaign,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.BidType,
		arg.PaymentType,
		arg.DailyBudget,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SellerCabinetID,
		&i.WbCampaignID,
		&i.Name,
		&i.Status,
		&i.CampaignType,
		&i.BidType,
		&i.PaymentType,
		&i.DailyBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCampaign = `-- name: UpsertCampaign :one
INSERT INTO campaigns (workspace_id, seller_cabinet_id, wb_campaign_id, name, status, campaign_type, bid_type, payment_type, daily_budget)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (wb_campaign_id, seller_cabinet_id) DO UPDATE SET
    name = EXCLUDED.name,
    status = EXCLUDED.status,
    campaign_type = EXCLUDED.campaign_type,
    bid_type = EXCLUDED.bid_type,
    payment_type = EXCLUDED.payment_type,
    daily_budget = EXCLUDED.daily_budget,
    updated_at = now()
RETURNING id, workspace_id, seller_cabinet_id, wb_campaign_id, name, status, campaign_type, bid_type, payment_type, daily_budget, created_at, updated_at
`

type UpsertCampaignParams struct {
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	WbCampaignID    int64       `json:"wb_campaign_id"`
	Name            string      `json:"name"`
	Status          string      `json:"status"`
	CampaignType    int32       `json:"campaign_type"`
	BidType         string      `json:"bid_type"`
	PaymentType     string      `json:"payment_type"`
	DailyBudget     pgtype.Int8 `json:"daily_budget"`
}

func (q *Queries) UpsertCampaign(ctx context.Context, arg UpsertCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, upsertCampaign,
		arg.WorkspaceID,
		arg.SellerCabinetID,
		arg.WbCampaignID,
		arg.Name,
		arg.Status,
		arg.CampaignType,
		arg.BidType,
		arg.PaymentType,
		arg.DailyBudget,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SellerCabinetID,
		&i.WbCampaignID,
		&i.Name,
		&i.Status,
		&i.CampaignType,
		&i.BidType,
		&i.PaymentType,
		&i.DailyBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
