// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package sqlcgen

import (
	"context"
)

// iteratorForBatchCreateSERPResultItems implements pgx.CopyFromSource.
type iteratorForBatchCreateSERPResultItems struct {
	rows                 []BatchCreateSERPResultItemsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchCreateSERPResultItems) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchCreateSERPResultItems) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SnapshotID,
		r.rows[0].Position,
		r.rows[0].WbProductID,
		r.rows[0].Title,
		r.rows[0].Price,
		r.rows[0].Rating,
		r.rows[0].ReviewsCount,
	}, nil
}

func (r iteratorForBatchCreateSERPResultItems) Err() error {
	return nil
}

func (q *Queries) BatchCreateSERPResultItems(ctx context.Context, arg []BatchCreateSERPResultItemsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"serp_result_items"}, []string{"snapshot_id", "position", "wb_product_id", "title", "price", "rating", "reviews_count"}, &iteratorForBatchCreateSERPResultItems{rows: arg})
}
