// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: counts.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogsByWorkspace = `-- name: CountAuditLogsByWorkspace :one
SELECT COUNT(*) FROM audit_logs WHERE workspace_id = $1
`

func (q *Queries) CountAuditLogsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogsByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBidSnapshotsByWorkspace = `-- name: CountBidSnapshotsByWorkspace :one
SELECT COUNT(*) FROM bid_snapshots bs
JOIN phrases p ON p.id = bs.phrase_id
WHERE p.workspace_id = $1
`

func (q *Queries) CountBidSnapshotsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBidSnapshotsByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCampaignsByWorkspace = `-- name: CountCampaignsByWorkspace :one
SELECT COUNT(*) FROM campaigns WHERE workspace_id = $1
`

func (q *Queries) CountCampaignsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCampaignsByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countExportsByWorkspace = `-- name: CountExportsByWorkspace :one
SELECT COUNT(*) FROM exports WHERE workspace_id = $1
`

func (q *Queries) CountExportsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countExportsByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJobRunsByWorkspace = `-- name: CountJobRunsByWorkspace :one
SELECT COUNT(*) FROM job_runs WHERE workspace_id = $1
`

func (q *Queries) CountJobRunsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countJobRunsByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPhrasesByWorkspace = `-- name: CountPhrasesByWorkspace :one
SELECT COUNT(*) FROM phrases WHERE workspace_id = $1
`

func (q *Queries) CountPhrasesByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPhrasesByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPositionsByWorkspace = `-- name: CountPositionsByWorkspace :one
SELECT COUNT(*) FROM positions WHERE workspace_id = $1
`

func (q *Queries) CountPositionsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPositionsByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsByWorkspace = `-- name: CountProductsByWorkspace :one
SELECT COUNT(*) FROM products WHERE workspace_id = $1
`

func (q *Queries) CountProductsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecommendationsByWorkspace = `-- name: CountRecommendationsByWorkspace :one
SELECT COUNT(*) FROM recommendations WHERE workspace_id = $1 AND status = 'active'
`

func (q *Queries) CountRecommendationsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRecommendationsByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
