// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exports.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExport = `-- name: CreateExport :one
INSERT INTO exports (workspace_id, user_id, entity_type, format, filters)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, user_id, entity_type, format, status, file_path, error_message, filters, created_at, updated_at
`

type CreateExportParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	EntityType  string      `json:"entity_type"`
	Format      string      `json:"format"`
	Filters     []byte      `json:"filters"`
}

func (q *Queries) CreateExport(ctx context.Context, arg CreateExportParams) (Export, error) {
	row := q.db.QueryRow(ctx, createExport,
		arg.WorkspaceID,
		arg.UserID,
		arg.EntityType,
		arg.Format,
		arg.Filters,
	)
	var i Export
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.EntityType,
		&i.Format,
		&i.Status,
		&i.FilePath,
		&i.ErrorMessage,
		&i.Filters,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExportByID = `-- name: GetExportByID :one
SELECT id, workspace_id, user_id, entity_type, format, status, file_path, error_message, filters, created_at, updated_at FROM exports WHERE id = $1
`

func (q *Queries) GetExportByID(ctx context.Context, id pgtype.UUID) (Export, error) {
	row := q.db.QueryRow(ctx, getExportByID, id)
	var i Export
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.EntityType,
		&i.Format,
		&i.Status,
		&i.FilePath,
		&i.ErrorMessage,
		&i.Filters,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExportsByWorkspace = `-- name: ListExportsByWorkspace :many
SELECT id, workspace_id, user_id, entity_type, format, status, file_path, error_message, filters, created_at, updated_at FROM exports
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListExportsByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) ListExportsByWorkspace(ctx context.Context, arg ListExportsByWorkspaceParams) ([]Export, error) {
	rows, err := q.db.Query(ctx, listExportsByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Export{}
	for rows.Next() {
		var i Export
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.EntityType,
			&i.Format,
			&i.Status,
			&i.FilePath,
			&i.ErrorMessage,
			&i.Filters,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExportStatus = `-- name: UpdateExportStatus :one
UPDATE exports
SET status = $2, file_path = $3, error_message = $4, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, user_id, entity_type, format, status, file_path, error_message, filters, created_at, updated_at
`

type UpdateExportStatusParams struct {
	ID           pgtype.UUID `json:"id"`
	Status       string      `json:"status"`
	FilePath     pgtype.Text `json:"file_path"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateExportStatus(ctx context.Context, arg UpdateExportStatusParams) (Export, error) {
	row := q.db.QueryRow(ctx, updateExportStatus,
		arg.ID,
		arg.Status,
		arg.FilePath,
		arg.ErrorMessage,
	)
	var i Export
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.EntityType,
		&i.Format,
		&i.Status,
		&i.FilePath,
		&i.ErrorMessage,
		&i.Filters,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
