// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: extension_sessions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExtensionSession = `-- name: CreateExtensionSession :one
INSERT INTO extension_sessions (user_id, workspace_id, extension_version, last_active_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, workspace_id, extension_version, last_active_at, created_at
`

type CreateExtensionSessionParams struct {
	UserID           pgtype.UUID        `json:"user_id"`
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ExtensionVersion string             `json:"extension_version"`
	LastActiveAt     pgtype.Timestamptz `json:"last_active_at"`
}

func (q *Queries) CreateExtensionSession(ctx context.Context, arg CreateExtensionSessionParams) (ExtensionSession, error) {
	row := q.db.QueryRow(ctx, createExtensionSession,
		arg.UserID,
		arg.WorkspaceID,
		arg.ExtensionVersion,
		arg.LastActiveAt,
	)
	var i ExtensionSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.ExtensionVersion,
		&i.LastActiveAt,
		&i.CreatedAt,
	)
	return i, err
}

const getExtensionSession = `-- name: GetExtensionSession :one
SELECT id, user_id, workspace_id, extension_version, last_active_at, created_at FROM extension_sessions
WHERE user_id = $1 AND workspace_id = $2
`

type GetExtensionSessionParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetExtensionSession(ctx context.Context, arg GetExtensionSessionParams) (ExtensionSession, error) {
	row := q.db.QueryRow(ctx, getExtensionSession, arg.UserID, arg.WorkspaceID)
	var i ExtensionSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.ExtensionVersion,
		&i.LastActiveAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateExtensionSession = `-- name: UpdateExtensionSession :one
UPDATE extension_sessions
SET extension_version = $2,
    last_active_at = $3
WHERE id = $1
RETURNING id, user_id, workspace_id, extension_version, last_active_at, created_at
`

type UpdateExtensionSessionParams struct {
	ID               pgtype.UUID        `json:"id"`
	ExtensionVersion string             `json:"extension_version"`
	LastActiveAt     pgtype.Timestamptz `json:"last_active_at"`
}

func (q *Queries) UpdateExtensionSession(ctx context.Context, arg UpdateExtensionSessionParams) (ExtensionSession, error) {
	row := q.db.QueryRow(ctx, updateExtensionSession, arg.ID, arg.ExtensionVersion, arg.LastActiveAt)
	var i ExtensionSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.ExtensionVersion,
		&i.LastActiveAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateExtensionSessionActivity = `-- name: UpdateExtensionSessionActivity :exec
UPDATE extension_sessions
SET last_active_at = now()
WHERE id = $1
`

func (q *Queries) UpdateExtensionSessionActivity(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateExtensionSessionActivity, id)
	return err
}
