// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: extension_context_events.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExtensionContextEvent = `-- name: CreateExtensionContextEvent :one
INSERT INTO extension_context_events (session_id, workspace_id, user_id, url, page_type, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, session_id, workspace_id, user_id, url, page_type, metadata, created_at
`

type CreateExtensionContextEventParams struct {
	SessionID   pgtype.UUID `json:"session_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	Url         string      `json:"url"`
	PageType    string      `json:"page_type"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateExtensionContextEvent(ctx context.Context, arg CreateExtensionContextEventParams) (ExtensionContextEvent, error) {
	row := q.db.QueryRow(ctx, createExtensionContextEvent,
		arg.SessionID,
		arg.WorkspaceID,
		arg.UserID,
		arg.Url,
		arg.PageType,
		arg.Metadata,
	)
	var i ExtensionContextEvent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Url,
		&i.PageType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
