// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: job_runs.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJobRun = `-- name: CreateJobRun :one
INSERT INTO job_runs (workspace_id, task_type, status, started_at, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, task_type, status, started_at, finished_at, error_message, metadata, created_at
`

type CreateJobRunParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	TaskType    string             `json:"task_type"`
	Status      string             `json:"status"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	Metadata    []byte             `json:"metadata"`
}

func (q *Queries) CreateJobRun(ctx context.Context, arg CreateJobRunParams) (JobRun, error) {
	row := q.db.QueryRow(ctx, createJobRun,
		arg.WorkspaceID,
		arg.TaskType,
		arg.Status,
		arg.StartedAt,
		arg.Metadata,
	)
	var i JobRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TaskType,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getJobRunByID = `-- name: GetJobRunByID :one
SELECT id, workspace_id, task_type, status, started_at, finished_at, error_message, metadata, created_at FROM job_runs WHERE id = $1
`

func (q *Queries) GetJobRunByID(ctx context.Context, id pgtype.UUID) (JobRun, error) {
	row := q.db.QueryRow(ctx, getJobRunByID, id)
	var i JobRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TaskType,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listJobRunsByTaskType = `-- name: ListJobRunsByTaskType :many
SELECT id, workspace_id, task_type, status, started_at, finished_at, error_message, metadata, created_at FROM job_runs
WHERE task_type = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListJobRunsByTaskTypeParams struct {
	TaskType string `json:"task_type"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListJobRunsByTaskType(ctx context.Context, arg ListJobRunsByTaskTypeParams) ([]JobRun, error) {
	rows, err := q.db.Query(ctx, listJobRunsByTaskType, arg.TaskType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobRun{}
	for rows.Next() {
		var i JobRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TaskType,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorMessage,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobRunsByWorkspace = `-- name: ListJobRunsByWorkspace :many
SELECT id, workspace_id, task_type, status, started_at, finished_at, error_message, metadata, created_at FROM job_runs
WHERE workspace_id = $1
  AND ($4::text IS NULL OR task_type = $4::text)
  AND ($5::text IS NULL OR status = $5::text)
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListJobRunsByWorkspaceParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
	TaskTypeFilter pgtype.Text `json:"task_type_filter"`
	StatusFilter   pgtype.Text `json:"status_filter"`
}

func (q *Queries) ListJobRunsByWorkspace(ctx context.Context, arg ListJobRunsByWorkspaceParams) ([]JobRun, error) {
	rows, err := q.db.Query(ctx, listJobRunsByWorkspace,
		arg.WorkspaceID,
		arg.Limit,
		arg.Offset,
		arg.TaskTypeFilter,
		arg.StatusFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobRun{}
	for rows.Next() {
		var i JobRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TaskType,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorMessage,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobRunStatus = `-- name: UpdateJobRunStatus :one
UPDATE job_runs
SET status = $2, finished_at = $3, error_message = $4, metadata = $5
WHERE id = $1
RETURNING id, workspace_id, task_type, status, started_at, finished_at, error_message, metadata, created_at
`

type UpdateJobRunStatusParams struct {
	ID           pgtype.UUID        `json:"id"`
	Status       string             `json:"status"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	Metadata     []byte             `json:"metadata"`
}

func (q *Queries) UpdateJobRunStatus(ctx context.Context, arg UpdateJobRunStatusParams) (JobRun, error) {
	row := q.db.QueryRow(ctx, updateJobRunStatus,
		arg.ID,
		arg.Status,
		arg.FinishedAt,
		arg.ErrorMessage,
		arg.Metadata,
	)
	var i JobRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TaskType,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
