// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Action      string             `json:"action"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type BidSnapshot struct {
	ID             pgtype.UUID        `json:"id"`
	PhraseID       pgtype.UUID        `json:"phrase_id"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	CompetitiveBid int64              `json:"competitive_bid"`
	LeadershipBid  int64              `json:"leadership_bid"`
	CpmMin         int64              `json:"cpm_min"`
	CapturedAt     pgtype.Timestamptz `json:"captured_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Campaign struct {
	ID              pgtype.UUID        `json:"id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	SellerCabinetID pgtype.UUID        `json:"seller_cabinet_id"`
	WbCampaignID    int64              `json:"wb_campaign_id"`
	Name            string             `json:"name"`
	Status          string             `json:"status"`
	CampaignType    int32              `json:"campaign_type"`
	BidType         string             `json:"bid_type"`
	PaymentType     string             `json:"payment_type"`
	DailyBudget     pgtype.Int8        `json:"daily_budget"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CampaignStat struct {
	ID          pgtype.UUID        `json:"id"`
	CampaignID  pgtype.UUID        `json:"campaign_id"`
	Date        pgtype.Date        `json:"date"`
	Impressions int64              `json:"impressions"`
	Clicks      int64              `json:"clicks"`
	Spend       int64              `json:"spend"`
	Orders      pgtype.Int8        `json:"orders"`
	Revenue     pgtype.Int8        `json:"revenue"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Atbs        pgtype.Int8        `json:"atbs"`
	Canceled    pgtype.Int8        `json:"canceled"`
}

type Competitor struct {
	ID                     pgtype.UUID        `json:"id"`
	WorkspaceID            pgtype.UUID        `json:"workspace_id"`
	ProductID              pgtype.UUID        `json:"product_id"`
	CompetitorNmID         int64              `json:"competitor_nm_id"`
	CompetitorTitle        string             `json:"competitor_title"`
	CompetitorBrand        pgtype.Text        `json:"competitor_brand"`
	CompetitorPrice        pgtype.Int8        `json:"competitor_price"`
	CompetitorRating       pgtype.Float8      `json:"competitor_rating"`
	CompetitorReviewsCount pgtype.Int4        `json:"competitor_reviews_count"`
	CompetitorImageUrl     pgtype.Text        `json:"competitor_image_url"`
	Query                  string             `json:"query"`
	Region                 pgtype.Text        `json:"region"`
	FirstSeenAt            pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt             pgtype.Timestamptz `json:"last_seen_at"`
	LastPosition           pgtype.Int4        `json:"last_position"`
	OurPosition            pgtype.Int4        `json:"our_position"`
	Source                 string             `json:"source"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type CompetitorSnapshot struct {
	ID           pgtype.UUID        `json:"id"`
	CompetitorID pgtype.UUID        `json:"competitor_id"`
	Price        pgtype.Int8        `json:"price"`
	Rating       pgtype.Float8      `json:"rating"`
	ReviewsCount pgtype.Int4        `json:"reviews_count"`
	Position     pgtype.Int4        `json:"position"`
	OurPosition  pgtype.Int4        `json:"our_position"`
	CapturedAt   pgtype.Timestamptz `json:"captured_at"`
}

type DeliveryDatum struct {
	ID           pgtype.UUID        `json:"id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	ProductID    pgtype.UUID        `json:"product_id"`
	Region       string             `json:"region"`
	Warehouse    pgtype.Text        `json:"warehouse"`
	DeliveryDays pgtype.Int4        `json:"delivery_days"`
	DeliveryCost pgtype.Int8        `json:"delivery_cost"`
	InStock      pgtype.Bool        `json:"in_stock"`
	CapturedAt   pgtype.Timestamptz `json:"captured_at"`
}

type Export struct {
	ID           pgtype.UUID        `json:"id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	EntityType   string             `json:"entity_type"`
	Format       string             `json:"format"`
	Status       string             `json:"status"`
	FilePath     pgtype.Text        `json:"file_path"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	Filters      []byte             `json:"filters"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ExtensionBidSnapshot struct {
	ID              pgtype.UUID        `json:"id"`
	SessionID       pgtype.UUID        `json:"session_id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	SellerCabinetID pgtype.UUID        `json:"seller_cabinet_id"`
	CampaignID      pgtype.UUID        `json:"campaign_id"`
	PhraseID        pgtype.UUID        `json:"phrase_id"`
	Query           pgtype.Text        `json:"query"`
	Region          pgtype.Text        `json:"region"`
	VisibleBid      pgtype.Int8        `json:"visible_bid"`
	RecommendedBid  pgtype.Int8        `json:"recommended_bid"`
	CompetitiveBid  pgtype.Int8        `json:"competitive_bid"`
	LeadershipBid   pgtype.Int8        `json:"leadership_bid"`
	CpmMin          pgtype.Int8        `json:"cpm_min"`
	Source          string             `json:"source"`
	Confidence      pgtype.Numeric     `json:"confidence"`
	Metadata        []byte             `json:"metadata"`
	DedupeKey       string             `json:"dedupe_key"`
	CapturedAt      pgtype.Timestamptz `json:"captured_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ExtensionContextEvent struct {
	ID          pgtype.UUID        `json:"id"`
	SessionID   pgtype.UUID        `json:"session_id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Url         string             `json:"url"`
	PageType    string             `json:"page_type"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ExtensionNetworkCapture struct {
	ID              pgtype.UUID        `json:"id"`
	SessionID       pgtype.UUID        `json:"session_id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	SellerCabinetID pgtype.UUID        `json:"seller_cabinet_id"`
	CampaignID      pgtype.UUID        `json:"campaign_id"`
	PhraseID        pgtype.UUID        `json:"phrase_id"`
	ProductID       pgtype.UUID        `json:"product_id"`
	PageType        string             `json:"page_type"`
	EndpointKey     string             `json:"endpoint_key"`
	Query           pgtype.Text        `json:"query"`
	Region          pgtype.Text        `json:"region"`
	Payload         []byte             `json:"payload"`
	DedupeKey       string             `json:"dedupe_key"`
	CapturedAt      pgtype.Timestamptz `json:"captured_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ExtensionPageContext struct {
	ID              pgtype.UUID        `json:"id"`
	SessionID       pgtype.UUID        `json:"session_id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Url             string             `json:"url"`
	PageType        string             `json:"page_type"`
	SellerCabinetID pgtype.UUID        `json:"seller_cabinet_id"`
	CampaignID      pgtype.UUID        `json:"campaign_id"`
	PhraseID        pgtype.UUID        `json:"phrase_id"`
	ProductID       pgtype.UUID        `json:"product_id"`
	Query           pgtype.Text        `json:"query"`
	Region          pgtype.Text        `json:"region"`
	ActiveFilters   []byte             `json:"active_filters"`
	Metadata        []byte             `json:"metadata"`
	DedupeKey       string             `json:"dedupe_key"`
	CapturedAt      pgtype.Timestamptz `json:"captured_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ExtensionPositionSnapshot struct {
	ID              pgtype.UUID        `json:"id"`
	SessionID       pgtype.UUID        `json:"session_id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	SellerCabinetID pgtype.UUID        `json:"seller_cabinet_id"`
	CampaignID      pgtype.UUID        `json:"campaign_id"`
	PhraseID        pgtype.UUID        `json:"phrase_id"`
	ProductID       pgtype.UUID        `json:"product_id"`
	Query           string             `json:"query"`
	Region          string             `json:"region"`
	VisiblePosition int32              `json:"visible_position"`
	VisiblePage     pgtype.Int4        `json:"visible_page"`
	PageSubtype     pgtype.Text        `json:"page_subtype"`
	Source          string             `json:"source"`
	Confidence      pgtype.Numeric     `json:"confidence"`
	Metadata        []byte             `json:"metadata"`
	DedupeKey       string             `json:"dedupe_key"`
	CapturedAt      pgtype.Timestamptz `json:"captured_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ExtensionSession struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ExtensionVersion string             `json:"extension_version"`
	LastActiveAt     pgtype.Timestamptz `json:"last_active_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type ExtensionUiSignal struct {
	ID              pgtype.UUID        `json:"id"`
	SessionID       pgtype.UUID        `json:"session_id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	SellerCabinetID pgtype.UUID        `json:"seller_cabinet_id"`
	CampaignID      pgtype.UUID        `json:"campaign_id"`
	PhraseID        pgtype.UUID        `json:"phrase_id"`
	ProductID       pgtype.UUID        `json:"product_id"`
	Query           pgtype.Text        `json:"query"`
	Region          pgtype.Text        `json:"region"`
	SignalType      string             `json:"signal_type"`
	Severity        string             `json:"severity"`
	Title           string             `json:"title"`
	Message         pgtype.Text        `json:"message"`
	Confidence      pgtype.Numeric     `json:"confidence"`
	Metadata        []byte             `json:"metadata"`
	DedupeKey       string             `json:"dedupe_key"`
	CapturedAt      pgtype.Timestamptz `json:"captured_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type JobRun struct {
	ID           pgtype.UUID        `json:"id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	TaskType     string             `json:"task_type"`
	Status       string             `json:"status"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Keyword struct {
	ID             pgtype.UUID        `json:"id"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	Query          string             `json:"query"`
	Normalized     string             `json:"normalized"`
	Frequency      pgtype.Int4        `json:"frequency"`
	FrequencyTrend pgtype.Text        `json:"frequency_trend"`
	ClusterID      pgtype.UUID        `json:"cluster_id"`
	Source         string             `json:"source"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type KeywordCluster struct {
	ID             pgtype.UUID        `json:"id"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	Name           string             `json:"name"`
	MainKeyword    string             `json:"main_keyword"`
	KeywordCount   pgtype.Int4        `json:"keyword_count"`
	TotalFrequency pgtype.Int4        `json:"total_frequency"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type KeywordFrequencyHistory struct {
	ID        pgtype.UUID        `json:"id"`
	KeywordID pgtype.UUID        `json:"keyword_id"`
	Frequency int32              `json:"frequency"`
	CheckedAt pgtype.Timestamptz `json:"checked_at"`
}

type KeywordRelation struct {
	ID           pgtype.UUID        `json:"id"`
	KeywordID    pgtype.UUID        `json:"keyword_id"`
	RelatedID    pgtype.UUID        `json:"related_id"`
	RelationType string             `json:"relation_type"`
	Strength     pgtype.Float8      `json:"strength"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Phrase struct {
	ID          pgtype.UUID        `json:"id"`
	CampaignID  pgtype.UUID        `json:"campaign_id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ProductID   pgtype.UUID        `json:"product_id"`
	WbProductID pgtype.Int8        `json:"wb_product_id"`
	WbClusterID pgtype.Int8        `json:"wb_cluster_id"`
	WbNormQuery string             `json:"wb_norm_query"`
	Keyword     string             `json:"keyword"`
	Count       pgtype.Int4        `json:"count"`
	CurrentBid  pgtype.Int8        `json:"current_bid"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PhraseStat struct {
	ID          pgtype.UUID        `json:"id"`
	PhraseID    pgtype.UUID        `json:"phrase_id"`
	Date        pgtype.Date        `json:"date"`
	Impressions int64              `json:"impressions"`
	Clicks      int64              `json:"clicks"`
	Spend       int64              `json:"spend"`
	Atbs        pgtype.Int8        `json:"atbs"`
	Orders      pgtype.Int8        `json:"orders"`
	Cpc         pgtype.Float8      `json:"cpc"`
	Cpm         pgtype.Float8      `json:"cpm"`
	AvgPos      pgtype.Float8      `json:"avg_pos"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Position struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ProductID   pgtype.UUID        `json:"product_id"`
	Query       string             `json:"query"`
	Region      string             `json:"region"`
	Position    int32              `json:"position"`
	Page        int32              `json:"page"`
	Source      string             `json:"source"`
	CheckedAt   pgtype.Timestamptz `json:"checked_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PositionTrackingTarget struct {
	ID                pgtype.UUID        `json:"id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	ProductID         pgtype.UUID        `json:"product_id"`
	Query             string             `json:"query"`
	Region            string             `json:"region"`
	IsActive          bool               `json:"is_active"`
	BaselinePosition  pgtype.Int4        `json:"baseline_position"`
	BaselineCheckedAt pgtype.Timestamptz `json:"baseline_checked_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID                  pgtype.UUID        `json:"id"`
	WorkspaceID         pgtype.UUID        `json:"workspace_id"`
	SellerCabinetID     pgtype.UUID        `json:"seller_cabinet_id"`
	WbProductID         int64              `json:"wb_product_id"`
	Title               string             `json:"title"`
	Brand               pgtype.Text        `json:"brand"`
	Category            pgtype.Text        `json:"category"`
	ImageUrl            pgtype.Text        `json:"image_url"`
	Price               pgtype.Int8        `json:"price"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CurrentBidSearch    pgtype.Int4        `json:"current_bid_search"`
	CurrentBidRecommend pgtype.Int4        `json:"current_bid_recommend"`
	MinBidSearch        pgtype.Int4        `json:"min_bid_search"`
	MinBidRecommend     pgtype.Int4        `json:"min_bid_recommend"`
	CompetitiveBid      pgtype.Int4        `json:"competitive_bid"`
	Rating              pgtype.Float8      `json:"rating"`
	ReviewsCount        pgtype.Int4        `json:"reviews_count"`
	StockTotal          pgtype.Int4        `json:"stock_total"`
	ContentHash         pgtype.Text        `json:"content_hash"`
	LastEventAt         pgtype.Timestamptz `json:"last_event_at"`
}

type ProductSnapshot struct {
	ID           pgtype.UUID        `json:"id"`
	ProductID    pgtype.UUID        `json:"product_id"`
	Title        pgtype.Text        `json:"title"`
	Brand        pgtype.Text        `json:"brand"`
	Category     pgtype.Text        `json:"category"`
	Price        pgtype.Int8        `json:"price"`
	Rating       pgtype.Float8      `json:"rating"`
	ReviewsCount pgtype.Int4        `json:"reviews_count"`
	StockTotal   pgtype.Int4        `json:"stock_total"`
	ImageUrl     pgtype.Text        `json:"image_url"`
	ContentHash  pgtype.Text        `json:"content_hash"`
	CapturedAt   pgtype.Timestamptz `json:"captured_at"`
}

type Recommendation struct {
	ID            pgtype.UUID        `json:"id"`
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	CampaignID    pgtype.UUID        `json:"campaign_id"`
	PhraseID      pgtype.UUID        `json:"phrase_id"`
	ProductID     pgtype.UUID        `json:"product_id"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	Type          string             `json:"type"`
	Severity      string             `json:"severity"`
	Confidence    pgtype.Numeric     `json:"confidence"`
	SourceMetrics []byte             `json:"source_metrics"`
	NextAction    pgtype.Text        `json:"next_action"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Revoked   bool               `json:"revoked"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RegionalPositionAggregate struct {
	ID            pgtype.UUID        `json:"id"`
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	ProductID     pgtype.UUID        `json:"product_id"`
	Query         string             `json:"query"`
	Region        string             `json:"region"`
	AvgPosition   float64            `json:"avg_position"`
	BestPosition  pgtype.Int4        `json:"best_position"`
	WorstPosition pgtype.Int4        `json:"worst_position"`
	CheckCount    int32              `json:"check_count"`
	PeriodStart   pgtype.Date        `json:"period_start"`
	PeriodEnd     pgtype.Date        `json:"period_end"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type SellerCabinet struct {
	ID                    pgtype.UUID        `json:"id"`
	WorkspaceID           pgtype.UUID        `json:"workspace_id"`
	Name                  string             `json:"name"`
	EncryptedToken        string             `json:"encrypted_token"`
	Status                string             `json:"status"`
	LastSyncedAt          pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	ExternalIntegrationID pgtype.Text        `json:"external_integration_id"`
	Source                string             `json:"source"`
	IntegrationType       pgtype.Text        `json:"integration_type"`
	LastSellicoSyncAt     pgtype.Timestamptz `json:"last_sellico_sync_at"`
}

type SeoAnalysis struct {
	ID                pgtype.UUID        `json:"id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	ProductID         pgtype.UUID        `json:"product_id"`
	TitleScore        pgtype.Int4        `json:"title_score"`
	DescriptionScore  pgtype.Int4        `json:"description_score"`
	KeywordsScore     pgtype.Int4        `json:"keywords_score"`
	OverallScore      pgtype.Int4        `json:"overall_score"`
	TitleIssues       []byte             `json:"title_issues"`
	DescriptionIssues []byte             `json:"description_issues"`
	KeywordCoverage   []byte             `json:"keyword_coverage"`
	Recommendations   []byte             `json:"recommendations"`
	AnalyzedAt        pgtype.Timestamptz `json:"analyzed_at"`
}

type SerpResultItem struct {
	ID           pgtype.UUID        `json:"id"`
	SnapshotID   pgtype.UUID        `json:"snapshot_id"`
	Position     int32              `json:"position"`
	WbProductID  int64              `json:"wb_product_id"`
	Title        string             `json:"title"`
	Price        pgtype.Int8        `json:"price"`
	Rating       pgtype.Numeric     `json:"rating"`
	ReviewsCount pgtype.Int4        `json:"reviews_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	IsPromoted   pgtype.Bool        `json:"is_promoted"`
	PromoType    pgtype.Text        `json:"promo_type"`
}

type SerpSnapshot struct {
	ID           pgtype.UUID        `json:"id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	Query        string             `json:"query"`
	Region       string             `json:"region"`
	TotalResults int32              `json:"total_results"`
	ScannedAt    pgtype.Timestamptz `json:"scanned_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	Email          string             `json:"email"`
	PasswordHash   string             `json:"password_hash"`
	Name           string             `json:"name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ExternalUserID pgtype.Text        `json:"external_user_id"`
	AuthSource     string             `json:"auth_source"`
}

type WarehouseAnalytic struct {
	ID               pgtype.UUID        `json:"id"`
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	WarehouseName    string             `json:"warehouse_name"`
	Region           string             `json:"region"`
	ProductsCount    pgtype.Int4        `json:"products_count"`
	AvgDeliveryDays  pgtype.Float8      `json:"avg_delivery_days"`
	StockCoveragePct pgtype.Float8      `json:"stock_coverage_pct"`
	CapturedAt       pgtype.Timestamptz `json:"captured_at"`
}

type Workspace struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	Slug                string             `json:"slug"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	ExternalWorkspaceID pgtype.Text        `json:"external_workspace_id"`
	Source              string             `json:"source"`
	// Per-workspace settings: recommendation_thresholds, notifications (telegram bot token / chat id), etc.
	Settings []byte `json:"settings"`
	// AES-256-GCM encrypted Sellico user token for background integration refresh
	EncryptedSellicoToken pgtype.Text `json:"encrypted_sellico_token"`
	// When the cached Sellico token was last updated
	SellicoTokenUpdatedAt pgtype.Timestamptz `json:"sellico_token_updated_at"`
}

type WorkspaceMember struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
