// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ozon_prices.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOzonPriceChangesByCabinet = `-- name: CountOzonPriceChangesByCabinet :one
SELECT COUNT(*) FROM ozon_price_changes
WHERE seller_cabinet_id = $1
  AND ($2::bigint IS NULL OR sku = $2::bigint)
`

type CountOzonPriceChangesByCabinetParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Sku             pgtype.Int8 `json:"sku"`
}

func (q *Queries) CountOzonPriceChangesByCabinet(ctx context.Context, arg CountOzonPriceChangesByCabinetParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOzonPriceChangesByCabinet, arg.SellerCabinetID, arg.Sku)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOzonPriceWritesBySkuSince = `-- name: CountOzonPriceWritesBySkuSince :one
SELECT COUNT(*) FROM ozon_price_changes
WHERE seller_cabinet_id = $1
  AND sku = $2
  AND status IN ('pending', 'applied', 'rolled_back')
  AND created_at >= $3
`

type CountOzonPriceWritesBySkuSinceParams struct {
	SellerCabinetID pgtype.UUID        `json:"seller_cabinet_id"`
	Sku             int64              `json:"sku"`
	Since           pgtype.Timestamptz `json:"since"`
}

// CountOzonPriceWritesBySkuSince feeds the hard hourly write limit (Ozon
// rejects more than 10 price changes per product per hour). Only rows that
// did (or may still) reach Ozon count: pending + applied + rolled_back
// (a rollback is a real write too).
func (q *Queries) CountOzonPriceWritesBySkuSince(ctx context.Context, arg CountOzonPriceWritesBySkuSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOzonPriceWritesBySkuSince, arg.SellerCabinetID, arg.Sku, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOzonStrategyDecisionsBySkuSince = `-- name: CountOzonStrategyDecisionsBySkuSince :one
SELECT COUNT(*) FROM ozon_price_changes
WHERE seller_cabinet_id = $1
  AND sku = $2
  AND source = 'strategy'
  AND status IN ('pending', 'applied', 'shadow')
  AND created_at >= $3
`

type CountOzonStrategyDecisionsBySkuSinceParams struct {
	SellerCabinetID pgtype.UUID        `json:"seller_cabinet_id"`
	Sku             int64              `json:"sku"`
	Since           pgtype.Timestamptz `json:"since"`
}

// CountOzonStrategyDecisionsBySkuSince feeds the strategy cooldown and daily
// cap. Shadow rows count too: promoting a strategy from dry_run to auto must
// not bypass a cooldown the shadow run just started.
func (q *Queries) CountOzonStrategyDecisionsBySkuSince(ctx context.Context, arg CountOzonStrategyDecisionsBySkuSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOzonStrategyDecisionsBySkuSince, arg.SellerCabinetID, arg.Sku, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOzonPriceChangeByID = `-- name: GetOzonPriceChangeByID :one
SELECT id, seller_cabinet_id, sku, offer_id, old_price_rub, new_price_rub, old_old_price_rub, new_old_price_rub, min_price_rub, floor_rub, reason, source, strategy_id, status, decision_context, error, created_at, applied_at FROM ozon_price_changes WHERE id = $1
`

func (q *Queries) GetOzonPriceChangeByID(ctx context.Context, id pgtype.UUID) (OzonPriceChange, error) {
	row := q.db.QueryRow(ctx, getOzonPriceChangeByID, id)
	var i OzonPriceChange
	err := row.Scan(
		&i.ID,
		&i.SellerCabinetID,
		&i.Sku,
		&i.OfferID,
		&i.OldPriceRub,
		&i.NewPriceRub,
		&i.OldOldPriceRub,
		&i.NewOldPriceRub,
		&i.MinPriceRub,
		&i.FloorRub,
		&i.Reason,
		&i.Source,
		&i.StrategyID,
		&i.Status,
		&i.DecisionContext,
		&i.Error,
		&i.CreatedAt,
		&i.AppliedAt,
	)
	return i, err
}

const getOzonProductPriceBySku = `-- name: GetOzonProductPriceBySku :one
SELECT id, seller_cabinet_id, sku, offer_id, name, price_rub, old_price_rub, min_price_rub, net_price_rub, marketing_seller_price_rub, color_index, commission_fbo_pct, commission_fbs_pct, acquiring_pct, synced_at, ozon_index_min_price_rub, external_index_min_price_rub, self_index_min_price_rub FROM ozon_product_prices
WHERE seller_cabinet_id = $1 AND sku = $2
`

type GetOzonProductPriceBySkuParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Sku             int64       `json:"sku"`
}

func (q *Queries) GetOzonProductPriceBySku(ctx context.Context, arg GetOzonProductPriceBySkuParams) (OzonProductPrice, error) {
	row := q.db.QueryRow(ctx, getOzonProductPriceBySku, arg.SellerCabinetID, arg.Sku)
	var i OzonProductPrice
	err := row.Scan(
		&i.ID,
		&i.SellerCabinetID,
		&i.Sku,
		&i.OfferID,
		&i.Name,
		&i.PriceRub,
		&i.OldPriceRub,
		&i.MinPriceRub,
		&i.NetPriceRub,
		&i.MarketingSellerPriceRub,
		&i.ColorIndex,
		&i.CommissionFboPct,
		&i.CommissionFbsPct,
		&i.AcquiringPct,
		&i.SyncedAt,
		&i.OzonIndexMinPriceRub,
		&i.ExternalIndexMinPriceRub,
		&i.SelfIndexMinPriceRub,
	)
	return i, err
}

const insertOzonPriceChange = `-- name: InsertOzonPriceChange :one

INSERT INTO ozon_price_changes (
    seller_cabinet_id, sku, offer_id, old_price_rub, new_price_rub,
    old_old_price_rub, new_old_price_rub, min_price_rub, floor_rub,
    reason, source, strategy_id, status, decision_context
)
VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7,
    $8, $9,
    $10, $11, $12,
    $13, $14
)
RETURNING id, seller_cabinet_id, sku, offer_id, old_price_rub, new_price_rub, old_old_price_rub, new_old_price_rub, min_price_rub, floor_rub, reason, source, strategy_id, status, decision_context, error, created_at, applied_at
`

type InsertOzonPriceChangeParams struct {
	SellerCabinetID pgtype.UUID    `json:"seller_cabinet_id"`
	Sku             int64          `json:"sku"`
	OfferID         pgtype.Text    `json:"offer_id"`
	OldPriceRub     pgtype.Numeric `json:"old_price_rub"`
	NewPriceRub     pgtype.Numeric `json:"new_price_rub"`
	OldOldPriceRub  pgtype.Numeric `json:"old_old_price_rub"`
	NewOldPriceRub  pgtype.Numeric `json:"new_old_price_rub"`
	MinPriceRub     pgtype.Numeric `json:"min_price_rub"`
	FloorRub        pgtype.Numeric `json:"floor_rub"`
	Reason          pgtype.Text    `json:"reason"`
	Source          string         `json:"source"`
	StrategyID      pgtype.UUID    `json:"strategy_id"`
	Status          string         `json:"status"`
	DecisionContext []byte         `json:"decision_context"`
}

// Ozon module phase 4 queries (repricer: price change audit + guardrails).
func (q *Queries) InsertOzonPriceChange(ctx context.Context, arg InsertOzonPriceChangeParams) (OzonPriceChange, error) {
	row := q.db.QueryRow(ctx, insertOzonPriceChange,
		arg.SellerCabinetID,
		arg.Sku,
		arg.OfferID,
		arg.OldPriceRub,
		arg.NewPriceRub,
		arg.OldOldPriceRub,
		arg.NewOldPriceRub,
		arg.MinPriceRub,
		arg.FloorRub,
		arg.Reason,
		arg.Source,
		arg.StrategyID,
		arg.Status,
		arg.DecisionContext,
	)
	var i OzonPriceChange
	err := row.Scan(
		&i.ID,
		&i.SellerCabinetID,
		&i.Sku,
		&i.OfferID,
		&i.OldPriceRub,
		&i.NewPriceRub,
		&i.OldOldPriceRub,
		&i.NewOldPriceRub,
		&i.MinPriceRub,
		&i.FloorRub,
		&i.Reason,
		&i.Source,
		&i.StrategyID,
		&i.Status,
		&i.DecisionContext,
		&i.Error,
		&i.CreatedAt,
		&i.AppliedAt,
	)
	return i, err
}

const listOzonPriceChangesByCabinet = `-- name: ListOzonPriceChangesByCabinet :many
SELECT id, seller_cabinet_id, sku, offer_id, old_price_rub, new_price_rub, old_old_price_rub, new_old_price_rub, min_price_rub, floor_rub, reason, source, strategy_id, status, decision_context, error, created_at, applied_at FROM ozon_price_changes
WHERE seller_cabinet_id = $1
  AND ($2::bigint IS NULL OR sku = $2::bigint)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListOzonPriceChangesByCabinetParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Sku             pgtype.Int8 `json:"sku"`
	Offset          int32       `json:"offset"`
	Limit           int32       `json:"limit"`
}

func (q *Queries) ListOzonPriceChangesByCabinet(ctx context.Context, arg ListOzonPriceChangesByCabinetParams) ([]OzonPriceChange, error) {
	rows, err := q.db.Query(ctx, listOzonPriceChangesByCabinet,
		arg.SellerCabinetID,
		arg.Sku,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OzonPriceChange{}
	for rows.Next() {
		var i OzonPriceChange
		if err := rows.Scan(
			&i.ID,
			&i.SellerCabinetID,
			&i.Sku,
			&i.OfferID,
			&i.OldPriceRub,
			&i.NewPriceRub,
			&i.OldOldPriceRub,
			&i.NewOldPriceRub,
			&i.MinPriceRub,
			&i.FloorRub,
			&i.Reason,
			&i.Source,
			&i.StrategyID,
			&i.Status,
			&i.DecisionContext,
			&i.Error,
			&i.CreatedAt,
			&i.AppliedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOzonPriceChangeResult = `-- name: MarkOzonPriceChangeResult :exec
UPDATE ozon_price_changes
SET status = $1,
    error = $2,
    applied_at = CASE WHEN $1::text = 'applied' THEN now() ELSE applied_at END
WHERE id = $3
`

type MarkOzonPriceChangeResultParams struct {
	Status string      `json:"status"`
	Error  pgtype.Text `json:"error"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) MarkOzonPriceChangeResult(ctx context.Context, arg MarkOzonPriceChangeResultParams) error {
	_, err := q.db.Exec(ctx, markOzonPriceChangeResult, arg.Status, arg.Error, arg.ID)
	return err
}

const updateOzonProductPriceMirror = `-- name: UpdateOzonProductPriceMirror :exec
UPDATE ozon_product_prices SET
    price_rub = $1,
    old_price_rub = COALESCE($2, old_price_rub),
    min_price_rub = COALESCE($3, min_price_rub)
WHERE seller_cabinet_id = $4 AND sku = $5
`

type UpdateOzonProductPriceMirrorParams struct {
	PriceRub        pgtype.Numeric `json:"price_rub"`
	OldPriceRub     pgtype.Numeric `json:"old_price_rub"`
	MinPriceRub     pgtype.Numeric `json:"min_price_rub"`
	SellerCabinetID pgtype.UUID    `json:"seller_cabinet_id"`
	Sku             int64          `json:"sku"`
}

func (q *Queries) UpdateOzonProductPriceMirror(ctx context.Context, arg UpdateOzonProductPriceMirrorParams) error {
	_, err := q.db.Exec(ctx, updateOzonProductPriceMirror,
		arg.PriceRub,
		arg.OldPriceRub,
		arg.MinPriceRub,
		arg.SellerCabinetID,
		arg.Sku,
	)
	return err
}
