// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ozon_economics.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listOzonProductEconomicsByCabinet = `-- name: ListOzonProductEconomicsByCabinet :many
SELECT id, seller_cabinet_id, offer_id, sku, cost_price_rub, logistics_cost_rub, other_costs_rub, tax_percent, commission_percent, max_allowed_drr, source, synced_at FROM ozon_product_economics
WHERE seller_cabinet_id = $1
ORDER BY offer_id
`

func (q *Queries) ListOzonProductEconomicsByCabinet(ctx context.Context, sellerCabinetID pgtype.UUID) ([]OzonProductEconomic, error) {
	rows, err := q.db.Query(ctx, listOzonProductEconomicsByCabinet, sellerCabinetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OzonProductEconomic{}
	for rows.Next() {
		var i OzonProductEconomic
		if err := rows.Scan(
			&i.ID,
			&i.SellerCabinetID,
			&i.OfferID,
			&i.Sku,
			&i.CostPriceRub,
			&i.LogisticsCostRub,
			&i.OtherCostsRub,
			&i.TaxPercent,
			&i.CommissionPercent,
			&i.MaxAllowedDrr,
			&i.Source,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ozonCabinetMarginInputs = `-- name: OzonCabinetMarginInputs :many
SELECT p.sku,
       p.price_rub,
       p.net_price_rub,
       p.commission_fbo_pct,
       p.commission_fbs_pct,
       p.acquiring_pct,
       COALESCE(s.revenue_rub, 0)::numeric AS revenue_rub
FROM ozon_product_prices p
LEFT JOIN (
    SELECT sd.sku, SUM(sd.revenue_rub) AS revenue_rub
    FROM ozon_sales_daily sd
    WHERE sd.seller_cabinet_id = $1
      AND sd.date >= $2
    GROUP BY sd.sku
) s ON s.sku = p.sku
WHERE p.seller_cabinet_id = $1
`

type OzonCabinetMarginInputsParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Since           pgtype.Date `json:"since"`
}

type OzonCabinetMarginInputsRow struct {
	Sku              int64          `json:"sku"`
	PriceRub         pgtype.Numeric `json:"price_rub"`
	NetPriceRub      pgtype.Numeric `json:"net_price_rub"`
	CommissionFboPct pgtype.Numeric `json:"commission_fbo_pct"`
	CommissionFbsPct pgtype.Numeric `json:"commission_fbs_pct"`
	AcquiringPct     pgtype.Numeric `json:"acquiring_pct"`
	RevenueRub       pgtype.Numeric `json:"revenue_rub"`
}

// OzonCabinetMarginInputs feeds the derived «ДРР от общего оборота» ceiling:
// every priced SKU of the cabinet with the turnover it produced over the
// window. The margin itself is computed in Go so there is exactly one
// implementation of that formula (ozonSKUMarginPct).
//
// SKUs with no sales in the window come back with zero turnover and simply
// carry no weight.
func (q *Queries) OzonCabinetMarginInputs(ctx context.Context, arg OzonCabinetMarginInputsParams) ([]OzonCabinetMarginInputsRow, error) {
	rows, err := q.db.Query(ctx, ozonCabinetMarginInputs, arg.SellerCabinetID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OzonCabinetMarginInputsRow{}
	for rows.Next() {
		var i OzonCabinetMarginInputsRow
		if err := rows.Scan(
			&i.Sku,
			&i.PriceRub,
			&i.NetPriceRub,
			&i.CommissionFboPct,
			&i.CommissionFbsPct,
			&i.AcquiringPct,
			&i.RevenueRub,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOzonProductEconomics = `-- name: UpsertOzonProductEconomics :exec

INSERT INTO ozon_product_economics (
    seller_cabinet_id, offer_id, sku, cost_price_rub, logistics_cost_rub,
    other_costs_rub, tax_percent, commission_percent, max_allowed_drr, source
)
VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7,
    $8, $9,
    $10
)
ON CONFLICT (seller_cabinet_id, offer_id) DO UPDATE SET
    sku = EXCLUDED.sku,
    cost_price_rub = EXCLUDED.cost_price_rub,
    logistics_cost_rub = EXCLUDED.logistics_cost_rub,
    other_costs_rub = EXCLUDED.other_costs_rub,
    tax_percent = EXCLUDED.tax_percent,
    commission_percent = EXCLUDED.commission_percent,
    max_allowed_drr = EXCLUDED.max_allowed_drr,
    source = EXCLUDED.source,
    synced_at = now()
`

type UpsertOzonProductEconomicsParams struct {
	SellerCabinetID   pgtype.UUID    `json:"seller_cabinet_id"`
	OfferID           string         `json:"offer_id"`
	Sku               pgtype.Int8    `json:"sku"`
	CostPriceRub      pgtype.Numeric `json:"cost_price_rub"`
	LogisticsCostRub  pgtype.Numeric `json:"logistics_cost_rub"`
	OtherCostsRub     pgtype.Numeric `json:"other_costs_rub"`
	TaxPercent        pgtype.Numeric `json:"tax_percent"`
	CommissionPercent pgtype.Numeric `json:"commission_percent"`
	MaxAllowedDrr     pgtype.Numeric `json:"max_allowed_drr"`
	Source            pgtype.Text    `json:"source"`
}

// Sellico unit-economics mirror for Ozon cabinets (cost fallback for the
// margin-floor repricer when Ozon does not report net_price).
func (q *Queries) UpsertOzonProductEconomics(ctx context.Context, arg UpsertOzonProductEconomicsParams) error {
	_, err := q.db.Exec(ctx, upsertOzonProductEconomics,
		arg.SellerCabinetID,
		arg.OfferID,
		arg.Sku,
		arg.CostPriceRub,
		arg.LogisticsCostRub,
		arg.OtherCostsRub,
		arg.TaxPercent,
		arg.CommissionPercent,
		arg.MaxAllowedDrr,
		arg.Source,
	)
	return err
}
