// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ozon_cpo_orders.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateOzonCpoOrders = `-- name: AggregateOzonCpoOrders :one
SELECT
    COUNT(DISTINCT o.order_id)::bigint AS orders_count,
    COALESCE(SUM(o.quantity), 0)::bigint AS sold_units,
    COALESCE(SUM(o.sale_price_rub * o.quantity), 0)::numeric AS revenue_rub,
    COALESCE(SUM(o.spend_rub), 0)::numeric AS spend_rub,
    AVG(o.bid_pct)::numeric AS avg_bid_pct
FROM ozon_cpo_orders o
WHERE o.seller_cabinet_id = $1 AND o.date >= $2
`

type AggregateOzonCpoOrdersParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Date            pgtype.Date `json:"date"`
}

type AggregateOzonCpoOrdersRow struct {
	OrdersCount int64          `json:"orders_count"`
	SoldUnits   int64          `json:"sold_units"`
	RevenueRub  pgtype.Numeric `json:"revenue_rub"`
	SpendRub    pgtype.Numeric `json:"spend_rub"`
	AvgBidPct   pgtype.Numeric `json:"avg_bid_pct"`
}

// Window aggregate for the CPO overview, sourced from the promoted-orders
// report (actual orders — unlike ozon_campaign_stats, which carries the
// campaign statistics counters).
func (q *Queries) AggregateOzonCpoOrders(ctx context.Context, arg AggregateOzonCpoOrdersParams) (AggregateOzonCpoOrdersRow, error) {
	row := q.db.QueryRow(ctx, aggregateOzonCpoOrders, arg.SellerCabinetID, arg.Date)
	var i AggregateOzonCpoOrdersRow
	err := row.Scan(
		&i.OrdersCount,
		&i.SoldUnits,
		&i.RevenueRub,
		&i.SpendRub,
		&i.AvgBidPct,
	)
	return i, err
}

const countOzonCpoOrders = `-- name: CountOzonCpoOrders :one
SELECT COUNT(*) FROM ozon_cpo_orders
WHERE seller_cabinet_id = $1 AND date >= $2
`

type CountOzonCpoOrdersParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Date            pgtype.Date `json:"date"`
}

func (q *Queries) CountOzonCpoOrders(ctx context.Context, arg CountOzonCpoOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOzonCpoOrders, arg.SellerCabinetID, arg.Date)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listOzonCpoOrders = `-- name: ListOzonCpoOrders :many
SELECT id, seller_cabinet_id, date, order_id, order_number, sku, adv_sku, vendor_code, name, quantity, price_rub, sale_price_rub, bid_pct, bid_rub, spend_rub, updated_at FROM ozon_cpo_orders
WHERE seller_cabinet_id = $1 AND date >= $2
ORDER BY date DESC, order_id DESC, sku
LIMIT $3 OFFSET $4
`

type ListOzonCpoOrdersParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Date            pgtype.Date `json:"date"`
	Limit           int32       `json:"limit"`
	Offset          int32       `json:"offset"`
}

func (q *Queries) ListOzonCpoOrders(ctx context.Context, arg ListOzonCpoOrdersParams) ([]OzonCpoOrder, error) {
	rows, err := q.db.Query(ctx, listOzonCpoOrders,
		arg.SellerCabinetID,
		arg.Date,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OzonCpoOrder{}
	for rows.Next() {
		var i OzonCpoOrder
		if err := rows.Scan(
			&i.ID,
			&i.SellerCabinetID,
			&i.Date,
			&i.OrderID,
			&i.OrderNumber,
			&i.Sku,
			&i.AdvSku,
			&i.VendorCode,
			&i.Name,
			&i.Quantity,
			&i.PriceRub,
			&i.SalePriceRub,
			&i.BidPct,
			&i.BidRub,
			&i.SpendRub,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOzonCpoOrder = `-- name: UpsertOzonCpoOrder :exec

INSERT INTO ozon_cpo_orders (
    seller_cabinet_id, date, order_id, order_number, sku, adv_sku,
    vendor_code, name, quantity, price_rub, sale_price_rub,
    bid_pct, bid_rub, spend_rub
)
VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11,
    $12, $13, $14
)
ON CONFLICT (seller_cabinet_id, order_id, sku) DO UPDATE SET
    date = EXCLUDED.date,
    order_number = COALESCE(EXCLUDED.order_number, ozon_cpo_orders.order_number),
    adv_sku = COALESCE(EXCLUDED.adv_sku, ozon_cpo_orders.adv_sku),
    vendor_code = COALESCE(EXCLUDED.vendor_code, ozon_cpo_orders.vendor_code),
    name = COALESCE(EXCLUDED.name, ozon_cpo_orders.name),
    quantity = COALESCE(EXCLUDED.quantity, ozon_cpo_orders.quantity),
    price_rub = COALESCE(EXCLUDED.price_rub, ozon_cpo_orders.price_rub),
    sale_price_rub = COALESCE(EXCLUDED.sale_price_rub, ozon_cpo_orders.sale_price_rub),
    bid_pct = COALESCE(EXCLUDED.bid_pct, ozon_cpo_orders.bid_pct),
    bid_rub = COALESCE(EXCLUDED.bid_rub, ozon_cpo_orders.bid_rub),
    spend_rub = COALESCE(EXCLUDED.spend_rub, ozon_cpo_orders.spend_rub),
    updated_at = now()
`

type UpsertOzonCpoOrderParams struct {
	SellerCabinetID pgtype.UUID    `json:"seller_cabinet_id"`
	Date            pgtype.Date    `json:"date"`
	OrderID         string         `json:"order_id"`
	OrderNumber     pgtype.Text    `json:"order_number"`
	Sku             pgtype.Int8    `json:"sku"`
	AdvSku          pgtype.Int8    `json:"adv_sku"`
	VendorCode      pgtype.Text    `json:"vendor_code"`
	Name            pgtype.Text    `json:"name"`
	Quantity        pgtype.Int4    `json:"quantity"`
	PriceRub        pgtype.Numeric `json:"price_rub"`
	SalePriceRub    pgtype.Numeric `json:"sale_price_rub"`
	BidPct          pgtype.Numeric `json:"bid_pct"`
	BidRub          pgtype.Numeric `json:"bid_rub"`
	SpendRub        pgtype.Numeric `json:"spend_rub"`
}

// CPO («Оплата за заказ») promoted orders mirrored from the async
// all_sku_promo orders report (migration 000059).
func (q *Queries) UpsertOzonCpoOrder(ctx context.Context, arg UpsertOzonCpoOrderParams) error {
	_, err := q.db.Exec(ctx, upsertOzonCpoOrder,
		arg.SellerCabinetID,
		arg.Date,
		arg.OrderID,
		arg.OrderNumber,
		arg.Sku,
		arg.AdvSku,
		arg.VendorCode,
		arg.Name,
		arg.Quantity,
		arg.PriceRub,
		arg.SalePriceRub,
		arg.BidPct,
		arg.BidRub,
		arg.SpendRub,
	)
	return err
}
