// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ozon_products.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listOzonProductsByCabinet = `-- name: ListOzonProductsByCabinet :many
SELECT product_id, sku, offer_id, name, primary_image FROM ozon_products
WHERE seller_cabinet_id = $1
`

type ListOzonProductsByCabinetRow struct {
	ProductID    int64       `json:"product_id"`
	Sku          pgtype.Int8 `json:"sku"`
	OfferID      pgtype.Text `json:"offer_id"`
	Name         pgtype.Text `json:"name"`
	PrimaryImage pgtype.Text `json:"primary_image"`
}

// ListOzonProductsByCabinet feeds the price-sync name fill (map by product_id).
func (q *Queries) ListOzonProductsByCabinet(ctx context.Context, sellerCabinetID pgtype.UUID) ([]ListOzonProductsByCabinetRow, error) {
	rows, err := q.db.Query(ctx, listOzonProductsByCabinet, sellerCabinetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOzonProductsByCabinetRow{}
	for rows.Next() {
		var i ListOzonProductsByCabinetRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Sku,
			&i.OfferID,
			&i.Name,
			&i.PrimaryImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOzonProductsBySkus = `-- name: ListOzonProductsBySkus :many
SELECT sku, offer_id, name, primary_image FROM ozon_products
WHERE seller_cabinet_id = $1
  AND sku = ANY($2::bigint[])
`

type ListOzonProductsBySkusParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Skus            []int64     `json:"skus"`
}

type ListOzonProductsBySkusRow struct {
	Sku          pgtype.Int8 `json:"sku"`
	OfferID      pgtype.Text `json:"offer_id"`
	Name         pgtype.Text `json:"name"`
	PrimaryImage pgtype.Text `json:"primary_image"`
}

// ListOzonProductsBySkus feeds batched read enrichment (campaign detail, CPO,
// bid changes) — one query per page, no N+1.
func (q *Queries) ListOzonProductsBySkus(ctx context.Context, arg ListOzonProductsBySkusParams) ([]ListOzonProductsBySkusRow, error) {
	rows, err := q.db.Query(ctx, listOzonProductsBySkus, arg.SellerCabinetID, arg.Skus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOzonProductsBySkusRow{}
	for rows.Next() {
		var i ListOzonProductsBySkusRow
		if err := rows.Scan(
			&i.Sku,
			&i.OfferID,
			&i.Name,
			&i.PrimaryImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOzonProduct = `-- name: UpsertOzonProduct :exec

INSERT INTO ozon_products (seller_cabinet_id, product_id, sku, offer_id, name, primary_image)
VALUES (
    $1, $2, $3,
    $4, $5, $6
)
ON CONFLICT (seller_cabinet_id, product_id) DO UPDATE SET
    sku = COALESCE(EXCLUDED.sku, ozon_products.sku),
    offer_id = COALESCE(EXCLUDED.offer_id, ozon_products.offer_id),
    name = COALESCE(EXCLUDED.name, ozon_products.name),
    primary_image = COALESCE(EXCLUDED.primary_image, ozon_products.primary_image),
    updated_at = now()
`

type UpsertOzonProductParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	ProductID       int64       `json:"product_id"`
	Sku             pgtype.Int8 `json:"sku"`
	OfferID         pgtype.Text `json:"offer_id"`
	Name            pgtype.Text `json:"name"`
	PrimaryImage    pgtype.Text `json:"primary_image"`
}

// Ozon product catalog mapping (product_id ↔ sales SKU + name/offer_id/image).
func (q *Queries) UpsertOzonProduct(ctx context.Context, arg UpsertOzonProductParams) error {
	_, err := q.db.Exec(ctx, upsertOzonProduct,
		arg.SellerCabinetID,
		arg.ProductID,
		arg.Sku,
		arg.OfferID,
		arg.Name,
		arg.PrimaryImage,
	)
	return err
}
