// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ozon_ai.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAIDecisions = `-- name: CountAIDecisions :one
SELECT COUNT(*) FROM ai_decisions
WHERE workspace_id = $1
  AND seller_cabinet_id = $2
  AND ($3::text IS NULL OR status = $3::text)
  AND ($4::uuid IS NULL OR run_id = $4::uuid)
`

type CountAIDecisionsParams struct {
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Status          pgtype.Text `json:"status"`
	RunID           pgtype.UUID `json:"run_id"`
}

func (q *Queries) CountAIDecisions(ctx context.Context, arg CountAIDecisionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAIDecisions,
		arg.WorkspaceID,
		arg.SellerCabinetID,
		arg.Status,
		arg.RunID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAIRunsByCabinet = `-- name: CountAIRunsByCabinet :one
SELECT COUNT(*) FROM ai_runs
WHERE workspace_id = $1
  AND seller_cabinet_id = $2
`

type CountAIRunsByCabinetParams struct {
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
}

func (q *Queries) CountAIRunsByCabinet(ctx context.Context, arg CountAIRunsByCabinetParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAIRunsByCabinet, arg.WorkspaceID, arg.SellerCabinetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finishAIRun = `-- name: FinishAIRun :exec
UPDATE ai_runs SET
    status = $1,
    summary = $2,
    error = $3,
    prompt_tokens = $4,
    completion_tokens = $5,
    finished_at = now()
WHERE id = $6
`

type FinishAIRunParams struct {
	Status           string      `json:"status"`
	Summary          pgtype.Text `json:"summary"`
	Error            pgtype.Text `json:"error"`
	PromptTokens     pgtype.Int4 `json:"prompt_tokens"`
	CompletionTokens pgtype.Int4 `json:"completion_tokens"`
	ID               pgtype.UUID `json:"id"`
}

func (q *Queries) FinishAIRun(ctx context.Context, arg FinishAIRunParams) error {
	_, err := q.db.Exec(ctx, finishAIRun,
		arg.Status,
		arg.Summary,
		arg.Error,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.ID,
	)
	return err
}

const getAIDecisionByID = `-- name: GetAIDecisionByID :one
SELECT id, run_id, workspace_id, seller_cabinet_id, action_type, target, proposal, rationale, expected_effect, guardrail_verdict, status, error, created_at, applied_at, applied_by FROM ai_decisions
WHERE id = $1 AND workspace_id = $2
`

type GetAIDecisionByIDParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetAIDecisionByID(ctx context.Context, arg GetAIDecisionByIDParams) (AiDecision, error) {
	row := q.db.QueryRow(ctx, getAIDecisionByID, arg.ID, arg.WorkspaceID)
	var i AiDecision
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.WorkspaceID,
		&i.SellerCabinetID,
		&i.ActionType,
		&i.Target,
		&i.Proposal,
		&i.Rationale,
		&i.ExpectedEffect,
		&i.GuardrailVerdict,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.AppliedAt,
		&i.AppliedBy,
	)
	return i, err
}

const getAIDecisionGuardState = `-- name: GetAIDecisionGuardState :one
SELECT
    COUNT(*) FILTER (WHERE created_at >= $1)::bigint AS changes_today,
    MAX(created_at)::timestamptz AS last_change_at
FROM ai_decisions
WHERE seller_cabinet_id = $2
  AND action_type = $3
  AND target @> $4::jsonb
  AND status IN ('shadow', 'proposed', 'approved', 'auto_applied', 'applied')
`

type GetAIDecisionGuardStateParams struct {
	DayStart        pgtype.Timestamptz `json:"day_start"`
	SellerCabinetID pgtype.UUID        `json:"seller_cabinet_id"`
	ActionType      string             `json:"action_type"`
	Target          []byte             `json:"target"`
}

type GetAIDecisionGuardStateRow struct {
	ChangesToday int64              `json:"changes_today"`
	LastChangeAt pgtype.Timestamptz `json:"last_change_at"`
}

// GetAIDecisionGuardState feeds the per-target cooldown/daily-cap guardrail
// from the AI side of history (ozon_bid_changes covers the write side).
// Only decisions that were or still may be applied count: shadow rows count
// too — promoting a strategy level must not bypass a cooldown the shadow run
// just started (same rule as the deterministic strategy guard).
func (q *Queries) GetAIDecisionGuardState(ctx context.Context, arg GetAIDecisionGuardStateParams) (GetAIDecisionGuardStateRow, error) {
	row := q.db.QueryRow(ctx, getAIDecisionGuardState,
		arg.DayStart,
		arg.SellerCabinetID,
		arg.ActionType,
		arg.Target,
	)
	var i GetAIDecisionGuardStateRow
	err := row.Scan(&i.ChangesToday, &i.LastChangeAt)
	return i, err
}

const getActiveOzonAIStrategyForCabinet = `-- name: GetActiveOzonAIStrategyForCabinet :one
SELECT id, workspace_id, seller_cabinet_id, name, type, params, is_active, created_at, updated_at FROM strategies
WHERE seller_cabinet_id = $1
  AND type = 'ozon_ai_autopilot'
  AND is_active = TRUE
ORDER BY updated_at DESC
LIMIT 1
`

// GetActiveOzonAIStrategyForCabinet picks the strategy a cabinet run uses.
// Multiple active AI strategies on one cabinet make no sense; the newest wins.
func (q *Queries) GetActiveOzonAIStrategyForCabinet(ctx context.Context, sellerCabinetID pgtype.UUID) (Strategy, error) {
	row := q.db.QueryRow(ctx, getActiveOzonAIStrategyForCabinet, sellerCabinetID)
	var i Strategy
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SellerCabinetID,
		&i.Name,
		&i.Type,
		&i.Params,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOzonAIBidGuardState = `-- name: GetOzonAIBidGuardState :one
SELECT
    COUNT(*) FILTER (WHERE created_at >= $1)::bigint AS changes_today,
    MAX(created_at)::timestamptz AS last_change_at
FROM ozon_bid_changes
WHERE campaign_id = $2
  AND sku = $3
  AND source IN ('strategy', 'ai')
  AND status IN ('pending', 'applied', 'shadow')
`

type GetOzonAIBidGuardStateParams struct {
	DayStart   pgtype.Timestamptz `json:"day_start"`
	CampaignID pgtype.UUID        `json:"campaign_id"`
	Sku        pgtype.Int8        `json:"sku"`
}

type GetOzonAIBidGuardStateRow struct {
	ChangesToday int64              `json:"changes_today"`
	LastChangeAt pgtype.Timestamptz `json:"last_change_at"`
}

// GetOzonAIBidGuardState mirrors GetOzonStrategyGuardState for a single
// (campaign, sku) target, counting both strategy and AI writes so the two
// automation paths share one cooldown budget.
func (q *Queries) GetOzonAIBidGuardState(ctx context.Context, arg GetOzonAIBidGuardStateParams) (GetOzonAIBidGuardStateRow, error) {
	row := q.db.QueryRow(ctx, getOzonAIBidGuardState, arg.DayStart, arg.CampaignID, arg.Sku)
	var i GetOzonAIBidGuardStateRow
	err := row.Scan(&i.ChangesToday, &i.LastChangeAt)
	return i, err
}

const getOzonAICPOGuardState = `-- name: GetOzonAICPOGuardState :one
SELECT
    COUNT(*) FILTER (WHERE created_at >= $1)::bigint AS changes_today,
    MAX(created_at)::timestamptz AS last_change_at
FROM ozon_bid_changes
WHERE seller_cabinet_id = $2
  AND sku = $3
  AND kind = 'cpo'
  AND source IN ('strategy', 'ai')
  AND status IN ('pending', 'applied', 'shadow')
`

type GetOzonAICPOGuardStateParams struct {
	DayStart        pgtype.Timestamptz `json:"day_start"`
	SellerCabinetID pgtype.UUID        `json:"seller_cabinet_id"`
	Sku             pgtype.Int8        `json:"sku"`
}

type GetOzonAICPOGuardStateRow struct {
	ChangesToday int64              `json:"changes_today"`
	LastChangeAt pgtype.Timestamptz `json:"last_change_at"`
}

// GetOzonAICPOGuardState is the CPO flavor (no campaign; cabinet + sku).
func (q *Queries) GetOzonAICPOGuardState(ctx context.Context, arg GetOzonAICPOGuardStateParams) (GetOzonAICPOGuardStateRow, error) {
	row := q.db.QueryRow(ctx, getOzonAICPOGuardState, arg.DayStart, arg.SellerCabinetID, arg.Sku)
	var i GetOzonAICPOGuardStateRow
	err := row.Scan(&i.ChangesToday, &i.LastChangeAt)
	return i, err
}

const getRunningAIRunForCabinet = `-- name: GetRunningAIRunForCabinet :one
SELECT id, workspace_id, seller_cabinet_id, strategy_id, status, trigger, summary, error, prompt_tokens, completion_tokens, started_at, finished_at FROM ai_runs
WHERE seller_cabinet_id = $1
  AND status = 'running'
  AND started_at > now() - INTERVAL '1 hour'
ORDER BY started_at DESC
LIMIT 1
`

// GetRunningAIRunForCabinet powers the 409 on manual runs. Runs older than
// one hour are treated as stale (crashed worker) and no longer block.
func (q *Queries) GetRunningAIRunForCabinet(ctx context.Context, sellerCabinetID pgtype.UUID) (AiRun, error) {
	row := q.db.QueryRow(ctx, getRunningAIRunForCabinet, sellerCabinetID)
	var i AiRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SellerCabinetID,
		&i.StrategyID,
		&i.Status,
		&i.Trigger,
		&i.Summary,
		&i.Error,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertAIDecision = `-- name: InsertAIDecision :one
INSERT INTO ai_decisions (
    run_id, workspace_id, seller_cabinet_id, action_type, target, proposal,
    rationale, expected_effect, guardrail_verdict, status, error
)
VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8,
    $9, $10, $11
)
RETURNING id, run_id, workspace_id, seller_cabinet_id, action_type, target, proposal, rationale, expected_effect, guardrail_verdict, status, error, created_at, applied_at, applied_by
`

type InsertAIDecisionParams struct {
	RunID            pgtype.UUID `json:"run_id"`
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	SellerCabinetID  pgtype.UUID `json:"seller_cabinet_id"`
	ActionType       string      `json:"action_type"`
	Target           []byte      `json:"target"`
	Proposal         []byte      `json:"proposal"`
	Rationale        pgtype.Text `json:"rationale"`
	ExpectedEffect   pgtype.Text `json:"expected_effect"`
	GuardrailVerdict string      `json:"guardrail_verdict"`
	Status           string      `json:"status"`
	Error            pgtype.Text `json:"error"`
}

func (q *Queries) InsertAIDecision(ctx context.Context, arg InsertAIDecisionParams) (AiDecision, error) {
	row := q.db.QueryRow(ctx, insertAIDecision,
		arg.RunID,
		arg.WorkspaceID,
		arg.SellerCabinetID,
		arg.ActionType,
		arg.Target,
		arg.Proposal,
		arg.Rationale,
		arg.ExpectedEffect,
		arg.GuardrailVerdict,
		arg.Status,
		arg.Error,
	)
	var i AiDecision
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.WorkspaceID,
		&i.SellerCabinetID,
		&i.ActionType,
		&i.Target,
		&i.Proposal,
		&i.Rationale,
		&i.ExpectedEffect,
		&i.GuardrailVerdict,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.AppliedAt,
		&i.AppliedBy,
	)
	return i, err
}

const insertAIRun = `-- name: InsertAIRun :one

INSERT INTO ai_runs (workspace_id, seller_cabinet_id, strategy_id, status, trigger)
VALUES (
    $1, $2,
    $3, $4, $5
)
RETURNING id, workspace_id, seller_cabinet_id, strategy_id, status, trigger, summary, error, prompt_tokens, completion_tokens, started_at, finished_at
`

type InsertAIRunParams struct {
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	StrategyID      pgtype.UUID `json:"strategy_id"`
	Status          string      `json:"status"`
	Trigger         string      `json:"trigger"`
}

// Ozon module phase 3 queries (AI autopilot: runs, decisions, context pack).
func (q *Queries) InsertAIRun(ctx context.Context, arg InsertAIRunParams) (AiRun, error) {
	row := q.db.QueryRow(ctx, insertAIRun,
		arg.WorkspaceID,
		arg.SellerCabinetID,
		arg.StrategyID,
		arg.Status,
		arg.Trigger,
	)
	var i AiRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SellerCabinetID,
		&i.StrategyID,
		&i.Status,
		&i.Trigger,
		&i.Summary,
		&i.Error,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listAIDecisions = `-- name: ListAIDecisions :many
SELECT id, run_id, workspace_id, seller_cabinet_id, action_type, target, proposal, rationale, expected_effect, guardrail_verdict, status, error, created_at, applied_at, applied_by FROM ai_decisions
WHERE workspace_id = $1
  AND seller_cabinet_id = $2
  AND ($3::text IS NULL OR status = $3::text)
  AND ($4::uuid IS NULL OR run_id = $4::uuid)
ORDER BY created_at DESC
LIMIT $6 OFFSET $5
`

type ListAIDecisionsParams struct {
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Status          pgtype.Text `json:"status"`
	RunID           pgtype.UUID `json:"run_id"`
	Offset          int32       `json:"offset"`
	Limit           int32       `json:"limit"`
}

func (q *Queries) ListAIDecisions(ctx context.Context, arg ListAIDecisionsParams) ([]AiDecision, error) {
	rows, err := q.db.Query(ctx, listAIDecisions,
		arg.WorkspaceID,
		arg.SellerCabinetID,
		arg.Status,
		arg.RunID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiDecision{}
	for rows.Next() {
		var i AiDecision
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.WorkspaceID,
			&i.SellerCabinetID,
			&i.ActionType,
			&i.Target,
			&i.Proposal,
			&i.Rationale,
			&i.ExpectedEffect,
			&i.GuardrailVerdict,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.AppliedAt,
			&i.AppliedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIRunsByCabinet = `-- name: ListAIRunsByCabinet :many
SELECT id, workspace_id, seller_cabinet_id, strategy_id, status, trigger, summary, error, prompt_tokens, completion_tokens, started_at, finished_at FROM ai_runs
WHERE workspace_id = $1
  AND seller_cabinet_id = $2
ORDER BY started_at DESC
LIMIT $4 OFFSET $3
`

type ListAIRunsByCabinetParams struct {
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Offset          int32       `json:"offset"`
	Limit           int32       `json:"limit"`
}

func (q *Queries) ListAIRunsByCabinet(ctx context.Context, arg ListAIRunsByCabinetParams) ([]AiRun, error) {
	rows, err := q.db.Query(ctx, listAIRunsByCabinet,
		arg.WorkspaceID,
		arg.SellerCabinetID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiRun{}
	for rows.Next() {
		var i AiRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SellerCabinetID,
			&i.StrategyID,
			&i.Status,
			&i.Trigger,
			&i.Summary,
			&i.Error,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveOzonAICabinets = `-- name: ListActiveOzonAICabinets :many
SELECT DISTINCT s.seller_cabinet_id
FROM strategies s
JOIN seller_cabinets sc ON sc.id = s.seller_cabinet_id
WHERE s.type = 'ozon_ai_autopilot'
  AND s.is_active = TRUE
  AND sc.marketplace = 'ozon'
  AND sc.deleted_at IS NULL
`

// ListActiveOzonAICabinets enumerates cabinets the ozon:ai_sweep fans out to:
// every active Ozon cabinet that has at least one active ozon_ai_autopilot
// strategy.
func (q *Queries) ListActiveOzonAICabinets(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveOzonAICabinets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var seller_cabinet_id pgtype.UUID
		if err := rows.Scan(&seller_cabinet_id); err != nil {
			return nil, err
		}
		items = append(items, seller_cabinet_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOzonCampaignDailyStatsSince = `-- name: ListOzonCampaignDailyStatsSince :many
SELECT s.campaign_id, s.date, s.views, s.clicks, s.spend_rub, s.orders, s.revenue_rub
FROM ozon_campaign_stats s
JOIN ozon_campaigns c ON c.id = s.campaign_id
WHERE c.seller_cabinet_id = $1 AND s.date >= $2
ORDER BY s.campaign_id, s.date
`

type ListOzonCampaignDailyStatsSinceParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Date            pgtype.Date `json:"date"`
}

type ListOzonCampaignDailyStatsSinceRow struct {
	CampaignID pgtype.UUID    `json:"campaign_id"`
	Date       pgtype.Date    `json:"date"`
	Views      int64          `json:"views"`
	Clicks     int64          `json:"clicks"`
	SpendRub   pgtype.Numeric `json:"spend_rub"`
	Orders     int64          `json:"orders"`
	RevenueRub pgtype.Numeric `json:"revenue_rub"`
}

// ListOzonCampaignDailyStatsSince returns per-campaign daily rows for the
// context pack (14-day window), keyed by the local campaign UUID.
func (q *Queries) ListOzonCampaignDailyStatsSince(ctx context.Context, arg ListOzonCampaignDailyStatsSinceParams) ([]ListOzonCampaignDailyStatsSinceRow, error) {
	rows, err := q.db.Query(ctx, listOzonCampaignDailyStatsSince, arg.SellerCabinetID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOzonCampaignDailyStatsSinceRow{}
	for rows.Next() {
		var i ListOzonCampaignDailyStatsSinceRow
		if err := rows.Scan(
			&i.CampaignID,
			&i.Date,
			&i.Views,
			&i.Clicks,
			&i.SpendRub,
			&i.Orders,
			&i.RevenueRub,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOzonProductPricesBySkus = `-- name: ListOzonProductPricesBySkus :many
SELECT id, seller_cabinet_id, sku, offer_id, name, price_rub, old_price_rub, min_price_rub, net_price_rub, marketing_seller_price_rub, color_index, commission_fbo_pct, commission_fbs_pct, acquiring_pct, synced_at FROM ozon_product_prices
WHERE seller_cabinet_id = $1
  AND sku = ANY($2::bigint[])
`

type ListOzonProductPricesBySkusParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Skus            []int64     `json:"skus"`
}

func (q *Queries) ListOzonProductPricesBySkus(ctx context.Context, arg ListOzonProductPricesBySkusParams) ([]OzonProductPrice, error) {
	rows, err := q.db.Query(ctx, listOzonProductPricesBySkus, arg.SellerCabinetID, arg.Skus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OzonProductPrice{}
	for rows.Next() {
		var i OzonProductPrice
		if err := rows.Scan(
			&i.ID,
			&i.SellerCabinetID,
			&i.Sku,
			&i.OfferID,
			&i.Name,
			&i.PriceRub,
			&i.OldPriceRub,
			&i.MinPriceRub,
			&i.NetPriceRub,
			&i.MarketingSellerPriceRub,
			&i.ColorIndex,
			&i.CommissionFboPct,
			&i.CommissionFbsPct,
			&i.AcquiringPct,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAIDecisionStatus = `-- name: SetAIDecisionStatus :exec
UPDATE ai_decisions SET
    status = $1,
    error = $2,
    applied_at = CASE WHEN $1::text IN ('applied', 'auto_applied')
                      THEN now() ELSE applied_at END,
    applied_by = COALESCE($3, applied_by)
WHERE id = $4
`

type SetAIDecisionStatusParams struct {
	Status    string      `json:"status"`
	Error     pgtype.Text `json:"error"`
	AppliedBy pgtype.UUID `json:"applied_by"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) SetAIDecisionStatus(ctx context.Context, arg SetAIDecisionStatusParams) error {
	_, err := q.db.Exec(ctx, setAIDecisionStatus,
		arg.Status,
		arg.Error,
		arg.AppliedBy,
		arg.ID,
	)
	return err
}
