// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ozon_inventory.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listOzonProductStocksByCabinet = `-- name: ListOzonProductStocksByCabinet :many
SELECT id, seller_cabinet_id, sku, offer_id, present, reserved, synced_at FROM ozon_product_stocks WHERE seller_cabinet_id = $1
`

func (q *Queries) ListOzonProductStocksByCabinet(ctx context.Context, sellerCabinetID pgtype.UUID) ([]OzonProductStock, error) {
	rows, err := q.db.Query(ctx, listOzonProductStocksByCabinet, sellerCabinetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OzonProductStock{}
	for rows.Next() {
		var i OzonProductStock
		if err := rows.Scan(
			&i.ID,
			&i.SellerCabinetID,
			&i.Sku,
			&i.OfferID,
			&i.Present,
			&i.Reserved,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ozonSalesVelocityByCabinet = `-- name: OzonSalesVelocityByCabinet :many
SELECT sku,
       COALESCE(SUM(ordered_units), 0)::bigint  AS units,
       COALESCE(SUM(revenue_rub), 0)::numeric   AS revenue_rub
FROM ozon_sales_daily
WHERE seller_cabinet_id = $1 AND date >= $2
GROUP BY sku
`

type OzonSalesVelocityByCabinetParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Date            pgtype.Date `json:"date"`
}

type OzonSalesVelocityByCabinetRow struct {
	Sku        int64          `json:"sku"`
	Units      int64          `json:"units"`
	RevenueRub pgtype.Numeric `json:"revenue_rub"`
}

// OzonSalesVelocityByCabinet sums ordered units and revenue per sales SKU
// over a lookback window; the caller divides by the window length to get
// units/day.
func (q *Queries) OzonSalesVelocityByCabinet(ctx context.Context, arg OzonSalesVelocityByCabinetParams) ([]OzonSalesVelocityByCabinetRow, error) {
	rows, err := q.db.Query(ctx, ozonSalesVelocityByCabinet, arg.SellerCabinetID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OzonSalesVelocityByCabinetRow{}
	for rows.Next() {
		var i OzonSalesVelocityByCabinetRow
		if err := rows.Scan(&i.Sku, &i.Units, &i.RevenueRub); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ozonSkuAdSpendByCabinet = `-- name: OzonSkuAdSpendByCabinet :many
SELECT cp.sku,
       COALESCE(SUM(s.spend_rub), 0)::numeric   AS spend_rub,
       COALESCE(SUM(s.revenue_rub), 0)::numeric AS revenue_rub
FROM ozon_campaign_products cp
JOIN ozon_campaigns c ON c.id = cp.campaign_id
JOIN ozon_campaign_stats s ON s.campaign_id = c.id
WHERE c.seller_cabinet_id = $1 AND s.date >= $2
GROUP BY cp.sku
`

type OzonSkuAdSpendByCabinetParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Date            pgtype.Date `json:"date"`
}

type OzonSkuAdSpendByCabinetRow struct {
	Sku        int64          `json:"sku"`
	SpendRub   pgtype.Numeric `json:"spend_rub"`
	RevenueRub pgtype.Numeric `json:"revenue_rub"`
}

// OzonSkuAdSpendByCabinet attributes campaign-level spend/revenue to every
// SKU of the campaign (ozon_campaign_stats has no per-SKU split): a SKU in
// several campaigns aggregates across them, so its ДРР is the blended
// campaign ДРР of its placements. sku here is the SALES sku.
func (q *Queries) OzonSkuAdSpendByCabinet(ctx context.Context, arg OzonSkuAdSpendByCabinetParams) ([]OzonSkuAdSpendByCabinetRow, error) {
	rows, err := q.db.Query(ctx, ozonSkuAdSpendByCabinet, arg.SellerCabinetID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OzonSkuAdSpendByCabinetRow{}
	for rows.Next() {
		var i OzonSkuAdSpendByCabinetRow
		if err := rows.Scan(&i.Sku, &i.SpendRub, &i.RevenueRub); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOzonProductStock = `-- name: UpsertOzonProductStock :exec

INSERT INTO ozon_product_stocks (seller_cabinet_id, sku, offer_id, present, reserved, synced_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (seller_cabinet_id, sku) DO UPDATE SET
    offer_id = EXCLUDED.offer_id,
    present = EXCLUDED.present,
    reserved = EXCLUDED.reserved,
    synced_at = now()
`

type UpsertOzonProductStockParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Sku             int64       `json:"sku"`
	OfferID         pgtype.Text `json:"offer_id"`
	Present         int32       `json:"present"`
	Reserved        int32       `json:"reserved"`
}

// Ozon module phase 5 queries (stocks + daily sales + per-SKU ad spend for
// the inventory-demand and ad-linked repricer strategies).
func (q *Queries) UpsertOzonProductStock(ctx context.Context, arg UpsertOzonProductStockParams) error {
	_, err := q.db.Exec(ctx, upsertOzonProductStock,
		arg.SellerCabinetID,
		arg.Sku,
		arg.OfferID,
		arg.Present,
		arg.Reserved,
	)
	return err
}

const upsertOzonSalesDaily = `-- name: UpsertOzonSalesDaily :exec
INSERT INTO ozon_sales_daily (seller_cabinet_id, sku, date, ordered_units, revenue_rub)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (seller_cabinet_id, sku, date) DO UPDATE SET
    ordered_units = EXCLUDED.ordered_units,
    revenue_rub = EXCLUDED.revenue_rub
`

type UpsertOzonSalesDailyParams struct {
	SellerCabinetID pgtype.UUID    `json:"seller_cabinet_id"`
	Sku             int64          `json:"sku"`
	Date            pgtype.Date    `json:"date"`
	OrderedUnits    int32          `json:"ordered_units"`
	RevenueRub      pgtype.Numeric `json:"revenue_rub"`
}

func (q *Queries) UpsertOzonSalesDaily(ctx context.Context, arg UpsertOzonSalesDailyParams) error {
	_, err := q.db.Exec(ctx, upsertOzonSalesDaily,
		arg.SellerCabinetID,
		arg.Sku,
		arg.Date,
		arg.OrderedUnits,
		arg.RevenueRub,
	)
	return err
}
