// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ozon.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateOzonCampaignStatsByCabinet = `-- name: AggregateOzonCampaignStatsByCabinet :many
SELECT
    s.campaign_id,
    COALESCE(SUM(s.views), 0)::bigint AS views,
    COALESCE(SUM(s.clicks), 0)::bigint AS clicks,
    COALESCE(SUM(s.spend_rub), 0)::numeric AS spend_rub,
    COALESCE(SUM(s.orders), 0)::bigint AS orders,
    COALESCE(SUM(s.revenue_rub), 0)::numeric AS revenue_rub
FROM ozon_campaign_stats s
JOIN ozon_campaigns c ON c.id = s.campaign_id
WHERE c.seller_cabinet_id = $1 AND s.date >= $2
GROUP BY s.campaign_id
`

type AggregateOzonCampaignStatsByCabinetParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Date            pgtype.Date `json:"date"`
}

type AggregateOzonCampaignStatsByCabinetRow struct {
	CampaignID pgtype.UUID    `json:"campaign_id"`
	Views      int64          `json:"views"`
	Clicks     int64          `json:"clicks"`
	SpendRub   pgtype.Numeric `json:"spend_rub"`
	Orders     int64          `json:"orders"`
	RevenueRub pgtype.Numeric `json:"revenue_rub"`
}

func (q *Queries) AggregateOzonCampaignStatsByCabinet(ctx context.Context, arg AggregateOzonCampaignStatsByCabinetParams) ([]AggregateOzonCampaignStatsByCabinetRow, error) {
	rows, err := q.db.Query(ctx, aggregateOzonCampaignStatsByCabinet, arg.SellerCabinetID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateOzonCampaignStatsByCabinetRow{}
	for rows.Next() {
		var i AggregateOzonCampaignStatsByCabinetRow
		if err := rows.Scan(
			&i.CampaignID,
			&i.Views,
			&i.Clicks,
			&i.SpendRub,
			&i.Orders,
			&i.RevenueRub,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOzonCampaignsByCabinet = `-- name: CountOzonCampaignsByCabinet :one
SELECT COUNT(*) FROM ozon_campaigns WHERE seller_cabinet_id = $1
`

func (q *Queries) CountOzonCampaignsByCabinet(ctx context.Context, sellerCabinetID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOzonCampaignsByCabinet, sellerCabinetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOzonProductPrices = `-- name: CountOzonProductPrices :one
SELECT COUNT(*) FROM ozon_product_prices
WHERE seller_cabinet_id = $1
  AND (
    $2::text IS NULL
    OR name ILIKE '%' || $2::text || '%'
    OR offer_id ILIKE '%' || $2::text || '%'
    OR sku::text = $2::text
  )
`

type CountOzonProductPricesParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Search          pgtype.Text `json:"search"`
}

func (q *Queries) CountOzonProductPrices(ctx context.Context, arg CountOzonProductPricesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOzonProductPrices, arg.SellerCabinetID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOzonCampaignByID = `-- name: GetOzonCampaignByID :one
SELECT id, seller_cabinet_id, ozon_campaign_id, title, adv_object_type, state, placement, autopilot_strategy, daily_budget_rub, weekly_budget_rub, from_date, to_date, created_at, updated_at FROM ozon_campaigns WHERE id = $1
`

func (q *Queries) GetOzonCampaignByID(ctx context.Context, id pgtype.UUID) (OzonCampaign, error) {
	row := q.db.QueryRow(ctx, getOzonCampaignByID, id)
	var i OzonCampaign
	err := row.Scan(
		&i.ID,
		&i.SellerCabinetID,
		&i.OzonCampaignID,
		&i.Title,
		&i.AdvObjectType,
		&i.State,
		&i.Placement,
		&i.AutopilotStrategy,
		&i.DailyBudgetRub,
		&i.WeeklyBudgetRub,
		&i.FromDate,
		&i.ToDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOzonSyncState = `-- name: GetOzonSyncState :one
SELECT seller_cabinet_id, campaigns_synced_at, stats_synced_at, prices_synced_at, last_error, updated_at FROM ozon_sync_states WHERE seller_cabinet_id = $1
`

func (q *Queries) GetOzonSyncState(ctx context.Context, sellerCabinetID pgtype.UUID) (OzonSyncState, error) {
	row := q.db.QueryRow(ctx, getOzonSyncState, sellerCabinetID)
	var i OzonSyncState
	err := row.Scan(
		&i.SellerCabinetID,
		&i.CampaignsSyncedAt,
		&i.StatsSyncedAt,
		&i.PricesSyncedAt,
		&i.LastError,
		&i.UpdatedAt,
	)
	return i, err
}

const listOzonCampaignProducts = `-- name: ListOzonCampaignProducts :many
SELECT id, campaign_id, sku, bid_rub, target_cir, top_position, is_active, updated_at FROM ozon_campaign_products
WHERE campaign_id = $1
ORDER BY sku
`

func (q *Queries) ListOzonCampaignProducts(ctx context.Context, campaignID pgtype.UUID) ([]OzonCampaignProduct, error) {
	rows, err := q.db.Query(ctx, listOzonCampaignProducts, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OzonCampaignProduct{}
	for rows.Next() {
		var i OzonCampaignProduct
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Sku,
			&i.BidRub,
			&i.TargetCir,
			&i.TopPosition,
			&i.IsActive,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOzonCampaignRefsByCabinet = `-- name: ListOzonCampaignRefsByCabinet :many
SELECT id, ozon_campaign_id FROM ozon_campaigns
WHERE seller_cabinet_id = $1
`

type ListOzonCampaignRefsByCabinetRow struct {
	ID             pgtype.UUID `json:"id"`
	OzonCampaignID int64       `json:"ozon_campaign_id"`
}

func (q *Queries) ListOzonCampaignRefsByCabinet(ctx context.Context, sellerCabinetID pgtype.UUID) ([]ListOzonCampaignRefsByCabinetRow, error) {
	rows, err := q.db.Query(ctx, listOzonCampaignRefsByCabinet, sellerCabinetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOzonCampaignRefsByCabinetRow{}
	for rows.Next() {
		var i ListOzonCampaignRefsByCabinetRow
		if err := rows.Scan(&i.ID, &i.OzonCampaignID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOzonCampaignStats = `-- name: ListOzonCampaignStats :many
SELECT id, campaign_id, date, views, clicks, spend_rub, orders, revenue_rub FROM ozon_campaign_stats
WHERE campaign_id = $1 AND date BETWEEN $2 AND $3
ORDER BY date
`

type ListOzonCampaignStatsParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	Date       pgtype.Date `json:"date"`
	Date_2     pgtype.Date `json:"date_2"`
}

func (q *Queries) ListOzonCampaignStats(ctx context.Context, arg ListOzonCampaignStatsParams) ([]OzonCampaignStat, error) {
	rows, err := q.db.Query(ctx, listOzonCampaignStats, arg.CampaignID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OzonCampaignStat{}
	for rows.Next() {
		var i OzonCampaignStat
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Date,
			&i.Views,
			&i.Clicks,
			&i.SpendRub,
			&i.Orders,
			&i.RevenueRub,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOzonCampaignsByCabinet = `-- name: ListOzonCampaignsByCabinet :many
SELECT id, seller_cabinet_id, ozon_campaign_id, title, adv_object_type, state, placement, autopilot_strategy, daily_budget_rub, weekly_budget_rub, from_date, to_date, created_at, updated_at FROM ozon_campaigns
WHERE seller_cabinet_id = $1
ORDER BY ozon_campaign_id DESC
LIMIT $2 OFFSET $3
`

type ListOzonCampaignsByCabinetParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Limit           int32       `json:"limit"`
	Offset          int32       `json:"offset"`
}

func (q *Queries) ListOzonCampaignsByCabinet(ctx context.Context, arg ListOzonCampaignsByCabinetParams) ([]OzonCampaign, error) {
	rows, err := q.db.Query(ctx, listOzonCampaignsByCabinet, arg.SellerCabinetID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OzonCampaign{}
	for rows.Next() {
		var i OzonCampaign
		if err := rows.Scan(
			&i.ID,
			&i.SellerCabinetID,
			&i.OzonCampaignID,
			&i.Title,
			&i.AdvObjectType,
			&i.State,
			&i.Placement,
			&i.AutopilotStrategy,
			&i.DailyBudgetRub,
			&i.WeeklyBudgetRub,
			&i.FromDate,
			&i.ToDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOzonProductPrices = `-- name: ListOzonProductPrices :many
SELECT id, seller_cabinet_id, sku, offer_id, name, price_rub, old_price_rub, min_price_rub, net_price_rub, marketing_seller_price_rub, color_index, commission_fbo_pct, commission_fbs_pct, acquiring_pct, synced_at FROM ozon_product_prices
WHERE seller_cabinet_id = $1
  AND (
    $4::text IS NULL
    OR name ILIKE '%' || $4::text || '%'
    OR offer_id ILIKE '%' || $4::text || '%'
    OR sku::text = $4::text
  )
ORDER BY offer_id, sku
LIMIT $2 OFFSET $3
`

type ListOzonProductPricesParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Limit           int32       `json:"limit"`
	Offset          int32       `json:"offset"`
	Search          pgtype.Text `json:"search"`
}

func (q *Queries) ListOzonProductPrices(ctx context.Context, arg ListOzonProductPricesParams) ([]OzonProductPrice, error) {
	rows, err := q.db.Query(ctx, listOzonProductPrices,
		arg.SellerCabinetID,
		arg.Limit,
		arg.Offset,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OzonProductPrice{}
	for rows.Next() {
		var i OzonProductPrice
		if err := rows.Scan(
			&i.ID,
			&i.SellerCabinetID,
			&i.Sku,
			&i.OfferID,
			&i.Name,
			&i.PriceRub,
			&i.OldPriceRub,
			&i.MinPriceRub,
			&i.NetPriceRub,
			&i.MarketingSellerPriceRub,
			&i.ColorIndex,
			&i.CommissionFboPct,
			&i.CommissionFbsPct,
			&i.AcquiringPct,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchOzonSyncState = `-- name: TouchOzonSyncState :exec
INSERT INTO ozon_sync_states (
    seller_cabinet_id, campaigns_synced_at, stats_synced_at, prices_synced_at, last_error, updated_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    now()
)
ON CONFLICT (seller_cabinet_id) DO UPDATE SET
    campaigns_synced_at = COALESCE(EXCLUDED.campaigns_synced_at, ozon_sync_states.campaigns_synced_at),
    stats_synced_at = COALESCE(EXCLUDED.stats_synced_at, ozon_sync_states.stats_synced_at),
    prices_synced_at = COALESCE(EXCLUDED.prices_synced_at, ozon_sync_states.prices_synced_at),
    last_error = EXCLUDED.last_error,
    updated_at = now()
`

type TouchOzonSyncStateParams struct {
	SellerCabinetID   pgtype.UUID        `json:"seller_cabinet_id"`
	CampaignsSyncedAt pgtype.Timestamptz `json:"campaigns_synced_at"`
	StatsSyncedAt     pgtype.Timestamptz `json:"stats_synced_at"`
	PricesSyncedAt    pgtype.Timestamptz `json:"prices_synced_at"`
	LastError         pgtype.Text        `json:"last_error"`
}

func (q *Queries) TouchOzonSyncState(ctx context.Context, arg TouchOzonSyncStateParams) error {
	_, err := q.db.Exec(ctx, touchOzonSyncState,
		arg.SellerCabinetID,
		arg.CampaignsSyncedAt,
		arg.StatsSyncedAt,
		arg.PricesSyncedAt,
		arg.LastError,
	)
	return err
}

const upsertOzonCampaign = `-- name: UpsertOzonCampaign :one

INSERT INTO ozon_campaigns (
    seller_cabinet_id, ozon_campaign_id, title, adv_object_type, state,
    placement, autopilot_strategy, daily_budget_rub, weekly_budget_rub,
    from_date, to_date
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (seller_cabinet_id, ozon_campaign_id) DO UPDATE SET
    title = EXCLUDED.title,
    adv_object_type = EXCLUDED.adv_object_type,
    state = EXCLUDED.state,
    placement = EXCLUDED.placement,
    autopilot_strategy = EXCLUDED.autopilot_strategy,
    daily_budget_rub = EXCLUDED.daily_budget_rub,
    weekly_budget_rub = EXCLUDED.weekly_budget_rub,
    from_date = EXCLUDED.from_date,
    to_date = EXCLUDED.to_date,
    updated_at = now()
RETURNING id, seller_cabinet_id, ozon_campaign_id, title, adv_object_type, state, placement, autopilot_strategy, daily_budget_rub, weekly_budget_rub, from_date, to_date, created_at, updated_at
`

type UpsertOzonCampaignParams struct {
	SellerCabinetID   pgtype.UUID `json:"seller_cabinet_id"`
	OzonCampaignID    int64       `json:"ozon_campaign_id"`
	Title             pgtype.Text `json:"title"`
	AdvObjectType     pgtype.Text `json:"adv_object_type"`
	State             pgtype.Text `json:"state"`
	Placement         pgtype.Text `json:"placement"`
	AutopilotStrategy pgtype.Text `json:"autopilot_strategy"`
	DailyBudgetRub    pgtype.Int8 `json:"daily_budget_rub"`
	WeeklyBudgetRub   pgtype.Int8 `json:"weekly_budget_rub"`
	FromDate          pgtype.Date `json:"from_date"`
	ToDate            pgtype.Date `json:"to_date"`
}

// Ozon module phase 1 queries (campaigns, products, stats, prices, sync state).
func (q *Queries) UpsertOzonCampaign(ctx context.Context, arg UpsertOzonCampaignParams) (OzonCampaign, error) {
	row := q.db.QueryRow(ctx, upsertOzonCampaign,
		arg.SellerCabinetID,
		arg.OzonCampaignID,
		arg.Title,
		arg.AdvObjectType,
		arg.State,
		arg.Placement,
		arg.AutopilotStrategy,
		arg.DailyBudgetRub,
		arg.WeeklyBudgetRub,
		arg.FromDate,
		arg.ToDate,
	)
	var i OzonCampaign
	err := row.Scan(
		&i.ID,
		&i.SellerCabinetID,
		&i.OzonCampaignID,
		&i.Title,
		&i.AdvObjectType,
		&i.State,
		&i.Placement,
		&i.AutopilotStrategy,
		&i.DailyBudgetRub,
		&i.WeeklyBudgetRub,
		&i.FromDate,
		&i.ToDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOzonCampaignProduct = `-- name: UpsertOzonCampaignProduct :exec
INSERT INTO ozon_campaign_products (campaign_id, sku, bid_rub, target_cir, top_position, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (campaign_id, sku) DO UPDATE SET
    bid_rub = EXCLUDED.bid_rub,
    target_cir = EXCLUDED.target_cir,
    top_position = EXCLUDED.top_position,
    is_active = EXCLUDED.is_active,
    updated_at = now()
`

type UpsertOzonCampaignProductParams struct {
	CampaignID  pgtype.UUID    `json:"campaign_id"`
	Sku         int64          `json:"sku"`
	BidRub      pgtype.Numeric `json:"bid_rub"`
	TargetCir   pgtype.Numeric `json:"target_cir"`
	TopPosition pgtype.Int4    `json:"top_position"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) UpsertOzonCampaignProduct(ctx context.Context, arg UpsertOzonCampaignProductParams) error {
	_, err := q.db.Exec(ctx, upsertOzonCampaignProduct,
		arg.CampaignID,
		arg.Sku,
		arg.BidRub,
		arg.TargetCir,
		arg.TopPosition,
		arg.IsActive,
	)
	return err
}

const upsertOzonCampaignStat = `-- name: UpsertOzonCampaignStat :exec
INSERT INTO ozon_campaign_stats (campaign_id, date, views, clicks, spend_rub, orders, revenue_rub)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (campaign_id, date) DO UPDATE SET
    views = EXCLUDED.views,
    clicks = EXCLUDED.clicks,
    spend_rub = EXCLUDED.spend_rub,
    orders = EXCLUDED.orders,
    revenue_rub = EXCLUDED.revenue_rub
`

type UpsertOzonCampaignStatParams struct {
	CampaignID pgtype.UUID    `json:"campaign_id"`
	Date       pgtype.Date    `json:"date"`
	Views      int64          `json:"views"`
	Clicks     int64          `json:"clicks"`
	SpendRub   pgtype.Numeric `json:"spend_rub"`
	Orders     int64          `json:"orders"`
	RevenueRub pgtype.Numeric `json:"revenue_rub"`
}

func (q *Queries) UpsertOzonCampaignStat(ctx context.Context, arg UpsertOzonCampaignStatParams) error {
	_, err := q.db.Exec(ctx, upsertOzonCampaignStat,
		arg.CampaignID,
		arg.Date,
		arg.Views,
		arg.Clicks,
		arg.SpendRub,
		arg.Orders,
		arg.RevenueRub,
	)
	return err
}

const upsertOzonProductPrice = `-- name: UpsertOzonProductPrice :exec
INSERT INTO ozon_product_prices (
    seller_cabinet_id, sku, offer_id, name, price_rub, old_price_rub,
    min_price_rub, net_price_rub, marketing_seller_price_rub, color_index,
    commission_fbo_pct, commission_fbs_pct, acquiring_pct, synced_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, now())
ON CONFLICT (seller_cabinet_id, sku) DO UPDATE SET
    offer_id = EXCLUDED.offer_id,
    name = COALESCE(EXCLUDED.name, ozon_product_prices.name),
    price_rub = EXCLUDED.price_rub,
    old_price_rub = EXCLUDED.old_price_rub,
    min_price_rub = EXCLUDED.min_price_rub,
    net_price_rub = EXCLUDED.net_price_rub,
    marketing_seller_price_rub = EXCLUDED.marketing_seller_price_rub,
    color_index = EXCLUDED.color_index,
    commission_fbo_pct = EXCLUDED.commission_fbo_pct,
    commission_fbs_pct = EXCLUDED.commission_fbs_pct,
    acquiring_pct = EXCLUDED.acquiring_pct,
    synced_at = now()
`

type UpsertOzonProductPriceParams struct {
	SellerCabinetID         pgtype.UUID    `json:"seller_cabinet_id"`
	Sku                     int64          `json:"sku"`
	OfferID                 pgtype.Text    `json:"offer_id"`
	Name                    pgtype.Text    `json:"name"`
	PriceRub                pgtype.Numeric `json:"price_rub"`
	OldPriceRub             pgtype.Numeric `json:"old_price_rub"`
	MinPriceRub             pgtype.Numeric `json:"min_price_rub"`
	NetPriceRub             pgtype.Numeric `json:"net_price_rub"`
	MarketingSellerPriceRub pgtype.Numeric `json:"marketing_seller_price_rub"`
	ColorIndex              pgtype.Text    `json:"color_index"`
	CommissionFboPct        pgtype.Numeric `json:"commission_fbo_pct"`
	CommissionFbsPct        pgtype.Numeric `json:"commission_fbs_pct"`
	AcquiringPct            pgtype.Numeric `json:"acquiring_pct"`
}

func (q *Queries) UpsertOzonProductPrice(ctx context.Context, arg UpsertOzonProductPriceParams) error {
	_, err := q.db.Exec(ctx, upsertOzonProductPrice,
		arg.SellerCabinetID,
		arg.Sku,
		arg.OfferID,
		arg.Name,
		arg.PriceRub,
		arg.OldPriceRub,
		arg.MinPriceRub,
		arg.NetPriceRub,
		arg.MarketingSellerPriceRub,
		arg.ColorIndex,
		arg.CommissionFboPct,
		arg.CommissionFbsPct,
		arg.AcquiringPct,
	)
	return err
}
