// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ozon_schedules.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelOzonPriceScheduleEntry = `-- name: CancelOzonPriceScheduleEntry :one
UPDATE ozon_price_schedule_entries
SET status = 'cancelled'
WHERE id = $1 AND status = 'pending'
RETURNING id, seller_cabinet_id, sku, offer_id, scheduled_price_rub, revert_price_rub, starts_at, ends_at, status, error, created_at, applied_at, reverted_at
`

// CancelOzonPriceScheduleEntry cancels a pending entry (only pending rows
// can be cancelled; the WHERE clause makes the transition race-safe).
func (q *Queries) CancelOzonPriceScheduleEntry(ctx context.Context, id pgtype.UUID) (OzonPriceScheduleEntry, error) {
	row := q.db.QueryRow(ctx, cancelOzonPriceScheduleEntry, id)
	var i OzonPriceScheduleEntry
	err := row.Scan(
		&i.ID,
		&i.SellerCabinetID,
		&i.Sku,
		&i.OfferID,
		&i.ScheduledPriceRub,
		&i.RevertPriceRub,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.AppliedAt,
		&i.RevertedAt,
	)
	return i, err
}

const countOzonPriceScheduleEntriesByCabinet = `-- name: CountOzonPriceScheduleEntriesByCabinet :one
SELECT COUNT(*) FROM ozon_price_schedule_entries
WHERE seller_cabinet_id = $1
  AND ($2::text IS NULL OR status = $2::text)
`

type CountOzonPriceScheduleEntriesByCabinetParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Status          pgtype.Text `json:"status"`
}

func (q *Queries) CountOzonPriceScheduleEntriesByCabinet(ctx context.Context, arg CountOzonPriceScheduleEntriesByCabinetParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOzonPriceScheduleEntriesByCabinet, arg.SellerCabinetID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingOzonPriceSchedulesByCabinet = `-- name: CountPendingOzonPriceSchedulesByCabinet :one
SELECT COUNT(*) FROM ozon_price_schedule_entries
WHERE seller_cabinet_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingOzonPriceSchedulesByCabinet(ctx context.Context, sellerCabinetID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingOzonPriceSchedulesByCabinet, sellerCabinetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOzonPriceScheduleEntry = `-- name: CreateOzonPriceScheduleEntry :one

INSERT INTO ozon_price_schedule_entries (
    seller_cabinet_id, sku, offer_id, scheduled_price_rub, revert_price_rub,
    starts_at, ends_at
)
VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7
)
RETURNING id, seller_cabinet_id, sku, offer_id, scheduled_price_rub, revert_price_rub, starts_at, ends_at, status, error, created_at, applied_at, reverted_at
`

type CreateOzonPriceScheduleEntryParams struct {
	SellerCabinetID   pgtype.UUID        `json:"seller_cabinet_id"`
	Sku               int64              `json:"sku"`
	OfferID           pgtype.Text        `json:"offer_id"`
	ScheduledPriceRub pgtype.Numeric     `json:"scheduled_price_rub"`
	RevertPriceRub    pgtype.Numeric     `json:"revert_price_rub"`
	StartsAt          pgtype.Timestamptz `json:"starts_at"`
	EndsAt            pgtype.Timestamptz `json:"ends_at"`
}

// Ozon module phase 5 queries (price calendar with auto-revert + repricer
// health summary).
func (q *Queries) CreateOzonPriceScheduleEntry(ctx context.Context, arg CreateOzonPriceScheduleEntryParams) (OzonPriceScheduleEntry, error) {
	row := q.db.QueryRow(ctx, createOzonPriceScheduleEntry,
		arg.SellerCabinetID,
		arg.Sku,
		arg.OfferID,
		arg.ScheduledPriceRub,
		arg.RevertPriceRub,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i OzonPriceScheduleEntry
	err := row.Scan(
		&i.ID,
		&i.SellerCabinetID,
		&i.Sku,
		&i.OfferID,
		&i.ScheduledPriceRub,
		&i.RevertPriceRub,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.AppliedAt,
		&i.RevertedAt,
	)
	return i, err
}

const getOzonPriceScheduleEntry = `-- name: GetOzonPriceScheduleEntry :one
SELECT id, seller_cabinet_id, sku, offer_id, scheduled_price_rub, revert_price_rub, starts_at, ends_at, status, error, created_at, applied_at, reverted_at FROM ozon_price_schedule_entries WHERE id = $1
`

func (q *Queries) GetOzonPriceScheduleEntry(ctx context.Context, id pgtype.UUID) (OzonPriceScheduleEntry, error) {
	row := q.db.QueryRow(ctx, getOzonPriceScheduleEntry, id)
	var i OzonPriceScheduleEntry
	err := row.Scan(
		&i.ID,
		&i.SellerCabinetID,
		&i.Sku,
		&i.OfferID,
		&i.ScheduledPriceRub,
		&i.RevertPriceRub,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.AppliedAt,
		&i.RevertedAt,
	)
	return i, err
}

const lastOzonStrategySweepAt = `-- name: LastOzonStrategySweepAt :one
SELECT max(created_at)::timestamptz AS last_sweep_at
FROM ozon_price_changes
WHERE seller_cabinet_id = $1 AND source = 'strategy'
`

// LastOzonStrategySweepAt: when the strategy sweep last recorded a decision
// for this cabinet (max created_at over source='strategy' rows).
func (q *Queries) LastOzonStrategySweepAt(ctx context.Context, sellerCabinetID pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, lastOzonStrategySweepAt, sellerCabinetID)
	var last_sweep_at pgtype.Timestamptz
	err := row.Scan(&last_sweep_at)
	return last_sweep_at, err
}

const listDueOzonPriceScheduleReverts = `-- name: ListDueOzonPriceScheduleReverts :many
SELECT id, seller_cabinet_id, sku, offer_id, scheduled_price_rub, revert_price_rub, starts_at, ends_at, status, error, created_at, applied_at, reverted_at FROM ozon_price_schedule_entries
WHERE status = 'applied'
  AND ends_at IS NOT NULL AND ends_at <= $1
  AND revert_price_rub IS NOT NULL
ORDER BY ends_at
LIMIT $2
`

type ListDueOzonPriceScheduleRevertsParams struct {
	Now   pgtype.Timestamptz `json:"now"`
	Limit int32              `json:"limit"`
}

// ListDueOzonPriceScheduleReverts returns applied entries whose end time has
// passed and that carry a revert price to restore.
func (q *Queries) ListDueOzonPriceScheduleReverts(ctx context.Context, arg ListDueOzonPriceScheduleRevertsParams) ([]OzonPriceScheduleEntry, error) {
	rows, err := q.db.Query(ctx, listDueOzonPriceScheduleReverts, arg.Now, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OzonPriceScheduleEntry{}
	for rows.Next() {
		var i OzonPriceScheduleEntry
		if err := rows.Scan(
			&i.ID,
			&i.SellerCabinetID,
			&i.Sku,
			&i.OfferID,
			&i.ScheduledPriceRub,
			&i.RevertPriceRub,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.AppliedAt,
			&i.RevertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueOzonPriceSchedules = `-- name: ListDueOzonPriceSchedules :many
SELECT id, seller_cabinet_id, sku, offer_id, scheduled_price_rub, revert_price_rub, starts_at, ends_at, status, error, created_at, applied_at, reverted_at FROM ozon_price_schedule_entries
WHERE status = 'pending' AND starts_at <= $1
ORDER BY starts_at
LIMIT $2
`

type ListDueOzonPriceSchedulesParams struct {
	Now   pgtype.Timestamptz `json:"now"`
	Limit int32              `json:"limit"`
}

// ListDueOzonPriceSchedules returns pending entries whose start time has
// passed, across all cabinets (the 15m executor task runs globally).
func (q *Queries) ListDueOzonPriceSchedules(ctx context.Context, arg ListDueOzonPriceSchedulesParams) ([]OzonPriceScheduleEntry, error) {
	rows, err := q.db.Query(ctx, listDueOzonPriceSchedules, arg.Now, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OzonPriceScheduleEntry{}
	for rows.Next() {
		var i OzonPriceScheduleEntry
		if err := rows.Scan(
			&i.ID,
			&i.SellerCabinetID,
			&i.Sku,
			&i.OfferID,
			&i.ScheduledPriceRub,
			&i.RevertPriceRub,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.AppliedAt,
			&i.RevertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOzonPriceScheduleEntriesByCabinet = `-- name: ListOzonPriceScheduleEntriesByCabinet :many
SELECT id, seller_cabinet_id, sku, offer_id, scheduled_price_rub, revert_price_rub, starts_at, ends_at, status, error, created_at, applied_at, reverted_at FROM ozon_price_schedule_entries
WHERE seller_cabinet_id = $1
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY starts_at DESC
LIMIT $4 OFFSET $3
`

type ListOzonPriceScheduleEntriesByCabinetParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Status          pgtype.Text `json:"status"`
	Offset          int32       `json:"offset"`
	Limit           int32       `json:"limit"`
}

func (q *Queries) ListOzonPriceScheduleEntriesByCabinet(ctx context.Context, arg ListOzonPriceScheduleEntriesByCabinetParams) ([]OzonPriceScheduleEntry, error) {
	rows, err := q.db.Query(ctx, listOzonPriceScheduleEntriesByCabinet,
		arg.SellerCabinetID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OzonPriceScheduleEntry{}
	for rows.Next() {
		var i OzonPriceScheduleEntry
		if err := rows.Scan(
			&i.ID,
			&i.SellerCabinetID,
			&i.Sku,
			&i.OfferID,
			&i.ScheduledPriceRub,
			&i.RevertPriceRub,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.AppliedAt,
			&i.RevertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOzonPriceScheduleResult = `-- name: MarkOzonPriceScheduleResult :one
UPDATE ozon_price_schedule_entries
SET status = $1,
    error = $2,
    applied_at = CASE WHEN $1::text = 'applied' THEN now() ELSE applied_at END,
    reverted_at = CASE WHEN $1::text = 'reverted' THEN now() ELSE reverted_at END
WHERE id = $3
RETURNING id, seller_cabinet_id, sku, offer_id, scheduled_price_rub, revert_price_rub, starts_at, ends_at, status, error, created_at, applied_at, reverted_at
`

type MarkOzonPriceScheduleResultParams struct {
	Status string      `json:"status"`
	Error  pgtype.Text `json:"error"`
	ID     pgtype.UUID `json:"id"`
}

// MarkOzonPriceScheduleResult finalizes one entry: 'applied' stamps
// applied_at, 'reverted' stamps reverted_at, 'failed' records the error.
func (q *Queries) MarkOzonPriceScheduleResult(ctx context.Context, arg MarkOzonPriceScheduleResultParams) (OzonPriceScheduleEntry, error) {
	row := q.db.QueryRow(ctx, markOzonPriceScheduleResult, arg.Status, arg.Error, arg.ID)
	var i OzonPriceScheduleEntry
	err := row.Scan(
		&i.ID,
		&i.SellerCabinetID,
		&i.Sku,
		&i.OfferID,
		&i.ScheduledPriceRub,
		&i.RevertPriceRub,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.AppliedAt,
		&i.RevertedAt,
	)
	return i, err
}

const ozonPriceChanges24hSummary = `-- name: OzonPriceChanges24hSummary :one
SELECT
    COUNT(*) FILTER (WHERE status = 'applied')::bigint AS applied,
    COUNT(*) FILTER (WHERE status = 'shadow')::bigint  AS shadow,
    COUNT(*) FILTER (WHERE status = 'failed')::bigint  AS failed
FROM ozon_price_changes
WHERE seller_cabinet_id = $1 AND created_at > now() - interval '24 hours'
`

type OzonPriceChanges24hSummaryRow struct {
	Applied int64 `json:"applied"`
	Shadow  int64 `json:"shadow"`
	Failed  int64 `json:"failed"`
}

// OzonPriceChanges24hSummary feeds the repricer health endpoint.
func (q *Queries) OzonPriceChanges24hSummary(ctx context.Context, sellerCabinetID pgtype.UUID) (OzonPriceChanges24hSummaryRow, error) {
	row := q.db.QueryRow(ctx, ozonPriceChanges24hSummary, sellerCabinetID)
	var i OzonPriceChanges24hSummaryRow
	err := row.Scan(&i.Applied, &i.Shadow, &i.Failed)
	return i, err
}
