// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ozon_search_queries.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateOzonSearchQueries = `-- name: AggregateOzonSearchQueries :many
SELECT
    q.query,
    SUM(q.views)::bigint AS views,
    SUM(q.clicks)::bigint AS clicks,
    SUM(q.orders)::bigint AS orders,
    COALESCE(SUM(q.spend_rub), 0)::numeric AS spend_rub,
    (SUM(q.avg_position * GREATEST(q.views, 1)) FILTER (WHERE q.avg_position IS NOT NULL)
        / NULLIF(SUM(GREATEST(q.views, 1)) FILTER (WHERE q.avg_position IS NOT NULL), 0))::numeric AS avg_position,
    (ARRAY_AGG(q.sku ORDER BY q.views DESC))[1]::bigint AS top_sku
FROM ozon_search_queries q
WHERE q.seller_cabinet_id = $1
  AND q.date >= $2
  AND ($3::bigint IS NULL OR q.sku = $3::bigint)
  AND ($4::text IS NULL OR q.query ILIKE '%' || $4::text || '%')
GROUP BY q.query
ORDER BY SUM(q.views) DESC, q.query
LIMIT $6 OFFSET $5
`

type AggregateOzonSearchQueriesParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	DateFrom        pgtype.Date `json:"date_from"`
	Sku             pgtype.Int8 `json:"sku"`
	Search          pgtype.Text `json:"search"`
	Offset          int32       `json:"offset"`
	Limit           int32       `json:"limit"`
}

type AggregateOzonSearchQueriesRow struct {
	Query       string         `json:"query"`
	Views       int64          `json:"views"`
	Clicks      int64          `json:"clicks"`
	Orders      int64          `json:"orders"`
	SpendRub    pgtype.Numeric `json:"spend_rub"`
	AvgPosition pgtype.Numeric `json:"avg_position"`
	TopSku      int64          `json:"top_sku"`
}

// AggregateOzonSearchQueries powers GET /ozon/search-queries: per-query
// aggregate over a date window. avg_position is weighted by views over the
// rows that actually reported a position; top_sku is the highest-views SKU of
// the query (used for product-name enrichment).
func (q *Queries) AggregateOzonSearchQueries(ctx context.Context, arg AggregateOzonSearchQueriesParams) ([]AggregateOzonSearchQueriesRow, error) {
	rows, err := q.db.Query(ctx, aggregateOzonSearchQueries,
		arg.SellerCabinetID,
		arg.DateFrom,
		arg.Sku,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateOzonSearchQueriesRow{}
	for rows.Next() {
		var i AggregateOzonSearchQueriesRow
		if err := rows.Scan(
			&i.Query,
			&i.Views,
			&i.Clicks,
			&i.Orders,
			&i.SpendRub,
			&i.AvgPosition,
			&i.TopSku,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOzonSearchQueries = `-- name: CountOzonSearchQueries :one
SELECT COUNT(DISTINCT q.query) FROM ozon_search_queries q
WHERE q.seller_cabinet_id = $1
  AND q.date >= $2
  AND ($3::bigint IS NULL OR q.sku = $3::bigint)
  AND ($4::text IS NULL OR q.query ILIKE '%' || $4::text || '%')
`

type CountOzonSearchQueriesParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	DateFrom        pgtype.Date `json:"date_from"`
	Sku             pgtype.Int8 `json:"sku"`
	Search          pgtype.Text `json:"search"`
}

func (q *Queries) CountOzonSearchQueries(ctx context.Context, arg CountOzonSearchQueriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOzonSearchQueries,
		arg.SellerCabinetID,
		arg.DateFrom,
		arg.Sku,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listOzonPhraseCampaignRefs = `-- name: ListOzonPhraseCampaignRefs :many
SELECT id, ozon_campaign_id FROM ozon_campaigns
WHERE seller_cabinet_id = $1
  AND state = 'CAMPAIGN_STATE_RUNNING'
  AND adv_object_type IN ('SKU', 'SEARCH_PROMO')
ORDER BY ozon_campaign_id
`

type ListOzonPhraseCampaignRefsRow struct {
	ID             pgtype.UUID `json:"id"`
	OzonCampaignID int64       `json:"ozon_campaign_id"`
}

// ListOzonPhraseCampaignRefs picks the campaigns the phrases sync asks Ozon
// about: SKU / SEARCH_PROMO campaigns currently running.
func (q *Queries) ListOzonPhraseCampaignRefs(ctx context.Context, sellerCabinetID pgtype.UUID) ([]ListOzonPhraseCampaignRefsRow, error) {
	rows, err := q.db.Query(ctx, listOzonPhraseCampaignRefs, sellerCabinetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOzonPhraseCampaignRefsRow{}
	for rows.Next() {
		var i ListOzonPhraseCampaignRefsRow
		if err := rows.Scan(&i.ID, &i.OzonCampaignID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOzonSearchQueriesBySkus = `-- name: ListOzonSearchQueriesBySkus :many
SELECT
    q.sku,
    q.query,
    SUM(q.views)::bigint AS views,
    SUM(q.clicks)::bigint AS clicks,
    SUM(q.orders)::bigint AS orders,
    COALESCE(SUM(q.spend_rub), 0)::numeric AS spend_rub,
    (SUM(q.avg_position * GREATEST(q.views, 1)) FILTER (WHERE q.avg_position IS NOT NULL)
        / NULLIF(SUM(GREATEST(q.views, 1)) FILTER (WHERE q.avg_position IS NOT NULL), 0))::numeric AS avg_position
FROM ozon_search_queries q
WHERE q.seller_cabinet_id = $1
  AND q.sku = ANY($2::bigint[])
  AND q.date >= $3
GROUP BY q.sku, q.query
ORDER BY q.sku, SUM(q.views) DESC, q.query
LIMIT 20000
`

type ListOzonSearchQueriesBySkusParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Skus            []int64     `json:"skus"`
	DateFrom        pgtype.Date `json:"date_from"`
}

type ListOzonSearchQueriesBySkusRow struct {
	Sku         int64          `json:"sku"`
	Query       string         `json:"query"`
	Views       int64          `json:"views"`
	Clicks      int64          `json:"clicks"`
	Orders      int64          `json:"orders"`
	SpendRub    pgtype.Numeric `json:"spend_rub"`
	AvgPosition pgtype.Numeric `json:"avg_position"`
}

// ListOzonSearchQueriesBySkus serves the AI context pack / request_data:
// per-(sku, query) aggregates ordered by views within each SKU. The per-SKU
// top-N cut happens in Go (sqlc's analyzer cannot resolve ROW_NUMBER()
// filters); the LIMIT is a defensive bound only.
func (q *Queries) ListOzonSearchQueriesBySkus(ctx context.Context, arg ListOzonSearchQueriesBySkusParams) ([]ListOzonSearchQueriesBySkusRow, error) {
	rows, err := q.db.Query(ctx, listOzonSearchQueriesBySkus, arg.SellerCabinetID, arg.Skus, arg.DateFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOzonSearchQueriesBySkusRow{}
	for rows.Next() {
		var i ListOzonSearchQueriesBySkusRow
		if err := rows.Scan(
			&i.Sku,
			&i.Query,
			&i.Views,
			&i.Clicks,
			&i.Orders,
			&i.SpendRub,
			&i.AvgPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOzonSearchQuery = `-- name: UpsertOzonSearchQuery :exec

INSERT INTO ozon_search_queries (
    seller_cabinet_id, sku, query, date, views, clicks, orders, spend_rub, avg_position
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9
)
ON CONFLICT (seller_cabinet_id, sku, query, date) DO UPDATE SET
    views = EXCLUDED.views,
    clicks = EXCLUDED.clicks,
    orders = EXCLUDED.orders,
    spend_rub = EXCLUDED.spend_rub,
    avg_position = COALESCE(EXCLUDED.avg_position, ozon_search_queries.avg_position)
`

type UpsertOzonSearchQueryParams struct {
	SellerCabinetID pgtype.UUID    `json:"seller_cabinet_id"`
	Sku             int64          `json:"sku"`
	Query           string         `json:"query"`
	Date            pgtype.Date    `json:"date"`
	Views           int64          `json:"views"`
	Clicks          int64          `json:"clicks"`
	Orders          int64          `json:"orders"`
	SpendRub        pgtype.Numeric `json:"spend_rub"`
	AvgPosition     pgtype.Numeric `json:"avg_position"`
}

// Ozon search query statistics (Performance API phrases report mirror).
func (q *Queries) UpsertOzonSearchQuery(ctx context.Context, arg UpsertOzonSearchQueryParams) error {
	_, err := q.db.Exec(ctx, upsertOzonSearchQuery,
		arg.SellerCabinetID,
		arg.Sku,
		arg.Query,
		arg.Date,
		arg.Views,
		arg.Clicks,
		arg.Orders,
		arg.SpendRub,
		arg.AvgPosition,
	)
	return err
}
