// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ozon_campaign_sku_stats.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateOzonCampaignSkuStats = `-- name: AggregateOzonCampaignSkuStats :many
SELECT
    sku,
    COALESCE(SUM(views), 0)::BIGINT        AS views,
    COALESCE(SUM(clicks), 0)::BIGINT       AS clicks,
    COALESCE(SUM(spend_rub), 0)::NUMERIC   AS spend_rub,
    COALESCE(SUM(orders), 0)::BIGINT       AS orders,
    COALESCE(SUM(revenue_rub), 0)::NUMERIC AS revenue_rub
FROM ozon_campaign_sku_stats
WHERE seller_cabinet_id = $1
  AND ozon_campaign_id = $2
  AND date >= $3::DATE
GROUP BY sku
`

type AggregateOzonCampaignSkuStatsParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	OzonCampaignID  int64       `json:"ozon_campaign_id"`
	DateFrom        pgtype.Date `json:"date_from"`
}

type AggregateOzonCampaignSkuStatsRow struct {
	Sku        int64          `json:"sku"`
	Views      int64          `json:"views"`
	Clicks     int64          `json:"clicks"`
	SpendRub   pgtype.Numeric `json:"spend_rub"`
	Orders     int64          `json:"orders"`
	RevenueRub pgtype.Numeric `json:"revenue_rub"`
}

// AggregateOzonCampaignSkuStats sums one campaign's per-SKU counters over a
// date window — «сколько заказов принесла именно эта кампания этому SKU».
func (q *Queries) AggregateOzonCampaignSkuStats(ctx context.Context, arg AggregateOzonCampaignSkuStatsParams) ([]AggregateOzonCampaignSkuStatsRow, error) {
	rows, err := q.db.Query(ctx, aggregateOzonCampaignSkuStats, arg.SellerCabinetID, arg.OzonCampaignID, arg.DateFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateOzonCampaignSkuStatsRow{}
	for rows.Next() {
		var i AggregateOzonCampaignSkuStatsRow
		if err := rows.Scan(
			&i.Sku,
			&i.Views,
			&i.Clicks,
			&i.SpendRub,
			&i.Orders,
			&i.RevenueRub,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOzonSkuCampaignRefs = `-- name: ListOzonSkuCampaignRefs :many
SELECT id, ozon_campaign_id FROM ozon_campaigns
WHERE seller_cabinet_id = $1
  AND state = 'CAMPAIGN_STATE_RUNNING'
  AND adv_object_type = 'SKU'
ORDER BY ozon_campaign_id
`

type ListOzonSkuCampaignRefsRow struct {
	ID             pgtype.UUID `json:"id"`
	OzonCampaignID int64       `json:"ozon_campaign_id"`
}

// ListOzonSkuCampaignRefs picks the campaigns for the objects report: running
// SKU (трафареты) campaigns only — Ozon returns 400 «generation of this type
// of report is forbidden» when SEARCH_PROMO ids are in the list.
func (q *Queries) ListOzonSkuCampaignRefs(ctx context.Context, sellerCabinetID pgtype.UUID) ([]ListOzonSkuCampaignRefsRow, error) {
	rows, err := q.db.Query(ctx, listOzonSkuCampaignRefs, sellerCabinetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOzonSkuCampaignRefsRow{}
	for rows.Next() {
		var i ListOzonSkuCampaignRefsRow
		if err := rows.Scan(&i.ID, &i.OzonCampaignID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOzonCampaignSkuStat = `-- name: UpsertOzonCampaignSkuStat :exec
INSERT INTO ozon_campaign_sku_stats (
    seller_cabinet_id, ozon_campaign_id, sku, date,
    views, clicks, spend_rub, orders, revenue_rub
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (seller_cabinet_id, ozon_campaign_id, sku, date) DO UPDATE SET
    views       = EXCLUDED.views,
    clicks      = EXCLUDED.clicks,
    spend_rub   = EXCLUDED.spend_rub,
    orders      = EXCLUDED.orders,
    revenue_rub = EXCLUDED.revenue_rub
`

type UpsertOzonCampaignSkuStatParams struct {
	SellerCabinetID pgtype.UUID    `json:"seller_cabinet_id"`
	OzonCampaignID  int64          `json:"ozon_campaign_id"`
	Sku             int64          `json:"sku"`
	Date            pgtype.Date    `json:"date"`
	Views           int64          `json:"views"`
	Clicks          int64          `json:"clicks"`
	SpendRub        pgtype.Numeric `json:"spend_rub"`
	Orders          int64          `json:"orders"`
	RevenueRub      pgtype.Numeric `json:"revenue_rub"`
}

// UpsertOzonCampaignSkuStat writes one day of one campaign's SKU counters
// from the Performance API campaign report (idempotent re-sync).
func (q *Queries) UpsertOzonCampaignSkuStat(ctx context.Context, arg UpsertOzonCampaignSkuStatParams) error {
	_, err := q.db.Exec(ctx, upsertOzonCampaignSkuStat,
		arg.SellerCabinetID,
		arg.OzonCampaignID,
		arg.Sku,
		arg.Date,
		arg.Views,
		arg.Clicks,
		arg.SpendRub,
		arg.Orders,
		arg.RevenueRub,
	)
	return err
}
