// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ozon_actions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateOzonCampaignStatsSince = `-- name: AggregateOzonCampaignStatsSince :one
SELECT
    COALESCE(SUM(views), 0)::bigint AS views,
    COALESCE(SUM(clicks), 0)::bigint AS clicks,
    COALESCE(SUM(spend_rub), 0)::numeric AS spend_rub,
    COALESCE(SUM(orders), 0)::bigint AS orders,
    COALESCE(SUM(revenue_rub), 0)::numeric AS revenue_rub
FROM ozon_campaign_stats
WHERE campaign_id = $1 AND date >= $2
`

type AggregateOzonCampaignStatsSinceParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	Date       pgtype.Date `json:"date"`
}

type AggregateOzonCampaignStatsSinceRow struct {
	Views      int64          `json:"views"`
	Clicks     int64          `json:"clicks"`
	SpendRub   pgtype.Numeric `json:"spend_rub"`
	Orders     int64          `json:"orders"`
	RevenueRub pgtype.Numeric `json:"revenue_rub"`
}

func (q *Queries) AggregateOzonCampaignStatsSince(ctx context.Context, arg AggregateOzonCampaignStatsSinceParams) (AggregateOzonCampaignStatsSinceRow, error) {
	row := q.db.QueryRow(ctx, aggregateOzonCampaignStatsSince, arg.CampaignID, arg.Date)
	var i AggregateOzonCampaignStatsSinceRow
	err := row.Scan(
		&i.Views,
		&i.Clicks,
		&i.SpendRub,
		&i.Orders,
		&i.RevenueRub,
	)
	return i, err
}

const countOzonBidChangesByCabinet = `-- name: CountOzonBidChangesByCabinet :one
SELECT COUNT(*) FROM ozon_bid_changes bc
LEFT JOIN ozon_campaigns c ON c.id = bc.campaign_id
WHERE COALESCE(bc.seller_cabinet_id, c.seller_cabinet_id) = $1
  AND ($2::uuid IS NULL OR bc.campaign_id = $2::uuid)
`

type CountOzonBidChangesByCabinetParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	CampaignID      pgtype.UUID `json:"campaign_id"`
}

func (q *Queries) CountOzonBidChangesByCabinet(ctx context.Context, arg CountOzonBidChangesByCabinetParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOzonBidChangesByCabinet, arg.SellerCabinetID, arg.CampaignID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOzonCpoProducts = `-- name: CountOzonCpoProducts :one
SELECT COUNT(*) FROM ozon_cpo_products WHERE seller_cabinet_id = $1
`

func (q *Queries) CountOzonCpoProducts(ctx context.Context, sellerCabinetID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOzonCpoProducts, sellerCabinetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOzonStrategyBindingInWorkspace = `-- name: CreateOzonStrategyBindingInWorkspace :one
INSERT INTO strategy_bindings (strategy_id, ozon_campaign_id)
SELECT s.id, $1::uuid
FROM strategies s
WHERE s.id = $2 AND s.workspace_id = $3
  AND EXISTS (
      SELECT 1 FROM ozon_campaigns oc
      WHERE oc.id = $1::uuid
        AND oc.seller_cabinet_id = s.seller_cabinet_id
  )
RETURNING id, strategy_id, ozon_campaign_id, created_at
`

type CreateOzonStrategyBindingInWorkspaceParams struct {
	OzonCampaignID pgtype.UUID `json:"ozon_campaign_id"`
	StrategyID     pgtype.UUID `json:"strategy_id"`
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
}

type CreateOzonStrategyBindingInWorkspaceRow struct {
	ID             pgtype.UUID        `json:"id"`
	StrategyID     pgtype.UUID        `json:"strategy_id"`
	OzonCampaignID pgtype.UUID        `json:"ozon_campaign_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// CreateOzonStrategyBindingInWorkspace inserts an Ozon binding only when the
// strategy belongs to the workspace AND the ozon campaign belongs to the
// strategy's seller cabinet (tenancy in one statement, mirroring the WB
// CreateStrategyBindingInWorkspace).
func (q *Queries) CreateOzonStrategyBindingInWorkspace(ctx context.Context, arg CreateOzonStrategyBindingInWorkspaceParams) (CreateOzonStrategyBindingInWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, createOzonStrategyBindingInWorkspace, arg.OzonCampaignID, arg.StrategyID, arg.WorkspaceID)
	var i CreateOzonStrategyBindingInWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.StrategyID,
		&i.OzonCampaignID,
		&i.CreatedAt,
	)
	return i, err
}

const getOzonStrategyGuardState = `-- name: GetOzonStrategyGuardState :one
SELECT
    COALESCE(MAX(per_sku.changes_today), 0)::bigint AS max_changes_per_sku_today,
    MAX(per_sku.last_change_at)::timestamptz AS last_change_at
FROM (
    SELECT
        sku,
        COUNT(*) FILTER (WHERE created_at >= $1) AS changes_today,
        MAX(created_at) AS last_change_at
    FROM ozon_bid_changes
    WHERE campaign_id = $2
      AND source = 'strategy'
      AND status IN ('pending', 'applied', 'shadow')
    GROUP BY sku
) per_sku
`

type GetOzonStrategyGuardStateParams struct {
	DayStart   pgtype.Timestamptz `json:"day_start"`
	CampaignID pgtype.UUID        `json:"campaign_id"`
}

type GetOzonStrategyGuardStateRow struct {
	MaxChangesPerSkuToday int64              `json:"max_changes_per_sku_today"`
	LastChangeAt          pgtype.Timestamptz `json:"last_change_at"`
}

// GetOzonStrategyGuardState feeds the per-(campaign, sku) cooldown and
// daily-cap guardrails. The deterministic strategy scales every SKU of a
// campaign uniformly, so the worst (max) per-SKU counter is the campaign
// guard value. Shadow rows count too: promoting a strategy to live must not
// bypass a cooldown the shadow run just started.
func (q *Queries) GetOzonStrategyGuardState(ctx context.Context, arg GetOzonStrategyGuardStateParams) (GetOzonStrategyGuardStateRow, error) {
	row := q.db.QueryRow(ctx, getOzonStrategyGuardState, arg.DayStart, arg.CampaignID)
	var i GetOzonStrategyGuardStateRow
	err := row.Scan(&i.MaxChangesPerSkuToday, &i.LastChangeAt)
	return i, err
}

const insertOzonBidChange = `-- name: InsertOzonBidChange :one

INSERT INTO ozon_bid_changes (
    campaign_id, seller_cabinet_id, kind, sku, old_bid_rub, new_bid_rub,
    reason, source, status, decision_context
)
VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10
)
RETURNING id, campaign_id, seller_cabinet_id, kind, sku, old_bid_rub, new_bid_rub, reason, source, status, decision_context, error, created_at, applied_at
`

type InsertOzonBidChangeParams struct {
	CampaignID      pgtype.UUID    `json:"campaign_id"`
	SellerCabinetID pgtype.UUID    `json:"seller_cabinet_id"`
	Kind            string         `json:"kind"`
	Sku             pgtype.Int8    `json:"sku"`
	OldBidRub       pgtype.Numeric `json:"old_bid_rub"`
	NewBidRub       pgtype.Numeric `json:"new_bid_rub"`
	Reason          pgtype.Text    `json:"reason"`
	Source          string         `json:"source"`
	Status          string         `json:"status"`
	DecisionContext []byte         `json:"decision_context"`
}

// Ozon module phase 2 queries (campaign actions, bid audit, CPO, strategies).
func (q *Queries) InsertOzonBidChange(ctx context.Context, arg InsertOzonBidChangeParams) (OzonBidChange, error) {
	row := q.db.QueryRow(ctx, insertOzonBidChange,
		arg.CampaignID,
		arg.SellerCabinetID,
		arg.Kind,
		arg.Sku,
		arg.OldBidRub,
		arg.NewBidRub,
		arg.Reason,
		arg.Source,
		arg.Status,
		arg.DecisionContext,
	)
	var i OzonBidChange
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.SellerCabinetID,
		&i.Kind,
		&i.Sku,
		&i.OldBidRub,
		&i.NewBidRub,
		&i.Reason,
		&i.Source,
		&i.Status,
		&i.DecisionContext,
		&i.Error,
		&i.CreatedAt,
		&i.AppliedAt,
	)
	return i, err
}

const listOzonBidChangesByCabinet = `-- name: ListOzonBidChangesByCabinet :many
SELECT bc.id, bc.campaign_id, bc.seller_cabinet_id, bc.kind, bc.sku, bc.old_bid_rub, bc.new_bid_rub, bc.reason, bc.source, bc.status, bc.decision_context, bc.error, bc.created_at, bc.applied_at FROM ozon_bid_changes bc
LEFT JOIN ozon_campaigns c ON c.id = bc.campaign_id
WHERE COALESCE(bc.seller_cabinet_id, c.seller_cabinet_id) = $1
  AND ($2::uuid IS NULL OR bc.campaign_id = $2::uuid)
ORDER BY bc.created_at DESC
LIMIT $4 OFFSET $3
`

type ListOzonBidChangesByCabinetParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	CampaignID      pgtype.UUID `json:"campaign_id"`
	Offset          int32       `json:"offset"`
	Limit           int32       `json:"limit"`
}

func (q *Queries) ListOzonBidChangesByCabinet(ctx context.Context, arg ListOzonBidChangesByCabinetParams) ([]OzonBidChange, error) {
	rows, err := q.db.Query(ctx, listOzonBidChangesByCabinet,
		arg.SellerCabinetID,
		arg.CampaignID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OzonBidChange{}
	for rows.Next() {
		var i OzonBidChange
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.SellerCabinetID,
			&i.Kind,
			&i.Sku,
			&i.OldBidRub,
			&i.NewBidRub,
			&i.Reason,
			&i.Source,
			&i.Status,
			&i.DecisionContext,
			&i.Error,
			&i.CreatedAt,
			&i.AppliedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOzonCampaignBindingsByStrategy = `-- name: ListOzonCampaignBindingsByStrategy :many
SELECT
    b.id AS binding_id,
    b.created_at AS binding_created_at,
    c.id, c.seller_cabinet_id, c.ozon_campaign_id, c.title, c.adv_object_type,
    c.state, c.placement, c.autopilot_strategy, c.daily_budget_rub,
    c.weekly_budget_rub, c.from_date, c.to_date, c.created_at, c.updated_at
FROM strategy_bindings b
JOIN ozon_campaigns c ON c.id = b.ozon_campaign_id
WHERE b.strategy_id = $1
ORDER BY b.created_at
`

type ListOzonCampaignBindingsByStrategyRow struct {
	BindingID         pgtype.UUID        `json:"binding_id"`
	BindingCreatedAt  pgtype.Timestamptz `json:"binding_created_at"`
	ID                pgtype.UUID        `json:"id"`
	SellerCabinetID   pgtype.UUID        `json:"seller_cabinet_id"`
	OzonCampaignID    int64              `json:"ozon_campaign_id"`
	Title             pgtype.Text        `json:"title"`
	AdvObjectType     pgtype.Text        `json:"adv_object_type"`
	State             pgtype.Text        `json:"state"`
	Placement         pgtype.Text        `json:"placement"`
	AutopilotStrategy pgtype.Text        `json:"autopilot_strategy"`
	DailyBudgetRub    pgtype.Int8        `json:"daily_budget_rub"`
	WeeklyBudgetRub   pgtype.Int8        `json:"weekly_budget_rub"`
	FromDate          pgtype.Date        `json:"from_date"`
	ToDate            pgtype.Date        `json:"to_date"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListOzonCampaignBindingsByStrategy(ctx context.Context, strategyID pgtype.UUID) ([]ListOzonCampaignBindingsByStrategyRow, error) {
	rows, err := q.db.Query(ctx, listOzonCampaignBindingsByStrategy, strategyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOzonCampaignBindingsByStrategyRow{}
	for rows.Next() {
		var i ListOzonCampaignBindingsByStrategyRow
		if err := rows.Scan(
			&i.BindingID,
			&i.BindingCreatedAt,
			&i.ID,
			&i.SellerCabinetID,
			&i.OzonCampaignID,
			&i.Title,
			&i.AdvObjectType,
			&i.State,
			&i.Placement,
			&i.AutopilotStrategy,
			&i.DailyBudgetRub,
			&i.WeeklyBudgetRub,
			&i.FromDate,
			&i.ToDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOzonCpoProducts = `-- name: ListOzonCpoProducts :many
SELECT id, seller_cabinet_id, sku, enabled, bid, bid_kind, updated_at, offer_id, name, price_rub, bid_price_rub, image_url, visibility_index FROM ozon_cpo_products
WHERE seller_cabinet_id = $1
ORDER BY sku
LIMIT $2 OFFSET $3
`

type ListOzonCpoProductsParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Limit           int32       `json:"limit"`
	Offset          int32       `json:"offset"`
}

func (q *Queries) ListOzonCpoProducts(ctx context.Context, arg ListOzonCpoProductsParams) ([]OzonCpoProduct, error) {
	rows, err := q.db.Query(ctx, listOzonCpoProducts, arg.SellerCabinetID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OzonCpoProduct{}
	for rows.Next() {
		var i OzonCpoProduct
		if err := rows.Scan(
			&i.ID,
			&i.SellerCabinetID,
			&i.Sku,
			&i.Enabled,
			&i.Bid,
			&i.BidKind,
			&i.UpdatedAt,
			&i.OfferID,
			&i.Name,
			&i.PriceRub,
			&i.BidPriceRub,
			&i.ImageUrl,
			&i.VisibilityIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOzonBidChangeResult = `-- name: MarkOzonBidChangeResult :exec
UPDATE ozon_bid_changes
SET status = $1,
    error = $2,
    applied_at = CASE WHEN $1::text = 'applied' THEN now() ELSE applied_at END
WHERE id = $3
`

type MarkOzonBidChangeResultParams struct {
	Status string      `json:"status"`
	Error  pgtype.Text `json:"error"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) MarkOzonBidChangeResult(ctx context.Context, arg MarkOzonBidChangeResultParams) error {
	_, err := q.db.Exec(ctx, markOzonBidChangeResult, arg.Status, arg.Error, arg.ID)
	return err
}

const setOzonCpoProductsEnabled = `-- name: SetOzonCpoProductsEnabled :exec
UPDATE ozon_cpo_products SET enabled = $1, updated_at = now()
WHERE seller_cabinet_id = $2
  AND sku = ANY($3::bigint[])
`

type SetOzonCpoProductsEnabledParams struct {
	Enabled         bool        `json:"enabled"`
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Skus            []int64     `json:"skus"`
}

func (q *Queries) SetOzonCpoProductsEnabled(ctx context.Context, arg SetOzonCpoProductsEnabledParams) error {
	_, err := q.db.Exec(ctx, setOzonCpoProductsEnabled, arg.Enabled, arg.SellerCabinetID, arg.Skus)
	return err
}

const updateOzonCampaignBudgets = `-- name: UpdateOzonCampaignBudgets :exec
UPDATE ozon_campaigns SET
    daily_budget_rub = COALESCE($1, daily_budget_rub),
    weekly_budget_rub = COALESCE($2, weekly_budget_rub),
    updated_at = now()
WHERE id = $3
`

type UpdateOzonCampaignBudgetsParams struct {
	DailyBudgetRub  pgtype.Int8 `json:"daily_budget_rub"`
	WeeklyBudgetRub pgtype.Int8 `json:"weekly_budget_rub"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateOzonCampaignBudgets(ctx context.Context, arg UpdateOzonCampaignBudgetsParams) error {
	_, err := q.db.Exec(ctx, updateOzonCampaignBudgets, arg.DailyBudgetRub, arg.WeeklyBudgetRub, arg.ID)
	return err
}

const updateOzonCampaignProductBid = `-- name: UpdateOzonCampaignProductBid :exec
UPDATE ozon_campaign_products SET
    bid_rub = $1,
    target_cir = COALESCE($2, target_cir),
    updated_at = now()
WHERE campaign_id = $3 AND sku = $4
`

type UpdateOzonCampaignProductBidParams struct {
	BidRub     pgtype.Numeric `json:"bid_rub"`
	TargetCir  pgtype.Numeric `json:"target_cir"`
	CampaignID pgtype.UUID    `json:"campaign_id"`
	Sku        int64          `json:"sku"`
}

func (q *Queries) UpdateOzonCampaignProductBid(ctx context.Context, arg UpdateOzonCampaignProductBidParams) error {
	_, err := q.db.Exec(ctx, updateOzonCampaignProductBid,
		arg.BidRub,
		arg.TargetCir,
		arg.CampaignID,
		arg.Sku,
	)
	return err
}

const updateOzonCampaignState = `-- name: UpdateOzonCampaignState :exec
UPDATE ozon_campaigns SET state = $2, updated_at = now() WHERE id = $1
`

type UpdateOzonCampaignStateParams struct {
	ID    pgtype.UUID `json:"id"`
	State pgtype.Text `json:"state"`
}

func (q *Queries) UpdateOzonCampaignState(ctx context.Context, arg UpdateOzonCampaignStateParams) error {
	_, err := q.db.Exec(ctx, updateOzonCampaignState, arg.ID, arg.State)
	return err
}

const updateOzonCpoProductBid = `-- name: UpdateOzonCpoProductBid :exec
UPDATE ozon_cpo_products SET
    bid = $1,
    bid_kind = COALESCE($2, bid_kind),
    updated_at = now()
WHERE seller_cabinet_id = $3 AND sku = $4
`

type UpdateOzonCpoProductBidParams struct {
	Bid             pgtype.Numeric `json:"bid"`
	BidKind         pgtype.Text    `json:"bid_kind"`
	SellerCabinetID pgtype.UUID    `json:"seller_cabinet_id"`
	Sku             int64          `json:"sku"`
}

func (q *Queries) UpdateOzonCpoProductBid(ctx context.Context, arg UpdateOzonCpoProductBidParams) error {
	_, err := q.db.Exec(ctx, updateOzonCpoProductBid,
		arg.Bid,
		arg.BidKind,
		arg.SellerCabinetID,
		arg.Sku,
	)
	return err
}

const upsertOzonCpoProduct = `-- name: UpsertOzonCpoProduct :exec
INSERT INTO ozon_cpo_products (
    seller_cabinet_id, sku, enabled, bid, bid_kind,
    offer_id, name, price_rub, bid_price_rub, image_url, visibility_index
)
VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8,
    $9, $10, $11
)
ON CONFLICT (seller_cabinet_id, sku) DO UPDATE SET
    enabled = EXCLUDED.enabled,
    bid = COALESCE(EXCLUDED.bid, ozon_cpo_products.bid),
    bid_kind = COALESCE(EXCLUDED.bid_kind, ozon_cpo_products.bid_kind),
    offer_id = COALESCE(EXCLUDED.offer_id, ozon_cpo_products.offer_id),
    name = COALESCE(EXCLUDED.name, ozon_cpo_products.name),
    price_rub = COALESCE(EXCLUDED.price_rub, ozon_cpo_products.price_rub),
    bid_price_rub = COALESCE(EXCLUDED.bid_price_rub, ozon_cpo_products.bid_price_rub),
    image_url = COALESCE(EXCLUDED.image_url, ozon_cpo_products.image_url),
    visibility_index = COALESCE(EXCLUDED.visibility_index, ozon_cpo_products.visibility_index),
    updated_at = now()
`

type UpsertOzonCpoProductParams struct {
	SellerCabinetID pgtype.UUID    `json:"seller_cabinet_id"`
	Sku             int64          `json:"sku"`
	Enabled         bool           `json:"enabled"`
	Bid             pgtype.Numeric `json:"bid"`
	BidKind         pgtype.Text    `json:"bid_kind"`
	OfferID         pgtype.Text    `json:"offer_id"`
	Name            pgtype.Text    `json:"name"`
	PriceRub        pgtype.Numeric `json:"price_rub"`
	BidPriceRub     pgtype.Numeric `json:"bid_price_rub"`
	ImageUrl        pgtype.Text    `json:"image_url"`
	VisibilityIndex pgtype.Text    `json:"visibility_index"`
}

func (q *Queries) UpsertOzonCpoProduct(ctx context.Context, arg UpsertOzonCpoProductParams) error {
	_, err := q.db.Exec(ctx, upsertOzonCpoProduct,
		arg.SellerCabinetID,
		arg.Sku,
		arg.Enabled,
		arg.Bid,
		arg.BidKind,
		arg.OfferID,
		arg.Name,
		arg.PriceRub,
		arg.BidPriceRub,
		arg.ImageUrl,
		arg.VisibilityIndex,
	)
	return err
}
