// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ozon_inventory.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateOzonCabinetAdSpendSince = `-- name: AggregateOzonCabinetAdSpendSince :one
SELECT COALESCE(SUM(s.spend_rub), 0)::numeric AS spend_rub
FROM ozon_campaign_stats s
JOIN ozon_campaigns c ON c.id = s.campaign_id
WHERE c.seller_cabinet_id = $1
  AND s.date >= $2
`

type AggregateOzonCabinetAdSpendSinceParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Since           pgtype.Date `json:"since"`
}

// AggregateOzonCabinetAdSpendSince sums the ad spend of every campaign of the
// cabinet over the same window — the numerator of the total ДРР.
func (q *Queries) AggregateOzonCabinetAdSpendSince(ctx context.Context, arg AggregateOzonCabinetAdSpendSinceParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, aggregateOzonCabinetAdSpendSince, arg.SellerCabinetID, arg.Since)
	var spend_rub pgtype.Numeric
	err := row.Scan(&spend_rub)
	return spend_rub, err
}

const aggregateOzonCabinetTotalSalesSince = `-- name: AggregateOzonCabinetTotalSalesSince :one

SELECT COALESCE(SUM(revenue_rub), 0)::numeric AS revenue_rub,
       MAX(date)::date                        AS last_date
FROM ozon_sales_daily
WHERE seller_cabinet_id = $1
  AND date >= $2
`

type AggregateOzonCabinetTotalSalesSinceParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Since           pgtype.Date `json:"since"`
}

type AggregateOzonCabinetTotalSalesSinceRow struct {
	RevenueRub pgtype.Numeric `json:"revenue_rub"`
	LastDate   pgtype.Date    `json:"last_date"`
}

// --- «ДРР от общего оборота»: cabinet-wide turnover vs cabinet-wide ad spend ---
//
// Both sides are cabinet-scoped on purpose. A SKU can sit in several
// campaigns, so splitting the turnover per campaign needs an attribution rule
// that does not exist yet; the cabinet aggregate has no double counting.
// AggregateOzonCabinetTotalSalesSince sums the cabinet's whole turnover over a
// lookback window. last_date is the newest day that actually has data — the
// caller uses it to tell fresh numbers from a stalled ozon:sync_analytics.
func (q *Queries) AggregateOzonCabinetTotalSalesSince(ctx context.Context, arg AggregateOzonCabinetTotalSalesSinceParams) (AggregateOzonCabinetTotalSalesSinceRow, error) {
	row := q.db.QueryRow(ctx, aggregateOzonCabinetTotalSalesSince, arg.SellerCabinetID, arg.Since)
	var i AggregateOzonCabinetTotalSalesSinceRow
	err := row.Scan(&i.RevenueRub, &i.LastDate)
	return i, err
}

const getOzonCabinetAdSpendWindowTotals = `-- name: GetOzonCabinetAdSpendWindowTotals :one
SELECT COALESCE(SUM(s.spend_rub), 0)::numeric AS spend_rub,
       COUNT(*)::bigint                       AS days
FROM ozon_campaign_stats s
JOIN ozon_campaigns c ON c.id = s.campaign_id
WHERE c.seller_cabinet_id = $1
  AND s.date BETWEEN $2 AND $3
`

type GetOzonCabinetAdSpendWindowTotalsParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	DateFrom        pgtype.Date `json:"date_from"`
	DateTo          pgtype.Date `json:"date_to"`
}

type GetOzonCabinetAdSpendWindowTotalsRow struct {
	SpendRub pgtype.Numeric `json:"spend_rub"`
	Days     int64          `json:"days"`
}

// GetOzonCabinetAdSpendWindowTotals mirrors the above for the spend side.
func (q *Queries) GetOzonCabinetAdSpendWindowTotals(ctx context.Context, arg GetOzonCabinetAdSpendWindowTotalsParams) (GetOzonCabinetAdSpendWindowTotalsRow, error) {
	row := q.db.QueryRow(ctx, getOzonCabinetAdSpendWindowTotals, arg.SellerCabinetID, arg.DateFrom, arg.DateTo)
	var i GetOzonCabinetAdSpendWindowTotalsRow
	err := row.Scan(&i.SpendRub, &i.Days)
	return i, err
}

const getOzonCabinetSalesWindowTotals = `-- name: GetOzonCabinetSalesWindowTotals :one
SELECT COALESCE(SUM(revenue_rub), 0)::numeric   AS revenue_rub,
       COALESCE(SUM(ordered_units), 0)::bigint  AS ordered_units,
       COUNT(*)::bigint                         AS days
FROM ozon_sales_daily
WHERE seller_cabinet_id = $1
  AND date BETWEEN $2 AND $3
`

type GetOzonCabinetSalesWindowTotalsParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	DateFrom        pgtype.Date `json:"date_from"`
	DateTo          pgtype.Date `json:"date_to"`
}

type GetOzonCabinetSalesWindowTotalsRow struct {
	RevenueRub   pgtype.Numeric `json:"revenue_rub"`
	OrderedUnits int64          `json:"ordered_units"`
	Days         int64          `json:"days"`
}

// GetOzonCabinetSalesWindowTotals is the closed-window variant used by the AI
// impact sweep (before/after comparison around an applied decision).
func (q *Queries) GetOzonCabinetSalesWindowTotals(ctx context.Context, arg GetOzonCabinetSalesWindowTotalsParams) (GetOzonCabinetSalesWindowTotalsRow, error) {
	row := q.db.QueryRow(ctx, getOzonCabinetSalesWindowTotals, arg.SellerCabinetID, arg.DateFrom, arg.DateTo)
	var i GetOzonCabinetSalesWindowTotalsRow
	err := row.Scan(&i.RevenueRub, &i.OrderedUnits, &i.Days)
	return i, err
}

const listOzonProductStocksByCabinet = `-- name: ListOzonProductStocksByCabinet :many
SELECT id, seller_cabinet_id, sku, offer_id, present, reserved, synced_at FROM ozon_product_stocks WHERE seller_cabinet_id = $1
`

func (q *Queries) ListOzonProductStocksByCabinet(ctx context.Context, sellerCabinetID pgtype.UUID) ([]OzonProductStock, error) {
	rows, err := q.db.Query(ctx, listOzonProductStocksByCabinet, sellerCabinetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OzonProductStock{}
	for rows.Next() {
		var i OzonProductStock
		if err := rows.Scan(
			&i.ID,
			&i.SellerCabinetID,
			&i.Sku,
			&i.OfferID,
			&i.Present,
			&i.Reserved,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ozonCampaignAttributedTurnoverByCabinet = `-- name: OzonCampaignAttributedTurnoverByCabinet :many
WITH campaign_spend AS (
    SELECT c.id AS campaign_id,
           COALESCE(SUM(s.spend_rub), 0)::numeric AS spend_rub
    FROM ozon_campaigns c
    LEFT JOIN ozon_campaign_stats s
           ON s.campaign_id = c.id AND s.date >= $1
    WHERE c.seller_cabinet_id = $2
    GROUP BY c.id
),
sku_spend AS (
    SELECT cp.sku, SUM(cs.spend_rub)::numeric AS spend_rub
    FROM ozon_campaign_products cp
    JOIN campaign_spend cs ON cs.campaign_id = cp.campaign_id
    GROUP BY cp.sku
),
sku_turnover AS (
    SELECT sku,
           COALESCE(SUM(revenue_rub), 0)::numeric AS revenue_rub,
           MAX(date) AS last_date
    FROM ozon_sales_daily
    WHERE seller_cabinet_id = $2
      AND date >= $1
    GROUP BY sku
)
SELECT cp.campaign_id,
       COALESCE(SUM(st.revenue_rub * cs.spend_rub / NULLIF(ss.spend_rub, 0)), 0)::numeric AS revenue_rub,
       COALESCE(BOOL_OR(ss.spend_rub > cs.spend_rub), FALSE)::boolean                     AS revenue_shared,
       MAX(st.last_date)::date                                                            AS last_date
FROM ozon_campaign_products cp
JOIN campaign_spend cs ON cs.campaign_id = cp.campaign_id
JOIN sku_spend ss ON ss.sku = cp.sku
JOIN sku_turnover st ON st.sku = cp.sku
GROUP BY cp.campaign_id
`

type OzonCampaignAttributedTurnoverByCabinetParams struct {
	Since           pgtype.Date `json:"since"`
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
}

type OzonCampaignAttributedTurnoverByCabinetRow struct {
	CampaignID    pgtype.UUID    `json:"campaign_id"`
	RevenueRub    pgtype.Numeric `json:"revenue_rub"`
	RevenueShared bool           `json:"revenue_shared"`
	LastDate      pgtype.Date    `json:"last_date"`
}

// OzonCampaignAttributedTurnoverByCabinet splits the cabinet's turnover across
// its campaigns so a per-campaign «ДРР от общего оборота» can be computed
// without double counting.
//
// A SKU advertised by several campaigns has its turnover divided between them
// in proportion to what each campaign spent over the window:
//
//	attributed(C) = Σ over SKUs of C:  turnover(sku) × spend(C) / spend_on(sku)
//
// Summed over every campaign that advertises a SKU this returns exactly that
// SKU's turnover — never more. A SKU with no ad spend anywhere contributes
// nothing: NULLIF drops it rather than dividing by zero.
//
// revenue_shared flags campaigns whose SKUs are also advertised elsewhere, so
// a decision context can say whether the denominator was split or whole.
func (q *Queries) OzonCampaignAttributedTurnoverByCabinet(ctx context.Context, arg OzonCampaignAttributedTurnoverByCabinetParams) ([]OzonCampaignAttributedTurnoverByCabinetRow, error) {
	rows, err := q.db.Query(ctx, ozonCampaignAttributedTurnoverByCabinet, arg.Since, arg.SellerCabinetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OzonCampaignAttributedTurnoverByCabinetRow{}
	for rows.Next() {
		var i OzonCampaignAttributedTurnoverByCabinetRow
		if err := rows.Scan(
			&i.CampaignID,
			&i.RevenueRub,
			&i.RevenueShared,
			&i.LastDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ozonSalesVelocityByCabinet = `-- name: OzonSalesVelocityByCabinet :many
SELECT sku,
       COALESCE(SUM(ordered_units), 0)::bigint  AS units,
       COALESCE(SUM(revenue_rub), 0)::numeric   AS revenue_rub
FROM ozon_sales_daily
WHERE seller_cabinet_id = $1 AND date >= $2
GROUP BY sku
`

type OzonSalesVelocityByCabinetParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Date            pgtype.Date `json:"date"`
}

type OzonSalesVelocityByCabinetRow struct {
	Sku        int64          `json:"sku"`
	Units      int64          `json:"units"`
	RevenueRub pgtype.Numeric `json:"revenue_rub"`
}

// OzonSalesVelocityByCabinet sums ordered units and revenue per sales SKU
// over a lookback window; the caller divides by the window length to get
// units/day.
func (q *Queries) OzonSalesVelocityByCabinet(ctx context.Context, arg OzonSalesVelocityByCabinetParams) ([]OzonSalesVelocityByCabinetRow, error) {
	rows, err := q.db.Query(ctx, ozonSalesVelocityByCabinet, arg.SellerCabinetID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OzonSalesVelocityByCabinetRow{}
	for rows.Next() {
		var i OzonSalesVelocityByCabinetRow
		if err := rows.Scan(&i.Sku, &i.Units, &i.RevenueRub); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ozonSkuAdSpendByCabinet = `-- name: OzonSkuAdSpendByCabinet :many
SELECT cp.sku,
       COALESCE(SUM(s.spend_rub), 0)::numeric   AS spend_rub,
       COALESCE(SUM(s.revenue_rub), 0)::numeric AS revenue_rub
FROM ozon_campaign_products cp
JOIN ozon_campaigns c ON c.id = cp.campaign_id
JOIN ozon_campaign_stats s ON s.campaign_id = c.id
WHERE c.seller_cabinet_id = $1 AND s.date >= $2
GROUP BY cp.sku
`

type OzonSkuAdSpendByCabinetParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Date            pgtype.Date `json:"date"`
}

type OzonSkuAdSpendByCabinetRow struct {
	Sku        int64          `json:"sku"`
	SpendRub   pgtype.Numeric `json:"spend_rub"`
	RevenueRub pgtype.Numeric `json:"revenue_rub"`
}

// OzonSkuAdSpendByCabinet attributes campaign-level spend/revenue to every
// SKU of the campaign (ozon_campaign_stats has no per-SKU split): a SKU in
// several campaigns aggregates across them, so its ДРР is the blended
// campaign ДРР of its placements. sku here is the SALES sku.
func (q *Queries) OzonSkuAdSpendByCabinet(ctx context.Context, arg OzonSkuAdSpendByCabinetParams) ([]OzonSkuAdSpendByCabinetRow, error) {
	rows, err := q.db.Query(ctx, ozonSkuAdSpendByCabinet, arg.SellerCabinetID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OzonSkuAdSpendByCabinetRow{}
	for rows.Next() {
		var i OzonSkuAdSpendByCabinetRow
		if err := rows.Scan(&i.Sku, &i.SpendRub, &i.RevenueRub); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOzonProductStock = `-- name: UpsertOzonProductStock :exec

INSERT INTO ozon_product_stocks (seller_cabinet_id, sku, offer_id, present, reserved, synced_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (seller_cabinet_id, sku) DO UPDATE SET
    offer_id = EXCLUDED.offer_id,
    present = EXCLUDED.present,
    reserved = EXCLUDED.reserved,
    synced_at = now()
`

type UpsertOzonProductStockParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Sku             int64       `json:"sku"`
	OfferID         pgtype.Text `json:"offer_id"`
	Present         int32       `json:"present"`
	Reserved        int32       `json:"reserved"`
}

// Ozon module phase 5 queries (stocks + daily sales + per-SKU ad spend for
// the inventory-demand and ad-linked repricer strategies).
func (q *Queries) UpsertOzonProductStock(ctx context.Context, arg UpsertOzonProductStockParams) error {
	_, err := q.db.Exec(ctx, upsertOzonProductStock,
		arg.SellerCabinetID,
		arg.Sku,
		arg.OfferID,
		arg.Present,
		arg.Reserved,
	)
	return err
}

const upsertOzonSalesDaily = `-- name: UpsertOzonSalesDaily :exec
INSERT INTO ozon_sales_daily (seller_cabinet_id, sku, date, ordered_units, revenue_rub)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (seller_cabinet_id, sku, date) DO UPDATE SET
    ordered_units = EXCLUDED.ordered_units,
    revenue_rub = EXCLUDED.revenue_rub
`

type UpsertOzonSalesDailyParams struct {
	SellerCabinetID pgtype.UUID    `json:"seller_cabinet_id"`
	Sku             int64          `json:"sku"`
	Date            pgtype.Date    `json:"date"`
	OrderedUnits    int32          `json:"ordered_units"`
	RevenueRub      pgtype.Numeric `json:"revenue_rub"`
}

func (q *Queries) UpsertOzonSalesDaily(ctx context.Context, arg UpsertOzonSalesDailyParams) error {
	_, err := q.db.Exec(ctx, upsertOzonSalesDaily,
		arg.SellerCabinetID,
		arg.Sku,
		arg.Date,
		arg.OrderedUnits,
		arg.RevenueRub,
	)
	return err
}
