// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: phrases.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPhrase = `-- name: CreatePhrase :one
INSERT INTO phrases (campaign_id, workspace_id, wb_cluster_id, keyword, count, current_bid)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, campaign_id, workspace_id, wb_cluster_id, keyword, count, current_bid, created_at, updated_at
`

type CreatePhraseParams struct {
	CampaignID  pgtype.UUID `json:"campaign_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	WbClusterID int64       `json:"wb_cluster_id"`
	Keyword     string      `json:"keyword"`
	Count       pgtype.Int4 `json:"count"`
	CurrentBid  pgtype.Int8 `json:"current_bid"`
}

func (q *Queries) CreatePhrase(ctx context.Context, arg CreatePhraseParams) (Phrase, error) {
	row := q.db.QueryRow(ctx, createPhrase,
		arg.CampaignID,
		arg.WorkspaceID,
		arg.WbClusterID,
		arg.Keyword,
		arg.Count,
		arg.CurrentBid,
	)
	var i Phrase
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.WorkspaceID,
		&i.WbClusterID,
		&i.Keyword,
		&i.Count,
		&i.CurrentBid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPhraseByID = `-- name: GetPhraseByID :one
SELECT id, campaign_id, workspace_id, wb_cluster_id, keyword, count, current_bid, created_at, updated_at FROM phrases WHERE id = $1
`

func (q *Queries) GetPhraseByID(ctx context.Context, id pgtype.UUID) (Phrase, error) {
	row := q.db.QueryRow(ctx, getPhraseByID, id)
	var i Phrase
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.WorkspaceID,
		&i.WbClusterID,
		&i.Keyword,
		&i.Count,
		&i.CurrentBid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPhrasesByCampaign = `-- name: ListPhrasesByCampaign :many
SELECT id, campaign_id, workspace_id, wb_cluster_id, keyword, count, current_bid, created_at, updated_at FROM phrases
WHERE campaign_id = $1
ORDER BY keyword
LIMIT $2 OFFSET $3
`

type ListPhrasesByCampaignParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListPhrasesByCampaign(ctx context.Context, arg ListPhrasesByCampaignParams) ([]Phrase, error) {
	rows, err := q.db.Query(ctx, listPhrasesByCampaign, arg.CampaignID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Phrase{}
	for rows.Next() {
		var i Phrase
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.WorkspaceID,
			&i.WbClusterID,
			&i.Keyword,
			&i.Count,
			&i.CurrentBid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhrasesByWorkspace = `-- name: ListPhrasesByWorkspace :many
SELECT id, campaign_id, workspace_id, wb_cluster_id, keyword, count, current_bid, created_at, updated_at FROM phrases
WHERE workspace_id = $1
ORDER BY keyword
LIMIT $2 OFFSET $3
`

type ListPhrasesByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) ListPhrasesByWorkspace(ctx context.Context, arg ListPhrasesByWorkspaceParams) ([]Phrase, error) {
	rows, err := q.db.Query(ctx, listPhrasesByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Phrase{}
	for rows.Next() {
		var i Phrase
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.WorkspaceID,
			&i.WbClusterID,
			&i.Keyword,
			&i.Count,
			&i.CurrentBid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPhrase = `-- name: UpsertPhrase :one
INSERT INTO phrases (campaign_id, workspace_id, wb_cluster_id, keyword, count, current_bid)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (wb_cluster_id, campaign_id) DO UPDATE SET
    keyword = EXCLUDED.keyword,
    count = EXCLUDED.count,
    current_bid = EXCLUDED.current_bid,
    updated_at = now()
RETURNING id, campaign_id, workspace_id, wb_cluster_id, keyword, count, current_bid, created_at, updated_at
`

type UpsertPhraseParams struct {
	CampaignID  pgtype.UUID `json:"campaign_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	WbClusterID int64       `json:"wb_cluster_id"`
	Keyword     string      `json:"keyword"`
	Count       pgtype.Int4 `json:"count"`
	CurrentBid  pgtype.Int8 `json:"current_bid"`
}

func (q *Queries) UpsertPhrase(ctx context.Context, arg UpsertPhraseParams) (Phrase, error) {
	row := q.db.QueryRow(ctx, upsertPhrase,
		arg.CampaignID,
		arg.WorkspaceID,
		arg.WbClusterID,
		arg.Keyword,
		arg.Count,
		arg.CurrentBid,
	)
	var i Phrase
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.WorkspaceID,
		&i.WbClusterID,
		&i.Keyword,
		&i.Count,
		&i.CurrentBid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
