// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: phrase_stats.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPhraseStat = `-- name: CreatePhraseStat :one
INSERT INTO phrase_stats (phrase_id, date, impressions, clicks, spend, atbs, orders, cpc, cpm, avg_pos)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, phrase_id, date, impressions, clicks, spend, atbs, orders, cpc, cpm, avg_pos, created_at, updated_at
`

type CreatePhraseStatParams struct {
	PhraseID    pgtype.UUID   `json:"phrase_id"`
	Date        pgtype.Date   `json:"date"`
	Impressions int64         `json:"impressions"`
	Clicks      int64         `json:"clicks"`
	Spend       int64         `json:"spend"`
	Atbs        pgtype.Int8   `json:"atbs"`
	Orders      pgtype.Int8   `json:"orders"`
	Cpc         pgtype.Float8 `json:"cpc"`
	Cpm         pgtype.Float8 `json:"cpm"`
	AvgPos      pgtype.Float8 `json:"avg_pos"`
}

func (q *Queries) CreatePhraseStat(ctx context.Context, arg CreatePhraseStatParams) (PhraseStat, error) {
	row := q.db.QueryRow(ctx, createPhraseStat,
		arg.PhraseID,
		arg.Date,
		arg.Impressions,
		arg.Clicks,
		arg.Spend,
		arg.Atbs,
		arg.Orders,
		arg.Cpc,
		arg.Cpm,
		arg.AvgPos,
	)
	var i PhraseStat
	err := row.Scan(
		&i.ID,
		&i.PhraseID,
		&i.Date,
		&i.Impressions,
		&i.Clicks,
		&i.Spend,
		&i.Atbs,
		&i.Orders,
		&i.Cpc,
		&i.Cpm,
		&i.AvgPos,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestPhraseStat = `-- name: GetLatestPhraseStat :one
SELECT id, phrase_id, date, impressions, clicks, spend, atbs, orders, cpc, cpm, avg_pos, created_at, updated_at FROM phrase_stats
WHERE phrase_id = $1
ORDER BY date DESC
LIMIT 1
`

func (q *Queries) GetLatestPhraseStat(ctx context.Context, phraseID pgtype.UUID) (PhraseStat, error) {
	row := q.db.QueryRow(ctx, getLatestPhraseStat, phraseID)
	var i PhraseStat
	err := row.Scan(
		&i.ID,
		&i.PhraseID,
		&i.Date,
		&i.Impressions,
		&i.Clicks,
		&i.Spend,
		&i.Atbs,
		&i.Orders,
		&i.Cpc,
		&i.Cpm,
		&i.AvgPos,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPhraseStatsByDateRange = `-- name: GetPhraseStatsByDateRange :many
SELECT id, phrase_id, date, impressions, clicks, spend, atbs, orders, cpc, cpm, avg_pos, created_at, updated_at FROM phrase_stats
WHERE phrase_id = $1 AND date BETWEEN $2 AND $3
ORDER BY date
LIMIT $4 OFFSET $5
`

type GetPhraseStatsByDateRangeParams struct {
	PhraseID pgtype.UUID `json:"phrase_id"`
	Date     pgtype.Date `json:"date"`
	Date_2   pgtype.Date `json:"date_2"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) GetPhraseStatsByDateRange(ctx context.Context, arg GetPhraseStatsByDateRangeParams) ([]PhraseStat, error) {
	rows, err := q.db.Query(ctx, getPhraseStatsByDateRange,
		arg.PhraseID,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PhraseStat{}
	for rows.Next() {
		var i PhraseStat
		if err := rows.Scan(
			&i.ID,
			&i.PhraseID,
			&i.Date,
			&i.Impressions,
			&i.Clicks,
			&i.Spend,
			&i.Atbs,
			&i.Orders,
			&i.Cpc,
			&i.Cpm,
			&i.AvgPos,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhraseStatsByWorkspace = `-- name: ListPhraseStatsByWorkspace :many
SELECT ps.id, ps.phrase_id, ps.date, ps.impressions, ps.clicks, ps.spend, ps.atbs, ps.orders, ps.cpc, ps.cpm, ps.avg_pos, ps.created_at, ps.updated_at FROM phrase_stats ps
JOIN phrases p ON p.id = ps.phrase_id
WHERE p.workspace_id = $1
ORDER BY ps.date DESC
LIMIT $2 OFFSET $3
`

type ListPhraseStatsByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) ListPhraseStatsByWorkspace(ctx context.Context, arg ListPhraseStatsByWorkspaceParams) ([]PhraseStat, error) {
	rows, err := q.db.Query(ctx, listPhraseStatsByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PhraseStat{}
	for rows.Next() {
		var i PhraseStat
		if err := rows.Scan(
			&i.ID,
			&i.PhraseID,
			&i.Date,
			&i.Impressions,
			&i.Clicks,
			&i.Spend,
			&i.Atbs,
			&i.Orders,
			&i.Cpc,
			&i.Cpm,
			&i.AvgPos,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPhraseStat = `-- name: UpsertPhraseStat :one
INSERT INTO phrase_stats (phrase_id, date, impressions, clicks, spend, atbs, orders, cpc, cpm, avg_pos)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (phrase_id, date) DO UPDATE SET
    impressions = EXCLUDED.impressions,
    clicks = EXCLUDED.clicks,
    spend = EXCLUDED.spend,
    atbs = EXCLUDED.atbs,
    orders = EXCLUDED.orders,
    cpc = EXCLUDED.cpc,
    cpm = EXCLUDED.cpm,
    avg_pos = EXCLUDED.avg_pos,
    updated_at = now()
RETURNING id, phrase_id, date, impressions, clicks, spend, atbs, orders, cpc, cpm, avg_pos, created_at, updated_at
`

type UpsertPhraseStatParams struct {
	PhraseID    pgtype.UUID   `json:"phrase_id"`
	Date        pgtype.Date   `json:"date"`
	Impressions int64         `json:"impressions"`
	Clicks      int64         `json:"clicks"`
	Spend       int64         `json:"spend"`
	Atbs        pgtype.Int8   `json:"atbs"`
	Orders      pgtype.Int8   `json:"orders"`
	Cpc         pgtype.Float8 `json:"cpc"`
	Cpm         pgtype.Float8 `json:"cpm"`
	AvgPos      pgtype.Float8 `json:"avg_pos"`
}

func (q *Queries) UpsertPhraseStat(ctx context.Context, arg UpsertPhraseStatParams) (PhraseStat, error) {
	row := q.db.QueryRow(ctx, upsertPhraseStat,
		arg.PhraseID,
		arg.Date,
		arg.Impressions,
		arg.Clicks,
		arg.Spend,
		arg.Atbs,
		arg.Orders,
		arg.Cpc,
		arg.Cpm,
		arg.AvgPos,
	)
	var i PhraseStat
	err := row.Scan(
		&i.ID,
		&i.PhraseID,
		&i.Date,
		&i.Impressions,
		&i.Clicks,
		&i.Spend,
		&i.Atbs,
		&i.Orders,
		&i.Cpc,
		&i.Cpm,
		&i.AvgPos,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
