// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: positions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPosition = `-- name: CreatePosition :one
INSERT INTO positions (workspace_id, product_id, query, region, position, page, source, checked_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, workspace_id, product_id, query, region, position, page, source, checked_at, created_at
`

type CreatePositionParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ProductID   pgtype.UUID        `json:"product_id"`
	Query       string             `json:"query"`
	Region      string             `json:"region"`
	Position    int32              `json:"position"`
	Page        int32              `json:"page"`
	Source      string             `json:"source"`
	CheckedAt   pgtype.Timestamptz `json:"checked_at"`
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, createPosition,
		arg.WorkspaceID,
		arg.ProductID,
		arg.Query,
		arg.Region,
		arg.Position,
		arg.Page,
		arg.Source,
		arg.CheckedAt,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProductID,
		&i.Query,
		&i.Region,
		&i.Position,
		&i.Page,
		&i.Source,
		&i.CheckedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAveragePosition = `-- name: GetAveragePosition :one
SELECT COALESCE(AVG(position)::float8, 0) AS avg_position FROM positions
WHERE product_id = $1 AND query = $2 AND region = $3
  AND checked_at BETWEEN $4 AND $5
`

type GetAveragePositionParams struct {
	ProductID   pgtype.UUID        `json:"product_id"`
	Query       string             `json:"query"`
	Region      string             `json:"region"`
	CheckedAt   pgtype.Timestamptz `json:"checked_at"`
	CheckedAt_2 pgtype.Timestamptz `json:"checked_at_2"`
}

func (q *Queries) GetAveragePosition(ctx context.Context, arg GetAveragePositionParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getAveragePosition,
		arg.ProductID,
		arg.Query,
		arg.Region,
		arg.CheckedAt,
		arg.CheckedAt_2,
	)
	var avg_position interface{}
	err := row.Scan(&avg_position)
	return avg_position, err
}

const listPositionsByProduct = `-- name: ListPositionsByProduct :many
SELECT id, workspace_id, product_id, query, region, position, page, source, checked_at, created_at FROM positions
WHERE product_id = $1
ORDER BY checked_at DESC
LIMIT $2 OFFSET $3
`

type ListPositionsByProductParams struct {
	ProductID pgtype.UUID `json:"product_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListPositionsByProduct(ctx context.Context, arg ListPositionsByProductParams) ([]Position, error) {
	rows, err := q.db.Query(ctx, listPositionsByProduct, arg.ProductID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Position{}
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProductID,
			&i.Query,
			&i.Region,
			&i.Position,
			&i.Page,
			&i.Source,
			&i.CheckedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositionsByWorkspace = `-- name: ListPositionsByWorkspace :many
SELECT id, workspace_id, product_id, query, region, position, page, source, checked_at, created_at FROM positions
WHERE workspace_id = $1
ORDER BY checked_at DESC
LIMIT $2 OFFSET $3
`

type ListPositionsByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) ListPositionsByWorkspace(ctx context.Context, arg ListPositionsByWorkspaceParams) ([]Position, error) {
	rows, err := q.db.Query(ctx, listPositionsByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Position{}
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProductID,
			&i.Query,
			&i.Region,
			&i.Position,
			&i.Page,
			&i.Source,
			&i.CheckedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositionsFiltered = `-- name: ListPositionsFiltered :many
SELECT id, workspace_id, product_id, query, region, position, page, source, checked_at, created_at FROM positions
WHERE workspace_id = $1
  AND ($4::uuid IS NULL OR product_id = $4::uuid)
  AND ($5::text IS NULL OR query = $5::text)
  AND ($6::text IS NULL OR region = $6::text)
  AND ($7::timestamptz IS NULL OR checked_at >= $7::timestamptz)
  AND ($8::timestamptz IS NULL OR checked_at <= $8::timestamptz)
ORDER BY checked_at DESC
LIMIT $2 OFFSET $3
`

type ListPositionsFilteredParams struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	Limit           int32              `json:"limit"`
	Offset          int32              `json:"offset"`
	ProductIDFilter pgtype.UUID        `json:"product_id_filter"`
	QueryFilter     pgtype.Text        `json:"query_filter"`
	RegionFilter    pgtype.Text        `json:"region_filter"`
	DateFrom        pgtype.Timestamptz `json:"date_from"`
	DateTo          pgtype.Timestamptz `json:"date_to"`
}

func (q *Queries) ListPositionsFiltered(ctx context.Context, arg ListPositionsFilteredParams) ([]Position, error) {
	rows, err := q.db.Query(ctx, listPositionsFiltered,
		arg.WorkspaceID,
		arg.Limit,
		arg.Offset,
		arg.ProductIDFilter,
		arg.QueryFilter,
		arg.RegionFilter,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Position{}
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProductID,
			&i.Query,
			&i.Region,
			&i.Position,
			&i.Page,
			&i.Source,
			&i.CheckedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
