// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: products.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (workspace_id, seller_cabinet_id, wb_product_id, title, brand, category, image_url, price)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, workspace_id, seller_cabinet_id, wb_product_id, title, brand, category, image_url, price, created_at, updated_at
`

type CreateProductParams struct {
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	WbProductID     int64       `json:"wb_product_id"`
	Title           string      `json:"title"`
	Brand           pgtype.Text `json:"brand"`
	Category        pgtype.Text `json:"category"`
	ImageUrl        pgtype.Text `json:"image_url"`
	Price           pgtype.Int8 `json:"price"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.WorkspaceID,
		arg.SellerCabinetID,
		arg.WbProductID,
		arg.Title,
		arg.Brand,
		arg.Category,
		arg.ImageUrl,
		arg.Price,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SellerCabinetID,
		&i.WbProductID,
		&i.Title,
		&i.Brand,
		&i.Category,
		&i.ImageUrl,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, workspace_id, seller_cabinet_id, wb_product_id, title, brand, category, image_url, price, created_at, updated_at FROM products WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SellerCabinetID,
		&i.WbProductID,
		&i.Title,
		&i.Brand,
		&i.Category,
		&i.ImageUrl,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByWBProductID = `-- name: GetProductByWBProductID :one
SELECT id, workspace_id, seller_cabinet_id, wb_product_id, title, brand, category, image_url, price, created_at, updated_at FROM products
WHERE workspace_id = $1 AND wb_product_id = $2
LIMIT 1
`

type GetProductByWBProductIDParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	WbProductID int64       `json:"wb_product_id"`
}

func (q *Queries) GetProductByWBProductID(ctx context.Context, arg GetProductByWBProductIDParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByWBProductID, arg.WorkspaceID, arg.WbProductID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SellerCabinetID,
		&i.WbProductID,
		&i.Title,
		&i.Brand,
		&i.Category,
		&i.ImageUrl,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductsBySellerCabinet = `-- name: ListProductsBySellerCabinet :many
SELECT id, workspace_id, seller_cabinet_id, wb_product_id, title, brand, category, image_url, price, created_at, updated_at FROM products
WHERE seller_cabinet_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductsBySellerCabinetParams struct {
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Limit           int32       `json:"limit"`
	Offset          int32       `json:"offset"`
}

func (q *Queries) ListProductsBySellerCabinet(ctx context.Context, arg ListProductsBySellerCabinetParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsBySellerCabinet, arg.SellerCabinetID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SellerCabinetID,
			&i.WbProductID,
			&i.Title,
			&i.Brand,
			&i.Category,
			&i.ImageUrl,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByWorkspace = `-- name: ListProductsByWorkspace :many
SELECT id, workspace_id, seller_cabinet_id, wb_product_id, title, brand, category, image_url, price, created_at, updated_at FROM products
WHERE workspace_id = $1
  AND ($4::uuid IS NULL OR seller_cabinet_id = $4::uuid)
  AND ($5::text IS NULL OR title ILIKE '%' || $5::text || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductsByWorkspaceParams struct {
	WorkspaceID           pgtype.UUID `json:"workspace_id"`
	Limit                 int32       `json:"limit"`
	Offset                int32       `json:"offset"`
	SellerCabinetIDFilter pgtype.UUID `json:"seller_cabinet_id_filter"`
	TitleFilter           pgtype.Text `json:"title_filter"`
}

func (q *Queries) ListProductsByWorkspace(ctx context.Context, arg ListProductsByWorkspaceParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByWorkspace,
		arg.WorkspaceID,
		arg.Limit,
		arg.Offset,
		arg.SellerCabinetIDFilter,
		arg.TitleFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SellerCabinetID,
			&i.WbProductID,
			&i.Title,
			&i.Brand,
			&i.Category,
			&i.ImageUrl,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProduct = `-- name: UpsertProduct :one
INSERT INTO products (workspace_id, seller_cabinet_id, wb_product_id, title, brand, category, image_url, price)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (wb_product_id, seller_cabinet_id) DO UPDATE SET
    title = EXCLUDED.title,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    image_url = EXCLUDED.image_url,
    price = EXCLUDED.price,
    updated_at = now()
RETURNING id, workspace_id, seller_cabinet_id, wb_product_id, title, brand, category, image_url, price, created_at, updated_at
`

type UpsertProductParams struct {
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	WbProductID     int64       `json:"wb_product_id"`
	Title           string      `json:"title"`
	Brand           pgtype.Text `json:"brand"`
	Category        pgtype.Text `json:"category"`
	ImageUrl        pgtype.Text `json:"image_url"`
	Price           pgtype.Int8 `json:"price"`
}

func (q *Queries) UpsertProduct(ctx context.Context, arg UpsertProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, upsertProduct,
		arg.WorkspaceID,
		arg.SellerCabinetID,
		arg.WbProductID,
		arg.Title,
		arg.Brand,
		arg.Category,
		arg.ImageUrl,
		arg.Price,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SellerCabinetID,
		&i.WbProductID,
		&i.Title,
		&i.Brand,
		&i.Category,
		&i.ImageUrl,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
