// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BatchCreateSERPResultItems(ctx context.Context, arg []BatchCreateSERPResultItemsParams) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateBidSnapshot(ctx context.Context, arg CreateBidSnapshotParams) (BidSnapshot, error)
	CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error)
	CreateCampaignStat(ctx context.Context, arg CreateCampaignStatParams) (CampaignStat, error)
	CreateExport(ctx context.Context, arg CreateExportParams) (Export, error)
	CreateExtensionContextEvent(ctx context.Context, arg CreateExtensionContextEventParams) (ExtensionContextEvent, error)
	CreateExtensionSession(ctx context.Context, arg CreateExtensionSessionParams) (ExtensionSession, error)
	CreateJobRun(ctx context.Context, arg CreateJobRunParams) (JobRun, error)
	CreatePhrase(ctx context.Context, arg CreatePhraseParams) (Phrase, error)
	CreatePhraseStat(ctx context.Context, arg CreatePhraseStatParams) (PhraseStat, error)
	CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateRecommendation(ctx context.Context, arg CreateRecommendationParams) (Recommendation, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateSERPResultItem(ctx context.Context, arg CreateSERPResultItemParams) (SerpResultItem, error)
	CreateSERPSnapshot(ctx context.Context, arg CreateSERPSnapshotParams) (SerpSnapshot, error)
	CreateSellerCabinet(ctx context.Context, arg CreateSellerCabinetParams) (SellerCabinet, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	CreateWorkspaceMember(ctx context.Context, arg CreateWorkspaceMemberParams) (WorkspaceMember, error)
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteWorkspaceMember(ctx context.Context, id pgtype.UUID) error
	GetActiveRecommendation(ctx context.Context, arg GetActiveRecommendationParams) (Recommendation, error)
	GetAveragePosition(ctx context.Context, arg GetAveragePositionParams) (interface{}, error)
	GetCampaignByID(ctx context.Context, id pgtype.UUID) (Campaign, error)
	GetCampaignStatsByDateRange(ctx context.Context, arg GetCampaignStatsByDateRangeParams) ([]CampaignStat, error)
	GetExportByID(ctx context.Context, id pgtype.UUID) (Export, error)
	GetExtensionSession(ctx context.Context, arg GetExtensionSessionParams) (ExtensionSession, error)
	GetJobRunByID(ctx context.Context, id pgtype.UUID) (JobRun, error)
	GetLatestBidSnapshot(ctx context.Context, phraseID pgtype.UUID) (BidSnapshot, error)
	GetLatestCampaignStat(ctx context.Context, campaignID pgtype.UUID) (CampaignStat, error)
	GetLatestPhraseStat(ctx context.Context, phraseID pgtype.UUID) (PhraseStat, error)
	GetPhraseByID(ctx context.Context, id pgtype.UUID) (Phrase, error)
	GetPhraseStatsByDateRange(ctx context.Context, arg GetPhraseStatsByDateRangeParams) ([]PhraseStat, error)
	GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error)
	GetRecommendationByID(ctx context.Context, id pgtype.UUID) (Recommendation, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetSERPSnapshotByID(ctx context.Context, id pgtype.UUID) (SerpSnapshot, error)
	GetSellerCabinetByID(ctx context.Context, id pgtype.UUID) (SellerCabinet, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetWorkspaceByID(ctx context.Context, id pgtype.UUID) (Workspace, error)
	GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error)
	GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error)
	GetWorkspaceMemberByID(ctx context.Context, id pgtype.UUID) (WorkspaceMember, error)
	ListActiveSellerCabinets(ctx context.Context) ([]SellerCabinet, error)
	ListActiveSellerCabinetsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]SellerCabinet, error)
	ListAuditLogsByWorkspace(ctx context.Context, arg ListAuditLogsByWorkspaceParams) ([]AuditLog, error)
	ListAuditLogsFiltered(ctx context.Context, arg ListAuditLogsFilteredParams) ([]AuditLog, error)
	ListBidSnapshotsByPhrase(ctx context.Context, arg ListBidSnapshotsByPhraseParams) ([]BidSnapshot, error)
	ListBidSnapshotsByWorkspace(ctx context.Context, arg ListBidSnapshotsByWorkspaceParams) ([]BidSnapshot, error)
	ListCampaignStatsByWorkspace(ctx context.Context, arg ListCampaignStatsByWorkspaceParams) ([]CampaignStat, error)
	ListCampaignsBySellerCabinet(ctx context.Context, arg ListCampaignsBySellerCabinetParams) ([]Campaign, error)
	ListCampaignsByWorkspace(ctx context.Context, arg ListCampaignsByWorkspaceParams) ([]Campaign, error)
	ListExportsByWorkspace(ctx context.Context, arg ListExportsByWorkspaceParams) ([]Export, error)
	ListJobRunsByTaskType(ctx context.Context, arg ListJobRunsByTaskTypeParams) ([]JobRun, error)
	ListJobRunsByWorkspace(ctx context.Context, arg ListJobRunsByWorkspaceParams) ([]JobRun, error)
	ListPhraseStatsByWorkspace(ctx context.Context, arg ListPhraseStatsByWorkspaceParams) ([]PhraseStat, error)
	ListPhrasesByCampaign(ctx context.Context, arg ListPhrasesByCampaignParams) ([]Phrase, error)
	ListPhrasesByWorkspace(ctx context.Context, arg ListPhrasesByWorkspaceParams) ([]Phrase, error)
	ListPositionsByProduct(ctx context.Context, arg ListPositionsByProductParams) ([]Position, error)
	ListPositionsByWorkspace(ctx context.Context, arg ListPositionsByWorkspaceParams) ([]Position, error)
	ListPositionsFiltered(ctx context.Context, arg ListPositionsFilteredParams) ([]Position, error)
	ListProductsBySellerCabinet(ctx context.Context, arg ListProductsBySellerCabinetParams) ([]Product, error)
	ListProductsByWorkspace(ctx context.Context, arg ListProductsByWorkspaceParams) ([]Product, error)
	ListRecommendationsByWorkspace(ctx context.Context, arg ListRecommendationsByWorkspaceParams) ([]Recommendation, error)
	ListSERPResultItemsBySnapshot(ctx context.Context, snapshotID pgtype.UUID) ([]SerpResultItem, error)
	ListSERPSnapshotsByWorkspace(ctx context.Context, arg ListSERPSnapshotsByWorkspaceParams) ([]SerpSnapshot, error)
	ListSERPSnapshotsFiltered(ctx context.Context, arg ListSERPSnapshotsFilteredParams) ([]SerpSnapshot, error)
	ListSellerCabinetsByWorkspace(ctx context.Context, arg ListSellerCabinetsByWorkspaceParams) ([]SellerCabinet, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListWorkspaceMembers(ctx context.Context, arg ListWorkspaceMembersParams) ([]WorkspaceMember, error)
	ListWorkspaces(ctx context.Context, arg ListWorkspacesParams) ([]Workspace, error)
	ListWorkspacesByUserID(ctx context.Context, arg ListWorkspacesByUserIDParams) ([]Workspace, error)
	RevokeAllUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error
	SoftDeleteSellerCabinet(ctx context.Context, id pgtype.UUID) error
	SoftDeleteWorkspace(ctx context.Context, id pgtype.UUID) error
	UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error)
	UpdateExportStatus(ctx context.Context, arg UpdateExportStatusParams) (Export, error)
	UpdateExtensionSession(ctx context.Context, arg UpdateExtensionSessionParams) (ExtensionSession, error)
	UpdateExtensionSessionActivity(ctx context.Context, id pgtype.UUID) error
	UpdateJobRunStatus(ctx context.Context, arg UpdateJobRunStatusParams) (JobRun, error)
	UpdateRecommendationContent(ctx context.Context, arg UpdateRecommendationContentParams) (Recommendation, error)
	UpdateRecommendationStatus(ctx context.Context, arg UpdateRecommendationStatusParams) (Recommendation, error)
	UpdateSellerCabinetLastSynced(ctx context.Context, id pgtype.UUID) error
	UpdateSellerCabinetStatus(ctx context.Context, arg UpdateSellerCabinetStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
	UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) (WorkspaceMember, error)
	UpsertCampaign(ctx context.Context, arg UpsertCampaignParams) (Campaign, error)
	UpsertCampaignStat(ctx context.Context, arg UpsertCampaignStatParams) (CampaignStat, error)
	UpsertPhrase(ctx context.Context, arg UpsertPhraseParams) (Phrase, error)
	UpsertPhraseStat(ctx context.Context, arg UpsertPhraseStatParams) (PhraseStat, error)
	UpsertProduct(ctx context.Context, arg UpsertProductParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
