// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seller_cabinets.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSellerCabinet = `-- name: CreateSellerCabinet :one
INSERT INTO seller_cabinets (workspace_id, name, encrypted_token)
VALUES ($1, $2, $3)
RETURNING id, workspace_id, name, encrypted_token, status, last_synced_at, created_at, updated_at, deleted_at
`

type CreateSellerCabinetParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	Name           string      `json:"name"`
	EncryptedToken string      `json:"encrypted_token"`
}

func (q *Queries) CreateSellerCabinet(ctx context.Context, arg CreateSellerCabinetParams) (SellerCabinet, error) {
	row := q.db.QueryRow(ctx, createSellerCabinet, arg.WorkspaceID, arg.Name, arg.EncryptedToken)
	var i SellerCabinet
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.EncryptedToken,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSellerCabinetByID = `-- name: GetSellerCabinetByID :one
SELECT id, workspace_id, name, encrypted_token, status, last_synced_at, created_at, updated_at, deleted_at FROM seller_cabinets
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSellerCabinetByID(ctx context.Context, id pgtype.UUID) (SellerCabinet, error) {
	row := q.db.QueryRow(ctx, getSellerCabinetByID, id)
	var i SellerCabinet
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.EncryptedToken,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveSellerCabinets = `-- name: ListActiveSellerCabinets :many
SELECT id, workspace_id, name, encrypted_token, status, last_synced_at, created_at, updated_at, deleted_at FROM seller_cabinets
WHERE status = 'active' AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListActiveSellerCabinets(ctx context.Context) ([]SellerCabinet, error) {
	rows, err := q.db.Query(ctx, listActiveSellerCabinets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SellerCabinet{}
	for rows.Next() {
		var i SellerCabinet
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.EncryptedToken,
			&i.Status,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSellerCabinetsByWorkspace = `-- name: ListActiveSellerCabinetsByWorkspace :many
SELECT id, workspace_id, name, encrypted_token, status, last_synced_at, created_at, updated_at, deleted_at FROM seller_cabinets
WHERE workspace_id = $1 AND status = 'active' AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListActiveSellerCabinetsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]SellerCabinet, error) {
	rows, err := q.db.Query(ctx, listActiveSellerCabinetsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SellerCabinet{}
	for rows.Next() {
		var i SellerCabinet
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.EncryptedToken,
			&i.Status,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSellerCabinetsByWorkspace = `-- name: ListSellerCabinetsByWorkspace :many
SELECT id, workspace_id, name, encrypted_token, status, last_synced_at, created_at, updated_at, deleted_at FROM seller_cabinets
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSellerCabinetsByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) ListSellerCabinetsByWorkspace(ctx context.Context, arg ListSellerCabinetsByWorkspaceParams) ([]SellerCabinet, error) {
	rows, err := q.db.Query(ctx, listSellerCabinetsByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SellerCabinet{}
	for rows.Next() {
		var i SellerCabinet
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.EncryptedToken,
			&i.Status,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSellerCabinet = `-- name: SoftDeleteSellerCabinet :exec
UPDATE seller_cabinets
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteSellerCabinet(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteSellerCabinet, id)
	return err
}

const updateSellerCabinetLastSynced = `-- name: UpdateSellerCabinetLastSynced :exec
UPDATE seller_cabinets
SET last_synced_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateSellerCabinetLastSynced(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateSellerCabinetLastSynced, id)
	return err
}

const updateSellerCabinetStatus = `-- name: UpdateSellerCabinetStatus :exec
UPDATE seller_cabinets
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateSellerCabinetStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateSellerCabinetStatus(ctx context.Context, arg UpdateSellerCabinetStatusParams) error {
	_, err := q.db.Exec(ctx, updateSellerCabinetStatus, arg.ID, arg.Status)
	return err
}
