// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: seller_cabinets.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSellerCabinet = `-- name: CreateSellerCabinet :one
INSERT INTO seller_cabinets (workspace_id, name, encrypted_token)
VALUES ($1, $2, $3)
RETURNING id, workspace_id, name, encrypted_token, status, last_synced_at, created_at, updated_at, deleted_at, external_integration_id, source, integration_type, last_sellico_sync_at
`

type CreateSellerCabinetParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	Name           string      `json:"name"`
	EncryptedToken string      `json:"encrypted_token"`
}

func (q *Queries) CreateSellerCabinet(ctx context.Context, arg CreateSellerCabinetParams) (SellerCabinet, error) {
	row := q.db.QueryRow(ctx, createSellerCabinet, arg.WorkspaceID, arg.Name, arg.EncryptedToken)
	var i SellerCabinet
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.EncryptedToken,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExternalIntegrationID,
		&i.Source,
		&i.IntegrationType,
		&i.LastSellicoSyncAt,
	)
	return i, err
}

const getSellerCabinetByExternalIntegrationID = `-- name: GetSellerCabinetByExternalIntegrationID :one
SELECT id, workspace_id, name, encrypted_token, status, last_synced_at, created_at, updated_at, deleted_at, external_integration_id, source, integration_type, last_sellico_sync_at FROM seller_cabinets
WHERE external_integration_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSellerCabinetByExternalIntegrationID(ctx context.Context, externalIntegrationID pgtype.Text) (SellerCabinet, error) {
	row := q.db.QueryRow(ctx, getSellerCabinetByExternalIntegrationID, externalIntegrationID)
	var i SellerCabinet
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.EncryptedToken,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExternalIntegrationID,
		&i.Source,
		&i.IntegrationType,
		&i.LastSellicoSyncAt,
	)
	return i, err
}

const getSellerCabinetByID = `-- name: GetSellerCabinetByID :one
SELECT id, workspace_id, name, encrypted_token, status, last_synced_at, created_at, updated_at, deleted_at, external_integration_id, source, integration_type, last_sellico_sync_at FROM seller_cabinets
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSellerCabinetByID(ctx context.Context, id pgtype.UUID) (SellerCabinet, error) {
	row := q.db.QueryRow(ctx, getSellerCabinetByID, id)
	var i SellerCabinet
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.EncryptedToken,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExternalIntegrationID,
		&i.Source,
		&i.IntegrationType,
		&i.LastSellicoSyncAt,
	)
	return i, err
}

const listActiveSellerCabinets = `-- name: ListActiveSellerCabinets :many
SELECT id, workspace_id, name, encrypted_token, status, last_synced_at, created_at, updated_at, deleted_at, external_integration_id, source, integration_type, last_sellico_sync_at FROM seller_cabinets
WHERE status = 'active' AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListActiveSellerCabinets(ctx context.Context) ([]SellerCabinet, error) {
	rows, err := q.db.Query(ctx, listActiveSellerCabinets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SellerCabinet{}
	for rows.Next() {
		var i SellerCabinet
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.EncryptedToken,
			&i.Status,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ExternalIntegrationID,
			&i.Source,
			&i.IntegrationType,
			&i.LastSellicoSyncAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSellerCabinetsByWorkspace = `-- name: ListActiveSellerCabinetsByWorkspace :many
SELECT id, workspace_id, name, encrypted_token, status, last_synced_at, created_at, updated_at, deleted_at, external_integration_id, source, integration_type, last_sellico_sync_at FROM seller_cabinets
WHERE workspace_id = $1 AND status = 'active' AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListActiveSellerCabinetsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]SellerCabinet, error) {
	rows, err := q.db.Query(ctx, listActiveSellerCabinetsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SellerCabinet{}
	for rows.Next() {
		var i SellerCabinet
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.EncryptedToken,
			&i.Status,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ExternalIntegrationID,
			&i.Source,
			&i.IntegrationType,
			&i.LastSellicoSyncAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSellerCabinetsByWorkspace = `-- name: ListSellerCabinetsByWorkspace :many
SELECT id, workspace_id, name, encrypted_token, status, last_synced_at, created_at, updated_at, deleted_at, external_integration_id, source, integration_type, last_sellico_sync_at FROM seller_cabinets
WHERE workspace_id = $1 AND deleted_at IS NULL
  AND ($4::text IS NULL OR status = $4::text)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSellerCabinetsByWorkspaceParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
	StatusFilter pgtype.Text `json:"status_filter"`
}

func (q *Queries) ListSellerCabinetsByWorkspace(ctx context.Context, arg ListSellerCabinetsByWorkspaceParams) ([]SellerCabinet, error) {
	rows, err := q.db.Query(ctx, listSellerCabinetsByWorkspace,
		arg.WorkspaceID,
		arg.Limit,
		arg.Offset,
		arg.StatusFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SellerCabinet{}
	for rows.Next() {
		var i SellerCabinet
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.EncryptedToken,
			&i.Status,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ExternalIntegrationID,
			&i.Source,
			&i.IntegrationType,
			&i.LastSellicoSyncAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSellerCabinet = `-- name: SoftDeleteSellerCabinet :exec
UPDATE seller_cabinets
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteSellerCabinet(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteSellerCabinet, id)
	return err
}

const updateSellerCabinetLastSynced = `-- name: UpdateSellerCabinetLastSynced :exec
UPDATE seller_cabinets
SET last_synced_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateSellerCabinetLastSynced(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateSellerCabinetLastSynced, id)
	return err
}

const updateSellerCabinetStatus = `-- name: UpdateSellerCabinetStatus :exec
UPDATE seller_cabinets
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateSellerCabinetStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateSellerCabinetStatus(ctx context.Context, arg UpdateSellerCabinetStatusParams) error {
	_, err := q.db.Exec(ctx, updateSellerCabinetStatus, arg.ID, arg.Status)
	return err
}

const updateSellerCabinetTokenCache = `-- name: UpdateSellerCabinetTokenCache :exec
UPDATE seller_cabinets
SET encrypted_token = $2,
    status = $3,
    source = 'sellico',
    integration_type = $4,
    last_sellico_sync_at = now(),
    updated_at = now()
WHERE id = $1
`

type UpdateSellerCabinetTokenCacheParams struct {
	ID              pgtype.UUID `json:"id"`
	EncryptedToken  string      `json:"encrypted_token"`
	Status          string      `json:"status"`
	IntegrationType pgtype.Text `json:"integration_type"`
}

func (q *Queries) UpdateSellerCabinetTokenCache(ctx context.Context, arg UpdateSellerCabinetTokenCacheParams) error {
	_, err := q.db.Exec(ctx, updateSellerCabinetTokenCache,
		arg.ID,
		arg.EncryptedToken,
		arg.Status,
		arg.IntegrationType,
	)
	return err
}

const upsertSellicoSellerCabinet = `-- name: UpsertSellicoSellerCabinet :one
INSERT INTO seller_cabinets (
    workspace_id,
    name,
    encrypted_token,
    status,
    external_integration_id,
    source,
    integration_type,
    last_sellico_sync_at
)
VALUES ($1, $2, $3, $4, $5, 'sellico', $6, now())
ON CONFLICT (external_integration_id) DO UPDATE SET
    workspace_id = EXCLUDED.workspace_id,
    name = EXCLUDED.name,
    encrypted_token = EXCLUDED.encrypted_token,
    status = EXCLUDED.status,
    source = EXCLUDED.source,
    integration_type = EXCLUDED.integration_type,
    last_sellico_sync_at = now(),
    deleted_at = NULL,
    updated_at = now()
RETURNING id, workspace_id, name, encrypted_token, status, last_synced_at, created_at, updated_at, deleted_at, external_integration_id, source, integration_type, last_sellico_sync_at
`

type UpsertSellicoSellerCabinetParams struct {
	WorkspaceID           pgtype.UUID `json:"workspace_id"`
	Name                  string      `json:"name"`
	EncryptedToken        string      `json:"encrypted_token"`
	Status                string      `json:"status"`
	ExternalIntegrationID pgtype.Text `json:"external_integration_id"`
	IntegrationType       pgtype.Text `json:"integration_type"`
}

func (q *Queries) UpsertSellicoSellerCabinet(ctx context.Context, arg UpsertSellicoSellerCabinetParams) (SellerCabinet, error) {
	row := q.db.QueryRow(ctx, upsertSellicoSellerCabinet,
		arg.WorkspaceID,
		arg.Name,
		arg.EncryptedToken,
		arg.Status,
		arg.ExternalIntegrationID,
		arg.IntegrationType,
	)
	var i SellerCabinet
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.EncryptedToken,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExternalIntegrationID,
		&i.Source,
		&i.IntegrationType,
		&i.LastSellicoSyncAt,
	)
	return i, err
}
