// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: serp_snapshots.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSERPSnapshot = `-- name: CreateSERPSnapshot :one
INSERT INTO serp_snapshots (workspace_id, query, region, total_results, scanned_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, query, region, total_results, scanned_at, created_at
`

type CreateSERPSnapshotParams struct {
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	Query        string             `json:"query"`
	Region       string             `json:"region"`
	TotalResults int32              `json:"total_results"`
	ScannedAt    pgtype.Timestamptz `json:"scanned_at"`
}

func (q *Queries) CreateSERPSnapshot(ctx context.Context, arg CreateSERPSnapshotParams) (SerpSnapshot, error) {
	row := q.db.QueryRow(ctx, createSERPSnapshot,
		arg.WorkspaceID,
		arg.Query,
		arg.Region,
		arg.TotalResults,
		arg.ScannedAt,
	)
	var i SerpSnapshot
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Query,
		&i.Region,
		&i.TotalResults,
		&i.ScannedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSERPSnapshotByID = `-- name: GetSERPSnapshotByID :one
SELECT id, workspace_id, query, region, total_results, scanned_at, created_at FROM serp_snapshots WHERE id = $1
`

func (q *Queries) GetSERPSnapshotByID(ctx context.Context, id pgtype.UUID) (SerpSnapshot, error) {
	row := q.db.QueryRow(ctx, getSERPSnapshotByID, id)
	var i SerpSnapshot
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Query,
		&i.Region,
		&i.TotalResults,
		&i.ScannedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listSERPSnapshotsByWorkspace = `-- name: ListSERPSnapshotsByWorkspace :many
SELECT id, workspace_id, query, region, total_results, scanned_at, created_at FROM serp_snapshots
WHERE workspace_id = $1
ORDER BY scanned_at DESC
LIMIT $2 OFFSET $3
`

type ListSERPSnapshotsByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) ListSERPSnapshotsByWorkspace(ctx context.Context, arg ListSERPSnapshotsByWorkspaceParams) ([]SerpSnapshot, error) {
	rows, err := q.db.Query(ctx, listSERPSnapshotsByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SerpSnapshot{}
	for rows.Next() {
		var i SerpSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Query,
			&i.Region,
			&i.TotalResults,
			&i.ScannedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSERPSnapshotsFiltered = `-- name: ListSERPSnapshotsFiltered :many
SELECT id, workspace_id, query, region, total_results, scanned_at, created_at FROM serp_snapshots
WHERE workspace_id = $1
  AND ($4::text IS NULL OR query = $4::text)
  AND ($5::text IS NULL OR region = $5::text)
  AND ($6::timestamptz IS NULL OR scanned_at >= $6::timestamptz)
  AND ($7::timestamptz IS NULL OR scanned_at <= $7::timestamptz)
ORDER BY scanned_at DESC
LIMIT $2 OFFSET $3
`

type ListSERPSnapshotsFilteredParams struct {
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	Limit        int32              `json:"limit"`
	Offset       int32              `json:"offset"`
	QueryFilter  pgtype.Text        `json:"query_filter"`
	RegionFilter pgtype.Text        `json:"region_filter"`
	DateFrom     pgtype.Timestamptz `json:"date_from"`
	DateTo       pgtype.Timestamptz `json:"date_to"`
}

func (q *Queries) ListSERPSnapshotsFiltered(ctx context.Context, arg ListSERPSnapshotsFilteredParams) ([]SerpSnapshot, error) {
	rows, err := q.db.Query(ctx, listSERPSnapshotsFiltered,
		arg.WorkspaceID,
		arg.Limit,
		arg.Offset,
		arg.QueryFilter,
		arg.RegionFilter,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SerpSnapshot{}
	for rows.Next() {
		var i SerpSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Query,
			&i.Region,
			&i.TotalResults,
			&i.ScannedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
