// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: strategies.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBidChange = `-- name: CreateBidChange :one
INSERT INTO bid_changes (
    workspace_id, seller_cabinet_id, campaign_id, product_id, phrase_id,
    strategy_id, recommendation_id, placement, old_bid, new_bid,
    reason, source, acos, roas, wb_status, automation_action_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, workspace_id, seller_cabinet_id, campaign_id, product_id, phrase_id, strategy_id, recommendation_id, placement, old_bid, new_bid, reason, source, acos, roas, wb_status, created_at, automation_action_id
`

type CreateBidChangeParams struct {
	WorkspaceID        pgtype.UUID   `json:"workspace_id"`
	SellerCabinetID    pgtype.UUID   `json:"seller_cabinet_id"`
	CampaignID         pgtype.UUID   `json:"campaign_id"`
	ProductID          pgtype.UUID   `json:"product_id"`
	PhraseID           pgtype.UUID   `json:"phrase_id"`
	StrategyID         pgtype.UUID   `json:"strategy_id"`
	RecommendationID   pgtype.UUID   `json:"recommendation_id"`
	Placement          string        `json:"placement"`
	OldBid             int32         `json:"old_bid"`
	NewBid             int32         `json:"new_bid"`
	Reason             string        `json:"reason"`
	Source             string        `json:"source"`
	Acos               pgtype.Float8 `json:"acos"`
	Roas               pgtype.Float8 `json:"roas"`
	WbStatus           string        `json:"wb_status"`
	AutomationActionID pgtype.UUID   `json:"automation_action_id"`
}

func (q *Queries) CreateBidChange(ctx context.Context, arg CreateBidChangeParams) (BidChange, error) {
	row := q.db.QueryRow(ctx, createBidChange,
		arg.WorkspaceID,
		arg.SellerCabinetID,
		arg.CampaignID,
		arg.ProductID,
		arg.PhraseID,
		arg.StrategyID,
		arg.RecommendationID,
		arg.Placement,
		arg.OldBid,
		arg.NewBid,
		arg.Reason,
		arg.Source,
		arg.Acos,
		arg.Roas,
		arg.WbStatus,
		arg.AutomationActionID,
	)
	var i BidChange
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SellerCabinetID,
		&i.CampaignID,
		&i.ProductID,
		&i.PhraseID,
		&i.StrategyID,
		&i.RecommendationID,
		&i.Placement,
		&i.OldBid,
		&i.NewBid,
		&i.Reason,
		&i.Source,
		&i.Acos,
		&i.Roas,
		&i.WbStatus,
		&i.CreatedAt,
		&i.AutomationActionID,
	)
	return i, err
}

const createMinusPhrase = `-- name: CreateMinusPhrase :one
INSERT INTO campaign_minus_phrases (campaign_id, phrase)
VALUES ($1, $2)
ON CONFLICT (campaign_id, phrase) DO NOTHING
RETURNING id, campaign_id, phrase, created_at
`

type CreateMinusPhraseParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	Phrase     string      `json:"phrase"`
}

func (q *Queries) CreateMinusPhrase(ctx context.Context, arg CreateMinusPhraseParams) (CampaignMinusPhrase, error) {
	row := q.db.QueryRow(ctx, createMinusPhrase, arg.CampaignID, arg.Phrase)
	var i CampaignMinusPhrase
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Phrase,
		&i.CreatedAt,
	)
	return i, err
}

const createPlusPhrase = `-- name: CreatePlusPhrase :one
INSERT INTO campaign_plus_phrases (campaign_id, phrase)
VALUES ($1, $2)
ON CONFLICT (campaign_id, phrase) DO NOTHING
RETURNING id, campaign_id, phrase, created_at
`

type CreatePlusPhraseParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	Phrase     string      `json:"phrase"`
}

func (q *Queries) CreatePlusPhrase(ctx context.Context, arg CreatePlusPhraseParams) (CampaignPlusPhrase, error) {
	row := q.db.QueryRow(ctx, createPlusPhrase, arg.CampaignID, arg.Phrase)
	var i CampaignPlusPhrase
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Phrase,
		&i.CreatedAt,
	)
	return i, err
}

const createStrategy = `-- name: CreateStrategy :one
INSERT INTO strategies (workspace_id, seller_cabinet_id, name, type, params, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, seller_cabinet_id, name, type, params, is_active, created_at, updated_at
`

type CreateStrategyParams struct {
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	SellerCabinetID pgtype.UUID `json:"seller_cabinet_id"`
	Name            string      `json:"name"`
	Type            string      `json:"type"`
	Params          []byte      `json:"params"`
	IsActive        bool        `json:"is_active"`
}

func (q *Queries) CreateStrategy(ctx context.Context, arg CreateStrategyParams) (Strategy, error) {
	row := q.db.QueryRow(ctx, createStrategy,
		arg.WorkspaceID,
		arg.SellerCabinetID,
		arg.Name,
		arg.Type,
		arg.Params,
		arg.IsActive,
	)
	var i Strategy
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SellerCabinetID,
		&i.Name,
		&i.Type,
		&i.Params,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStrategyBinding = `-- name: CreateStrategyBinding :one
INSERT INTO strategy_bindings (strategy_id, campaign_id, product_id)
VALUES ($1, $2, $3)
RETURNING id, strategy_id, campaign_id, product_id, created_at, ozon_campaign_id
`

type CreateStrategyBindingParams struct {
	StrategyID pgtype.UUID `json:"strategy_id"`
	CampaignID pgtype.UUID `json:"campaign_id"`
	ProductID  pgtype.UUID `json:"product_id"`
}

func (q *Queries) CreateStrategyBinding(ctx context.Context, arg CreateStrategyBindingParams) (StrategyBinding, error) {
	row := q.db.QueryRow(ctx, createStrategyBinding, arg.StrategyID, arg.CampaignID, arg.ProductID)
	var i StrategyBinding
	err := row.Scan(
		&i.ID,
		&i.StrategyID,
		&i.CampaignID,
		&i.ProductID,
		&i.CreatedAt,
		&i.OzonCampaignID,
	)
	return i, err
}

const deleteMinusPhrase = `-- name: DeleteMinusPhrase :exec
DELETE FROM campaign_minus_phrases WHERE id = $1
`

func (q *Queries) DeleteMinusPhrase(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMinusPhrase, id)
	return err
}

const deletePlusPhrase = `-- name: DeletePlusPhrase :exec
DELETE FROM campaign_plus_phrases WHERE id = $1
`

func (q *Queries) DeletePlusPhrase(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePlusPhrase, id)
	return err
}

const deleteStrategy = `-- name: DeleteStrategy :exec
DELETE FROM strategies WHERE id = $1
`

func (q *Queries) DeleteStrategy(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStrategy, id)
	return err
}

const deleteStrategyBinding = `-- name: DeleteStrategyBinding :exec
DELETE FROM strategy_bindings WHERE id = $1
`

func (q *Queries) DeleteStrategyBinding(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStrategyBinding, id)
	return err
}

const getStrategyByID = `-- name: GetStrategyByID :one
SELECT id, workspace_id, seller_cabinet_id, name, type, params, is_active, created_at, updated_at FROM strategies WHERE id = $1
`

func (q *Queries) GetStrategyByID(ctx context.Context, id pgtype.UUID) (Strategy, error) {
	row := q.db.QueryRow(ctx, getStrategyByID, id)
	var i Strategy
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SellerCabinetID,
		&i.Name,
		&i.Type,
		&i.Params,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveStrategiesByWorkspace = `-- name: ListActiveStrategiesByWorkspace :many
SELECT id, workspace_id, seller_cabinet_id, name, type, params, is_active, created_at, updated_at FROM strategies
WHERE workspace_id = $1 AND is_active = true
ORDER BY created_at DESC
`

func (q *Queries) ListActiveStrategiesByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]Strategy, error) {
	rows, err := q.db.Query(ctx, listActiveStrategiesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Strategy{}
	for rows.Next() {
		var i Strategy
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SellerCabinetID,
			&i.Name,
			&i.Type,
			&i.Params,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBidChangesByCampaign = `-- name: ListBidChangesByCampaign :many
SELECT id, workspace_id, seller_cabinet_id, campaign_id, product_id, phrase_id, strategy_id, recommendation_id, placement, old_bid, new_bid, reason, source, acos, roas, wb_status, created_at, automation_action_id FROM bid_changes
WHERE campaign_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBidChangesByCampaignParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListBidChangesByCampaign(ctx context.Context, arg ListBidChangesByCampaignParams) ([]BidChange, error) {
	rows, err := q.db.Query(ctx, listBidChangesByCampaign, arg.CampaignID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BidChange{}
	for rows.Next() {
		var i BidChange
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SellerCabinetID,
			&i.CampaignID,
			&i.ProductID,
			&i.PhraseID,
			&i.StrategyID,
			&i.RecommendationID,
			&i.Placement,
			&i.OldBid,
			&i.NewBid,
			&i.Reason,
			&i.Source,
			&i.Acos,
			&i.Roas,
			&i.WbStatus,
			&i.CreatedAt,
			&i.AutomationActionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBidChangesByWorkspace = `-- name: ListBidChangesByWorkspace :many
SELECT id, workspace_id, seller_cabinet_id, campaign_id, product_id, phrase_id, strategy_id, recommendation_id, placement, old_bid, new_bid, reason, source, acos, roas, wb_status, created_at, automation_action_id FROM bid_changes
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBidChangesByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) ListBidChangesByWorkspace(ctx context.Context, arg ListBidChangesByWorkspaceParams) ([]BidChange, error) {
	rows, err := q.db.Query(ctx, listBidChangesByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BidChange{}
	for rows.Next() {
		var i BidChange
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SellerCabinetID,
			&i.CampaignID,
			&i.ProductID,
			&i.PhraseID,
			&i.StrategyID,
			&i.RecommendationID,
			&i.Placement,
			&i.OldBid,
			&i.NewBid,
			&i.Reason,
			&i.Source,
			&i.Acos,
			&i.Roas,
			&i.WbStatus,
			&i.CreatedAt,
			&i.AutomationActionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMinusPhrases = `-- name: ListMinusPhrases :many
SELECT id, campaign_id, phrase, created_at FROM campaign_minus_phrases WHERE campaign_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListMinusPhrases(ctx context.Context, campaignID pgtype.UUID) ([]CampaignMinusPhrase, error) {
	rows, err := q.db.Query(ctx, listMinusPhrases, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignMinusPhrase{}
	for rows.Next() {
		var i CampaignMinusPhrase
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Phrase,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlusPhrases = `-- name: ListPlusPhrases :many
SELECT id, campaign_id, phrase, created_at FROM campaign_plus_phrases WHERE campaign_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPlusPhrases(ctx context.Context, campaignID pgtype.UUID) ([]CampaignPlusPhrase, error) {
	rows, err := q.db.Query(ctx, listPlusPhrases, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignPlusPhrase{}
	for rows.Next() {
		var i CampaignPlusPhrase
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Phrase,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStrategiesByWorkspace = `-- name: ListStrategiesByWorkspace :many
SELECT id, workspace_id, seller_cabinet_id, name, type, params, is_active, created_at, updated_at FROM strategies
WHERE workspace_id = $1
  AND ($4::uuid IS NULL OR seller_cabinet_id = $4::uuid)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListStrategiesByWorkspaceParams struct {
	WorkspaceID           pgtype.UUID `json:"workspace_id"`
	Limit                 int32       `json:"limit"`
	Offset                int32       `json:"offset"`
	SellerCabinetIDFilter pgtype.UUID `json:"seller_cabinet_id_filter"`
}

func (q *Queries) ListStrategiesByWorkspace(ctx context.Context, arg ListStrategiesByWorkspaceParams) ([]Strategy, error) {
	rows, err := q.db.Query(ctx, listStrategiesByWorkspace,
		arg.WorkspaceID,
		arg.Limit,
		arg.Offset,
		arg.SellerCabinetIDFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Strategy{}
	for rows.Next() {
		var i Strategy
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SellerCabinetID,
			&i.Name,
			&i.Type,
			&i.Params,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStrategyBindings = `-- name: ListStrategyBindings :many
SELECT id, strategy_id, campaign_id, product_id, created_at, ozon_campaign_id FROM strategy_bindings WHERE strategy_id = $1
`

func (q *Queries) ListStrategyBindings(ctx context.Context, strategyID pgtype.UUID) ([]StrategyBinding, error) {
	rows, err := q.db.Query(ctx, listStrategyBindings, strategyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StrategyBinding{}
	for rows.Next() {
		var i StrategyBinding
		if err := rows.Scan(
			&i.ID,
			&i.StrategyID,
			&i.CampaignID,
			&i.ProductID,
			&i.CreatedAt,
			&i.OzonCampaignID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStrategy = `-- name: UpdateStrategy :one
UPDATE strategies
SET name = $2, type = $3, params = $4, is_active = $5, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, seller_cabinet_id, name, type, params, is_active, created_at, updated_at
`

type UpdateStrategyParams struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Type     string      `json:"type"`
	Params   []byte      `json:"params"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) UpdateStrategy(ctx context.Context, arg UpdateStrategyParams) (Strategy, error) {
	row := q.db.QueryRow(ctx, updateStrategy,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Params,
		arg.IsActive,
	)
	var i Strategy
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SellerCabinetID,
		&i.Name,
		&i.Type,
		&i.Params,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
