// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workspace_settings.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWorkspaceSettings = `-- name: GetWorkspaceSettings :one
SELECT settings FROM workspaces WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkspaceSettings(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getWorkspaceSettings, id)
	var settings []byte
	err := row.Scan(&settings)
	return settings, err
}

const updateWorkspaceSettings = `-- name: UpdateWorkspaceSettings :one
WITH automation_lock AS MATERIALIZED (
    SELECT pg_advisory_xact_lock(hashtextextended($1::text || ':workspace-daily-bid-actions', 0))
)
UPDATE workspaces w
SET settings = $2, updated_at = now()
FROM automation_lock
WHERE w.id = $1
RETURNING w.id, w.name, w.slug, w.created_at, w.updated_at, w.deleted_at, w.settings
`

type UpdateWorkspaceSettingsParams struct {
	ID       pgtype.UUID `json:"id"`
	Settings []byte      `json:"settings"`
}

type UpdateWorkspaceSettingsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	Settings  []byte             `json:"settings"`
}

func (q *Queries) UpdateWorkspaceSettings(ctx context.Context, arg UpdateWorkspaceSettingsParams) (UpdateWorkspaceSettingsRow, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceSettings, arg.ID, arg.Settings)
	var i UpdateWorkspaceSettingsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Settings,
	)
	return i, err
}
