// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workspaces.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExternalWorkspace = `-- name: CreateExternalWorkspace :one
INSERT INTO workspaces (name, slug, external_workspace_id, source)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, created_at, updated_at, deleted_at, external_workspace_id, source
`

type CreateExternalWorkspaceParams struct {
	Name                string      `json:"name"`
	Slug                string      `json:"slug"`
	ExternalWorkspaceID pgtype.Text `json:"external_workspace_id"`
	Source              string      `json:"source"`
}

func (q *Queries) CreateExternalWorkspace(ctx context.Context, arg CreateExternalWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createExternalWorkspace,
		arg.Name,
		arg.Slug,
		arg.ExternalWorkspaceID,
		arg.Source,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExternalWorkspaceID,
		&i.Source,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, created_at, updated_at, deleted_at, external_workspace_id, source
`

type CreateWorkspaceParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Name, arg.Slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExternalWorkspaceID,
		&i.Source,
	)
	return i, err
}

const getWorkspaceByExternalWorkspaceID = `-- name: GetWorkspaceByExternalWorkspaceID :one
SELECT id, name, slug, created_at, updated_at, deleted_at, external_workspace_id, source FROM workspaces
WHERE external_workspace_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkspaceByExternalWorkspaceID(ctx context.Context, externalWorkspaceID pgtype.Text) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByExternalWorkspaceID, externalWorkspaceID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExternalWorkspaceID,
		&i.Source,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, name, slug, created_at, updated_at, deleted_at, external_workspace_id, source FROM workspaces
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id pgtype.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExternalWorkspaceID,
		&i.Source,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT id, name, slug, created_at, updated_at, deleted_at, external_workspace_id, source FROM workspaces
WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExternalWorkspaceID,
		&i.Source,
	)
	return i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, name, slug, created_at, updated_at, deleted_at, external_workspace_id, source FROM workspaces
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListWorkspacesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListWorkspaces(ctx context.Context, arg ListWorkspacesParams) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspaces, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ExternalWorkspaceID,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesByUserID = `-- name: ListWorkspacesByUserID :many
SELECT w.id, w.name, w.slug, w.created_at, w.updated_at, w.deleted_at, w.external_workspace_id, w.source FROM workspaces w
JOIN workspace_members wm ON w.id = wm.workspace_id
WHERE wm.user_id = $1 AND w.deleted_at IS NULL
ORDER BY w.created_at DESC
LIMIT $2 OFFSET $3
`

type ListWorkspacesByUserIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListWorkspacesByUserID(ctx context.Context, arg ListWorkspacesByUserIDParams) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ExternalWorkspaceID,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWorkspace = `-- name: SoftDeleteWorkspace :exec
UPDATE workspaces SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteWorkspace(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteWorkspace, id)
	return err
}

const updateExternalWorkspace = `-- name: UpdateExternalWorkspace :one
UPDATE workspaces
SET name = $2,
    slug = $3,
    external_workspace_id = $4,
    source = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, name, slug, created_at, updated_at, deleted_at, external_workspace_id, source
`

type UpdateExternalWorkspaceParams struct {
	ID                  pgtype.UUID `json:"id"`
	Name                string      `json:"name"`
	Slug                string      `json:"slug"`
	ExternalWorkspaceID pgtype.Text `json:"external_workspace_id"`
	Source              string      `json:"source"`
}

func (q *Queries) UpdateExternalWorkspace(ctx context.Context, arg UpdateExternalWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateExternalWorkspace,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.ExternalWorkspaceID,
		arg.Source,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExternalWorkspaceID,
		&i.Source,
	)
	return i, err
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces
SET name = $2, slug = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, slug, created_at, updated_at, deleted_at, external_workspace_id, source
`

type UpdateWorkspaceParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Slug string      `json:"slug"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace, arg.ID, arg.Name, arg.Slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExternalWorkspaceID,
		&i.Source,
	)
	return i, err
}
